// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts_extra.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountWithNilos = `-- name: GetAccountWithNilos :one
SELECT a.id, a.user_id, a.currency, a.account_number, a.balance, COALESCE(n.nilos_id, '')::text as nilos_id
FROM accounts a
LEFT JOIN virtual_cards n ON n.account_id = a.id
WHERE a.id = $1
`

type GetAccountWithNilosRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Currency      string         `json:"currency"`
	AccountNumber string         `json:"account_number"`
	Balance       pgtype.Numeric `json:"balance"`
	NilosID       string         `json:"nilos_id"`
}

func (q *Queries) GetAccountWithNilos(ctx context.Context, id uuid.UUID) (GetAccountWithNilosRow, error) {
	row := q.db.QueryRow(ctx, getAccountWithNilos, id)
	var i GetAccountWithNilosRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AccountNumber,
		&i.Balance,
		&i.NilosID,
	)
	return i, err
}
