// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, currency, account_number)
VALUES ($1, $2, $3)
RETURNING id, user_id, currency, balance, available_balance, account_number, status, created_at, updated_at, nilos_account_id, nilos_customer_id, iban, bic, sort_code, account_number_uk, nomba_account_ref, nomba_account_holder_id, nomba_bank_name, nomba_bank_account_number, nomba_bank_account_name
`

type CreateAccountParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Currency      string    `json:"currency"`
	AccountNumber string    `json:"account_number"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.UserID, arg.Currency, arg.AccountNumber)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.AccountNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NilosAccountID,
		&i.NilosCustomerID,
		&i.Iban,
		&i.Bic,
		&i.SortCode,
		&i.AccountNumberUk,
		&i.NombaAccountRef,
		&i.NombaAccountHolderID,
		&i.NombaBankName,
		&i.NombaBankAccountNumber,
		&i.NombaBankAccountName,
	)
	return i, err
}

const creditAccount = `-- name: CreditAccount :one
UPDATE accounts
SET balance           = balance + $2,
    available_balance = available_balance + $2,
    updated_at        = NOW()
WHERE id = $1
RETURNING id, user_id, currency, balance, available_balance, account_number, status, created_at, updated_at, nilos_account_id, nilos_customer_id, iban, bic, sort_code, account_number_uk, nomba_account_ref, nomba_account_holder_id, nomba_bank_name, nomba_bank_account_number, nomba_bank_account_name
`

type CreditAccountParams struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) CreditAccount(ctx context.Context, arg CreditAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, creditAccount, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.AccountNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NilosAccountID,
		&i.NilosCustomerID,
		&i.Iban,
		&i.Bic,
		&i.SortCode,
		&i.AccountNumberUk,
		&i.NombaAccountRef,
		&i.NombaAccountHolderID,
		&i.NombaBankName,
		&i.NombaBankAccountNumber,
		&i.NombaBankAccountName,
	)
	return i, err
}

const debitAccount = `-- name: DebitAccount :one
UPDATE accounts
SET balance           = balance - $2,
    available_balance = available_balance - $2,
    updated_at        = NOW()
WHERE id = $1 AND available_balance >= $2
RETURNING id, user_id, currency, balance, available_balance, account_number, status, created_at, updated_at, nilos_account_id, nilos_customer_id, iban, bic, sort_code, account_number_uk, nomba_account_ref, nomba_account_holder_id, nomba_bank_name, nomba_bank_account_number, nomba_bank_account_name
`

type DebitAccountParams struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) DebitAccount(ctx context.Context, arg DebitAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, debitAccount, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.AccountNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NilosAccountID,
		&i.NilosCustomerID,
		&i.Iban,
		&i.Bic,
		&i.SortCode,
		&i.AccountNumberUk,
		&i.NombaAccountRef,
		&i.NombaAccountHolderID,
		&i.NombaBankName,
		&i.NombaBankAccountNumber,
		&i.NombaBankAccountName,
	)
	return i, err
}

const freezeAccount = `-- name: FreezeAccount :exec
UPDATE accounts
SET status = 'frozen', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) FreezeAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, freezeAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, currency, balance, available_balance, account_number, status, created_at, updated_at, nilos_account_id, nilos_customer_id, iban, bic, sort_code, account_number_uk, nomba_account_ref, nomba_account_holder_id, nomba_bank_name, nomba_bank_account_number, nomba_bank_account_name FROM accounts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.AccountNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NilosAccountID,
		&i.NilosCustomerID,
		&i.Iban,
		&i.Bic,
		&i.SortCode,
		&i.AccountNumberUk,
		&i.NombaAccountRef,
		&i.NombaAccountHolderID,
		&i.NombaBankName,
		&i.NombaBankAccountNumber,
		&i.NombaBankAccountName,
	)
	return i, err
}

const getAccountByNombaAccountNumber = `-- name: GetAccountByNombaAccountNumber :one
SELECT id, user_id, currency, balance, available_balance, account_number, status, created_at, updated_at, nilos_account_id, nilos_customer_id, iban, bic, sort_code, account_number_uk, nomba_account_ref, nomba_account_holder_id, nomba_bank_name, nomba_bank_account_number, nomba_bank_account_name FROM accounts
WHERE nomba_bank_account_number = $1
LIMIT 1
`

func (q *Queries) GetAccountByNombaAccountNumber(ctx context.Context, nombaBankAccountNumber *string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByNombaAccountNumber, nombaBankAccountNumber)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.AccountNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NilosAccountID,
		&i.NilosCustomerID,
		&i.Iban,
		&i.Bic,
		&i.SortCode,
		&i.AccountNumberUk,
		&i.NombaAccountRef,
		&i.NombaAccountHolderID,
		&i.NombaBankName,
		&i.NombaBankAccountNumber,
		&i.NombaBankAccountName,
	)
	return i, err
}

const getAccountByUserAndCurrency = `-- name: GetAccountByUserAndCurrency :one
SELECT id, user_id, currency, balance, available_balance, account_number, status, created_at, updated_at, nilos_account_id, nilos_customer_id, iban, bic, sort_code, account_number_uk, nomba_account_ref, nomba_account_holder_id, nomba_bank_name, nomba_bank_account_number, nomba_bank_account_name FROM accounts
WHERE user_id = $1 AND currency = $2
LIMIT 1
`

type GetAccountByUserAndCurrencyParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Currency string    `json:"currency"`
}

func (q *Queries) GetAccountByUserAndCurrency(ctx context.Context, arg GetAccountByUserAndCurrencyParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUserAndCurrency, arg.UserID, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.AccountNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NilosAccountID,
		&i.NilosCustomerID,
		&i.Iban,
		&i.Bic,
		&i.SortCode,
		&i.AccountNumberUk,
		&i.NombaAccountRef,
		&i.NombaAccountHolderID,
		&i.NombaBankName,
		&i.NombaBankAccountNumber,
		&i.NombaBankAccountName,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, user_id, currency, balance, available_balance, account_number, status, created_at, updated_at, nilos_account_id, nilos_customer_id, iban, bic, sort_code, account_number_uk, nomba_account_ref, nomba_account_holder_id, nomba_bank_name, nomba_bank_account_number, nomba_bank_account_name FROM accounts
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.AccountNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NilosAccountID,
		&i.NilosCustomerID,
		&i.Iban,
		&i.Bic,
		&i.SortCode,
		&i.AccountNumberUk,
		&i.NombaAccountRef,
		&i.NombaAccountHolderID,
		&i.NombaBankName,
		&i.NombaBankAccountNumber,
		&i.NombaBankAccountName,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, user_id, currency, balance, available_balance, account_number, status, created_at, updated_at, nilos_account_id, nilos_customer_id, iban, bic, sort_code, account_number_uk, nomba_account_ref, nomba_account_holder_id, nomba_bank_name, nomba_bank_account_number, nomba_bank_account_name FROM accounts
WHERE user_id = $1
ORDER BY currency
`

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Currency,
			&i.Balance,
			&i.AvailableBalance,
			&i.AccountNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NilosAccountID,
			&i.NilosCustomerID,
			&i.Iban,
			&i.Bic,
			&i.SortCode,
			&i.AccountNumberUk,
			&i.NombaAccountRef,
			&i.NombaAccountHolderID,
			&i.NombaBankName,
			&i.NombaBankAccountNumber,
			&i.NombaBankAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNilosAccountDetails = `-- name: UpdateNilosAccountDetails :exec
UPDATE accounts
SET nilos_account_id = $2,
    iban = $3,
    bic = $4,
    sort_code = $5,
    account_number_uk = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNilosAccountDetailsParams struct {
	ID              uuid.UUID `json:"id"`
	NilosAccountID  *string   `json:"nilos_account_id"`
	Iban            *string   `json:"iban"`
	Bic             *string   `json:"bic"`
	SortCode        *string   `json:"sort_code"`
	AccountNumberUk *string   `json:"account_number_uk"`
}

func (q *Queries) UpdateNilosAccountDetails(ctx context.Context, arg UpdateNilosAccountDetailsParams) error {
	_, err := q.db.Exec(ctx, updateNilosAccountDetails,
		arg.ID,
		arg.NilosAccountID,
		arg.Iban,
		arg.Bic,
		arg.SortCode,
		arg.AccountNumberUk,
	)
	return err
}

const updateNombaAccountDetails = `-- name: UpdateNombaAccountDetails :exec
UPDATE accounts
SET nomba_account_ref         = $2,
    nomba_account_holder_id   = $3,
    nomba_bank_name           = $4,
    nomba_bank_account_number = $5,
    nomba_bank_account_name   = $6,
    updated_at                = NOW()
WHERE id = $1
`

type UpdateNombaAccountDetailsParams struct {
	ID                     uuid.UUID `json:"id"`
	NombaAccountRef        *string   `json:"nomba_account_ref"`
	NombaAccountHolderID   *string   `json:"nomba_account_holder_id"`
	NombaBankName          *string   `json:"nomba_bank_name"`
	NombaBankAccountNumber *string   `json:"nomba_bank_account_number"`
	NombaBankAccountName   *string   `json:"nomba_bank_account_name"`
}

func (q *Queries) UpdateNombaAccountDetails(ctx context.Context, arg UpdateNombaAccountDetailsParams) error {
	_, err := q.db.Exec(ctx, updateNombaAccountDetails,
		arg.ID,
		arg.NombaAccountRef,
		arg.NombaAccountHolderID,
		arg.NombaBankName,
		arg.NombaBankAccountNumber,
		arg.NombaBankAccountName,
	)
	return err
}
