// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_limits.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserLimitOverride = `-- name: DeleteUserLimitOverride :exec
DELETE FROM user_limit_overrides WHERE user_id = $1
`

func (q *Queries) DeleteUserLimitOverride(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserLimitOverride, userID)
	return err
}

const getPlatformLimit = `-- name: GetPlatformLimit :one
SELECT tier, daily_withdrawal_usd, per_transaction_usd, monthly_volume_usd,
       max_holding_balance_usd, daily_transaction_count, updated_at, updated_by
FROM platform_limits
WHERE tier = $1
`

func (q *Queries) GetPlatformLimit(ctx context.Context, tier string) (PlatformLimit, error) {
	row := q.db.QueryRow(ctx, getPlatformLimit, tier)
	var i PlatformLimit
	err := row.Scan(
		&i.Tier,
		&i.DailyWithdrawalUsd,
		&i.PerTransactionUsd,
		&i.MonthlyVolumeUsd,
		&i.MaxHoldingBalanceUsd,
		&i.DailyTransactionCount,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserLimitOverride = `-- name: GetUserLimitOverride :one
SELECT user_id, daily_withdrawal_usd, per_transaction_usd, monthly_volume_usd,
       max_holding_balance_usd, daily_transaction_count, note, updated_at, updated_by
FROM user_limit_overrides
WHERE user_id = $1
`

func (q *Queries) GetUserLimitOverride(ctx context.Context, userID uuid.UUID) (UserLimitOverride, error) {
	row := q.db.QueryRow(ctx, getUserLimitOverride, userID)
	var i UserLimitOverride
	err := row.Scan(
		&i.UserID,
		&i.DailyWithdrawalUsd,
		&i.PerTransactionUsd,
		&i.MonthlyVolumeUsd,
		&i.MaxHoldingBalanceUsd,
		&i.DailyTransactionCount,
		&i.Note,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listPlatformLimits = `-- name: ListPlatformLimits :many
SELECT tier, daily_withdrawal_usd, per_transaction_usd, monthly_volume_usd,
       max_holding_balance_usd, daily_transaction_count, updated_at, updated_by
FROM platform_limits
ORDER BY tier
`

func (q *Queries) ListPlatformLimits(ctx context.Context) ([]PlatformLimit, error) {
	rows, err := q.db.Query(ctx, listPlatformLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformLimit{}
	for rows.Next() {
		var i PlatformLimit
		if err := rows.Scan(
			&i.Tier,
			&i.DailyWithdrawalUsd,
			&i.PerTransactionUsd,
			&i.MonthlyVolumeUsd,
			&i.MaxHoldingBalanceUsd,
			&i.DailyTransactionCount,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAccountType = `-- name: SetUserAccountType :one
UPDATE users
SET account_type = $2, updated_at = now()
WHERE id = $1
RETURNING id, account_type
`

type SetUserAccountTypeParams struct {
	ID          uuid.UUID `json:"id"`
	AccountType string    `json:"account_type"`
}

type SetUserAccountTypeRow struct {
	ID          uuid.UUID `json:"id"`
	AccountType string    `json:"account_type"`
}

func (q *Queries) SetUserAccountType(ctx context.Context, arg SetUserAccountTypeParams) (SetUserAccountTypeRow, error) {
	row := q.db.QueryRow(ctx, setUserAccountType, arg.ID, arg.AccountType)
	var i SetUserAccountTypeRow
	err := row.Scan(&i.ID, &i.AccountType)
	return i, err
}

const upsertPlatformLimit = `-- name: UpsertPlatformLimit :one
INSERT INTO platform_limits
    (tier, daily_withdrawal_usd, per_transaction_usd, monthly_volume_usd,
     max_holding_balance_usd, daily_transaction_count, updated_by, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (tier) DO UPDATE SET
    daily_withdrawal_usd    = EXCLUDED.daily_withdrawal_usd,
    per_transaction_usd     = EXCLUDED.per_transaction_usd,
    monthly_volume_usd      = EXCLUDED.monthly_volume_usd,
    max_holding_balance_usd = EXCLUDED.max_holding_balance_usd,
    daily_transaction_count = EXCLUDED.daily_transaction_count,
    updated_by              = EXCLUDED.updated_by,
    updated_at              = now()
RETURNING tier, daily_withdrawal_usd, per_transaction_usd, monthly_volume_usd,
          max_holding_balance_usd, daily_transaction_count, updated_at, updated_by
`

type UpsertPlatformLimitParams struct {
	Tier                  string     `json:"tier"`
	DailyWithdrawalUsd    float64    `json:"daily_withdrawal_usd"`
	PerTransactionUsd     float64    `json:"per_transaction_usd"`
	MonthlyVolumeUsd      float64    `json:"monthly_volume_usd"`
	MaxHoldingBalanceUsd  float64    `json:"max_holding_balance_usd"`
	DailyTransactionCount int32      `json:"daily_transaction_count"`
	UpdatedBy             *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpsertPlatformLimit(ctx context.Context, arg UpsertPlatformLimitParams) (PlatformLimit, error) {
	row := q.db.QueryRow(ctx, upsertPlatformLimit,
		arg.Tier,
		arg.DailyWithdrawalUsd,
		arg.PerTransactionUsd,
		arg.MonthlyVolumeUsd,
		arg.MaxHoldingBalanceUsd,
		arg.DailyTransactionCount,
		arg.UpdatedBy,
	)
	var i PlatformLimit
	err := row.Scan(
		&i.Tier,
		&i.DailyWithdrawalUsd,
		&i.PerTransactionUsd,
		&i.MonthlyVolumeUsd,
		&i.MaxHoldingBalanceUsd,
		&i.DailyTransactionCount,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertUserLimitOverride = `-- name: UpsertUserLimitOverride :one
INSERT INTO user_limit_overrides
    (user_id, daily_withdrawal_usd, per_transaction_usd, monthly_volume_usd,
     max_holding_balance_usd, daily_transaction_count, note, updated_by, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (user_id) DO UPDATE SET
    daily_withdrawal_usd    = EXCLUDED.daily_withdrawal_usd,
    per_transaction_usd     = EXCLUDED.per_transaction_usd,
    monthly_volume_usd      = EXCLUDED.monthly_volume_usd,
    max_holding_balance_usd = EXCLUDED.max_holding_balance_usd,
    daily_transaction_count = EXCLUDED.daily_transaction_count,
    note                    = EXCLUDED.note,
    updated_by              = EXCLUDED.updated_by,
    updated_at              = now()
RETURNING user_id, daily_withdrawal_usd, per_transaction_usd, monthly_volume_usd,
          max_holding_balance_usd, daily_transaction_count, note, updated_at, updated_by
`

type UpsertUserLimitOverrideParams struct {
	UserID                uuid.UUID  `json:"user_id"`
	DailyWithdrawalUsd    *float64   `json:"daily_withdrawal_usd"`
	PerTransactionUsd     *float64   `json:"per_transaction_usd"`
	MonthlyVolumeUsd      *float64   `json:"monthly_volume_usd"`
	MaxHoldingBalanceUsd  *float64   `json:"max_holding_balance_usd"`
	DailyTransactionCount *int32     `json:"daily_transaction_count"`
	Note                  string     `json:"note"`
	UpdatedBy             *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpsertUserLimitOverride(ctx context.Context, arg UpsertUserLimitOverrideParams) (UserLimitOverride, error) {
	row := q.db.QueryRow(ctx, upsertUserLimitOverride,
		arg.UserID,
		arg.DailyWithdrawalUsd,
		arg.PerTransactionUsd,
		arg.MonthlyVolumeUsd,
		arg.MaxHoldingBalanceUsd,
		arg.DailyTransactionCount,
		arg.Note,
		arg.UpdatedBy,
	)
	var i UserLimitOverride
	err := row.Scan(
		&i.UserID,
		&i.DailyWithdrawalUsd,
		&i.PerTransactionUsd,
		&i.MonthlyVolumeUsd,
		&i.MaxHoldingBalanceUsd,
		&i.DailyTransactionCount,
		&i.Note,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
