// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const acceptStaffInvite = `-- name: AcceptStaffInvite :exec
UPDATE admin_staff
SET user_id = $1, invite_token = NULL, invite_accepted_at = now(), updated_at = now(), is_active = true
WHERE invite_token = $2
`

type AcceptStaffInviteParams struct {
	UserID      *uuid.UUID `json:"user_id"`
	InviteToken *string    `json:"invite_token"`
}

func (q *Queries) AcceptStaffInvite(ctx context.Context, arg AcceptStaffInviteParams) error {
	_, err := q.db.Exec(ctx, acceptStaffInvite, arg.UserID, arg.InviteToken)
	return err
}

const countAdminAuditLogs = `-- name: CountAdminAuditLogs :one
SELECT count(*) FROM admin_audit_logs
WHERE ($1::uuid IS NULL OR staff_id = $1)
  AND ($2::varchar = '' OR resource = $2)
  AND ($3::varchar = '' OR resource_id = $3)
`

type CountAdminAuditLogsParams struct {
	StaffID    *uuid.UUID `json:"staff_id"`
	Resource   string     `json:"resource"`
	ResourceID string     `json:"resource_id"`
}

func (q *Queries) CountAdminAuditLogs(ctx context.Context, arg CountAdminAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminAuditLogs, arg.StaffID, arg.Resource, arg.ResourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaffMembers = `-- name: CountStaffMembers :one
SELECT count(*) FROM admin_staff
WHERE ($1::boolean = true OR is_active = true)
`

func (q *Queries) CountStaffMembers(ctx context.Context, includeInactive bool) (int64, error) {
	row := q.db.QueryRow(ctx, countStaffMembers, includeInactive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminAuditLog = `-- name: CreateAdminAuditLog :one
INSERT INTO admin_audit_logs (
    staff_id, staff_name, staff_email, action, resource, resource_id, details, ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, staff_id, staff_name, staff_email, action, resource, resource_id, details, ip_address, created_at
`

type CreateAdminAuditLogParams struct {
	StaffID    uuid.UUID `json:"staff_id"`
	StaffName  string    `json:"staff_name"`
	StaffEmail string    `json:"staff_email"`
	Action     string    `json:"action"`
	Resource   string    `json:"resource"`
	ResourceID *string   `json:"resource_id"`
	Details    []byte    `json:"details"`
	IPAddress  *string   `json:"ip_address"`
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAdminAuditLog,
		arg.StaffID,
		arg.StaffName,
		arg.StaffEmail,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Details,
		arg.IPAddress,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.StaffName,
		&i.StaffEmail,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Details,
		&i.IPAddress,
		&i.CreatedAt,
	)
	return i, err
}

const createStaffMember = `-- name: CreateStaffMember :one
INSERT INTO admin_staff (
    email, name, role, custom_permissions, revoked_permissions, invited_by, invite_token
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, email, name, role, custom_permissions, revoked_permissions, is_active, invited_by, invite_token, invite_accepted_at, last_login_at, created_at, updated_at
`

type CreateStaffMemberParams struct {
	Email              string          `json:"email"`
	Name               string          `json:"name"`
	Role               string          `json:"role"`
	CustomPermissions  json.RawMessage `json:"custom_permissions"`
	RevokedPermissions json.RawMessage `json:"revoked_permissions"`
	InvitedBy          *uuid.UUID      `json:"invited_by"`
	InviteToken        *string         `json:"invite_token"`
}

func (q *Queries) CreateStaffMember(ctx context.Context, arg CreateStaffMemberParams) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, createStaffMember,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.CustomPermissions,
		arg.RevokedPermissions,
		arg.InvitedBy,
		arg.InviteToken,
	)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CustomPermissions,
		&i.RevokedPermissions,
		&i.IsActive,
		&i.InvitedBy,
		&i.InviteToken,
		&i.InviteAcceptedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableStaffMember = `-- name: DisableStaffMember :exec
UPDATE admin_staff SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DisableStaffMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableStaffMember, id)
	return err
}

const enableStaffMember = `-- name: EnableStaffMember :exec
UPDATE admin_staff SET is_active = true, updated_at = now() WHERE id = $1
`

func (q *Queries) EnableStaffMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableStaffMember, id)
	return err
}

const getStaffMemberByEmail = `-- name: GetStaffMemberByEmail :one
SELECT id, user_id, email, name, role, custom_permissions, revoked_permissions, is_active, invited_by, invite_token, invite_accepted_at, last_login_at, created_at, updated_at FROM admin_staff WHERE email = $1
`

func (q *Queries) GetStaffMemberByEmail(ctx context.Context, email string) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, getStaffMemberByEmail, email)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CustomPermissions,
		&i.RevokedPermissions,
		&i.IsActive,
		&i.InvitedBy,
		&i.InviteToken,
		&i.InviteAcceptedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffMemberByID = `-- name: GetStaffMemberByID :one
SELECT id, user_id, email, name, role, custom_permissions, revoked_permissions, is_active, invited_by, invite_token, invite_accepted_at, last_login_at, created_at, updated_at FROM admin_staff WHERE id = $1
`

func (q *Queries) GetStaffMemberByID(ctx context.Context, id uuid.UUID) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, getStaffMemberByID, id)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CustomPermissions,
		&i.RevokedPermissions,
		&i.IsActive,
		&i.InvitedBy,
		&i.InviteToken,
		&i.InviteAcceptedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffMemberByInviteToken = `-- name: GetStaffMemberByInviteToken :one
SELECT id, user_id, email, name, role, custom_permissions, revoked_permissions, is_active, invited_by, invite_token, invite_accepted_at, last_login_at, created_at, updated_at FROM admin_staff WHERE invite_token = $1
`

func (q *Queries) GetStaffMemberByInviteToken(ctx context.Context, inviteToken *string) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, getStaffMemberByInviteToken, inviteToken)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CustomPermissions,
		&i.RevokedPermissions,
		&i.IsActive,
		&i.InvitedBy,
		&i.InviteToken,
		&i.InviteAcceptedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffMemberByUserID = `-- name: GetStaffMemberByUserID :one
SELECT id, user_id, email, name, role, custom_permissions, revoked_permissions, is_active, invited_by, invite_token, invite_accepted_at, last_login_at, created_at, updated_at FROM admin_staff WHERE user_id = $1
`

func (q *Queries) GetStaffMemberByUserID(ctx context.Context, userID *uuid.UUID) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, getStaffMemberByUserID, userID)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CustomPermissions,
		&i.RevokedPermissions,
		&i.IsActive,
		&i.InvitedBy,
		&i.InviteToken,
		&i.InviteAcceptedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminAuditLogs = `-- name: ListAdminAuditLogs :many
SELECT id, staff_id, staff_name, staff_email, action, resource, resource_id, details, ip_address, created_at FROM admin_audit_logs
WHERE ($3::uuid IS NULL OR staff_id = $3)
  AND ($4::varchar = '' OR resource = $4)
  AND ($5::varchar = '' OR resource_id = $5)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminAuditLogsParams struct {
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
	StaffID    *uuid.UUID `json:"staff_id"`
	Resource   string     `json:"resource"`
	ResourceID string     `json:"resource_id"`
}

func (q *Queries) ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.StaffID,
		arg.Resource,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.StaffName,
			&i.StaffEmail,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Details,
			&i.IPAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffMembers = `-- name: ListStaffMembers :many
SELECT id, user_id, email, name, role, custom_permissions, revoked_permissions, is_active, invited_by, invite_token, invite_accepted_at, last_login_at, created_at, updated_at FROM admin_staff
WHERE ($1::boolean = true OR is_active = true)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListStaffMembersParams struct {
	IncludeInactive bool  `json:"include_inactive"`
	Offset          int32 `json:"offset"`
	Limit           int32 `json:"limit"`
}

func (q *Queries) ListStaffMembers(ctx context.Context, arg ListStaffMembersParams) ([]AdminStaff, error) {
	rows, err := q.db.Query(ctx, listStaffMembers, arg.IncludeInactive, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminStaff{}
	for rows.Next() {
		var i AdminStaff
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CustomPermissions,
			&i.RevokedPermissions,
			&i.IsActive,
			&i.InvitedBy,
			&i.InviteToken,
			&i.InviteAcceptedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaffLastLogin = `-- name: UpdateStaffLastLogin :exec
UPDATE admin_staff SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateStaffLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateStaffLastLogin, id)
	return err
}

const updateStaffMember = `-- name: UpdateStaffMember :one
UPDATE admin_staff
SET role = coalesce($1, role),
    custom_permissions = coalesce($2, custom_permissions),
    revoked_permissions = coalesce($3, revoked_permissions),
    updated_at = now()
WHERE id = $4
RETURNING id, user_id, email, name, role, custom_permissions, revoked_permissions, is_active, invited_by, invite_token, invite_accepted_at, last_login_at, created_at, updated_at
`

type UpdateStaffMemberParams struct {
	Role               *string   `json:"role"`
	CustomPermissions  []byte    `json:"custom_permissions"`
	RevokedPermissions []byte    `json:"revoked_permissions"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdateStaffMember(ctx context.Context, arg UpdateStaffMemberParams) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, updateStaffMember,
		arg.Role,
		arg.CustomPermissions,
		arg.RevokedPermissions,
		arg.ID,
	)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CustomPermissions,
		&i.RevokedPermissions,
		&i.IsActive,
		&i.InvitedBy,
		&i.InviteToken,
		&i.InviteAcceptedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
