// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_extra.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminDashboardStats = `-- name: GetAdminDashboardStats :one
SELECT
    count(*)::bigint as total_users,
    count(*) FILTER (WHERE is_active = true)::bigint as active_users,
    count(*) FILTER (WHERE is_active = false)::bigint as disabled_users,
    count(*) FILTER (WHERE kyc_status = 'pending')::bigint as pending_kyc,
    count(*) FILTER (WHERE kyc_status = 'approved')::bigint as approved_kyc,
    count(*) FILTER (WHERE kyc_status = 'rejected')::bigint as rejected_kyc,
    0::bigint as total_staff,
    0::bigint as active_staff,
    0::bigint as tx_count_30d,
    0::float8 as tx_volume_30d,
    count(*) FILTER (WHERE created_at >= now() - interval '7 days')::bigint as new_users_7d,
    count(*) FILTER (WHERE created_at >= now() - interval '30 days')::bigint as new_users_30d
FROM users
`

type GetAdminDashboardStatsRow struct {
	TotalUsers    int64   `json:"total_users"`
	ActiveUsers   int64   `json:"active_users"`
	DisabledUsers int64   `json:"disabled_users"`
	PendingKYC    int64   `json:"pending_kyc"`
	ApprovedKYC   int64   `json:"approved_kyc"`
	RejectedKYC   int64   `json:"rejected_kyc"`
	TotalStaff    int64   `json:"total_staff"`
	ActiveStaff   int64   `json:"active_staff"`
	TxCount30d    int64   `json:"tx_count_30d"`
	TxVolume30d   float64 `json:"tx_volume_30d"`
	NewUsers7d    int64   `json:"new_users_7d"`
	NewUsers30d   int64   `json:"new_users_30d"`
}

func (q *Queries) GetAdminDashboardStats(ctx context.Context) (GetAdminDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminDashboardStats)
	var i GetAdminDashboardStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.DisabledUsers,
		&i.PendingKYC,
		&i.ApprovedKYC,
		&i.RejectedKYC,
		&i.TotalStaff,
		&i.ActiveStaff,
		&i.TxCount30d,
		&i.TxVolume30d,
		&i.NewUsers7d,
		&i.NewUsers30d,
	)
	return i, err
}

const getAdminUserView = `-- name: GetAdminUserView :one
SELECT
    id, phone_number, email, first_name, last_name, kyc_status,
    is_active, role, 0::int as account_count, created_at,
    now()::timestamp as last_login_at
FROM users WHERE id = $1
`

type GetAdminUserViewRow struct {
	ID           uuid.UUID        `json:"id"`
	PhoneNumber  string           `json:"phone_number"`
	Email        *string          `json:"email"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	KycStatus    string           `json:"kyc_status"`
	IsActive     bool             `json:"is_active"`
	Role         string           `json:"role"`
	AccountCount int32            `json:"account_count"`
	CreatedAt    time.Time        `json:"created_at"`
	LastLoginAt  pgtype.Timestamp `json:"last_login_at"`
}

func (q *Queries) GetAdminUserView(ctx context.Context, id uuid.UUID) (GetAdminUserViewRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserView, id)
	var i GetAdminUserViewRow
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.KycStatus,
		&i.IsActive,
		&i.Role,
		&i.AccountCount,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
