// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business_analytics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTransactionStatsSince = `-- name: GetTransactionStatsSince :one
SELECT
    count(*)::bigint AS tx_count,
    COALESCE(sum(abs(transactions.amount)), 0)::float8 AS total_volume,
    COALESCE(avg(abs(transactions.amount)), 0)::float8 AS avg_amount,
    COALESCE(max(abs(transactions.amount)), 0)::float8 AS max_amount
FROM transactions
WHERE transactions.account_id IN (SELECT id FROM accounts WHERE user_id = $1)
  AND transactions.created_at >= $2
`

type GetTransactionStatsSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetTransactionStatsSinceRow struct {
	TxCount     int64   `json:"tx_count"`
	TotalVolume float64 `json:"total_volume"`
	AvgAmount   float64 `json:"avg_amount"`
	MaxAmount   float64 `json:"max_amount"`
}

// Aggregate transaction stats across all of a user's fiat accounts since a
// given time. Powers the business analytics dashboard (count / volume / avg /
// largest). Volume is the sum of absolute amounts (both in- and out-flows).
func (q *Queries) GetTransactionStatsSince(ctx context.Context, arg GetTransactionStatsSinceParams) (GetTransactionStatsSinceRow, error) {
	row := q.db.QueryRow(ctx, getTransactionStatsSince, arg.UserID, arg.CreatedAt)
	var i GetTransactionStatsSinceRow
	err := row.Scan(
		&i.TxCount,
		&i.TotalVolume,
		&i.AvgAmount,
		&i.MaxAmount,
	)
	return i, err
}

const getVolumeByCurrencySince = `-- name: GetVolumeByCurrencySince :many
SELECT
    transactions.currency::text AS currency,
    count(*)::bigint AS tx_count,
    COALESCE(sum(abs(transactions.amount)), 0)::float8 AS volume
FROM transactions
WHERE transactions.account_id IN (SELECT id FROM accounts WHERE user_id = $1)
  AND transactions.created_at >= $2
GROUP BY transactions.currency
ORDER BY volume DESC
`

type GetVolumeByCurrencySinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetVolumeByCurrencySinceRow struct {
	Currency string  `json:"currency"`
	TxCount  int64   `json:"tx_count"`
	Volume   float64 `json:"volume"`
}

// Per-currency transaction count and volume since a given time. Gives business
// accounts a currency-level breakdown of their activity.
func (q *Queries) GetVolumeByCurrencySince(ctx context.Context, arg GetVolumeByCurrencySinceParams) ([]GetVolumeByCurrencySinceRow, error) {
	rows, err := q.db.Query(ctx, getVolumeByCurrencySince, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVolumeByCurrencySinceRow{}
	for rows.Next() {
		var i GetVolumeByCurrencySinceRow
		if err := rows.Scan(&i.Currency, &i.TxCount, &i.Volume); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
