// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptMerchantStaffInvite = `-- name: AcceptMerchantStaffInvite :exec
UPDATE merchant_staff
SET staff_user_id = $1, status = 'active', invite_token = NULL, updated_at = now()
WHERE invite_token = $2
`

type AcceptMerchantStaffInviteParams struct {
	StaffUserID *uuid.UUID `json:"staff_user_id"`
	InviteToken *string    `json:"invite_token"`
}

func (q *Queries) AcceptMerchantStaffInvite(ctx context.Context, arg AcceptMerchantStaffInviteParams) error {
	_, err := q.db.Exec(ctx, acceptMerchantStaffInvite, arg.StaffUserID, arg.InviteToken)
	return err
}

const createBusinessDirector = `-- name: CreateBusinessDirector :one

INSERT INTO business_directors (
    user_id,
    first_name,
    last_name,
    job_title,
    date_of_birth,
    nationality,
    phone_number
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, first_name, last_name, job_title, date_of_birth, nationality, phone_number, created_at, updated_at
`

type CreateBusinessDirectorParams struct {
	UserID      uuid.UUID `json:"user_id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	JobTitle    string    `json:"job_title"`
	DateOfBirth time.Time `json:"date_of_birth"`
	Nationality string    `json:"nationality"`
	PhoneNumber string    `json:"phone_number"`
}

// Business director queries
func (q *Queries) CreateBusinessDirector(ctx context.Context, arg CreateBusinessDirectorParams) (BusinessDirector, error) {
	row := q.db.QueryRow(ctx, createBusinessDirector,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.JobTitle,
		arg.DateOfBirth,
		arg.Nationality,
		arg.PhoneNumber,
	)
	var i BusinessDirector
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.JobTitle,
		&i.DateOfBirth,
		&i.Nationality,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBusinessProfile = `-- name: CreateBusinessProfile :one

INSERT INTO business_profiles (
    user_id,
    company_legal_name,
    company_registration_no,
    industry,
    country_of_incorporation,
    annual_revenue,
    business_website
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING user_id, company_legal_name, company_registration_no, industry, country_of_incorporation, annual_revenue, business_website, directors_complete, documents_complete, created_at, updated_at
`

type CreateBusinessProfileParams struct {
	UserID                 uuid.UUID `json:"user_id"`
	CompanyLegalName       string    `json:"company_legal_name"`
	CompanyRegistrationNo  string    `json:"company_registration_no"`
	Industry               string    `json:"industry"`
	CountryOfIncorporation string    `json:"country_of_incorporation"`
	AnnualRevenue          string    `json:"annual_revenue"`
	BusinessWebsite        *string   `json:"business_website"`
}

// Business profile queries
func (q *Queries) CreateBusinessProfile(ctx context.Context, arg CreateBusinessProfileParams) (BusinessProfile, error) {
	row := q.db.QueryRow(ctx, createBusinessProfile,
		arg.UserID,
		arg.CompanyLegalName,
		arg.CompanyRegistrationNo,
		arg.Industry,
		arg.CountryOfIncorporation,
		arg.AnnualRevenue,
		arg.BusinessWebsite,
	)
	var i BusinessProfile
	err := row.Scan(
		&i.UserID,
		&i.CompanyLegalName,
		&i.CompanyRegistrationNo,
		&i.Industry,
		&i.CountryOfIncorporation,
		&i.AnnualRevenue,
		&i.BusinessWebsite,
		&i.DirectorsComplete,
		&i.DocumentsComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMerchantStaff = `-- name: CreateMerchantStaff :one

INSERT INTO merchant_staff (
    business_user_id,
    email,
    role,
    invite_token
) VALUES ($1, $2, $3, $4)
RETURNING id, business_user_id, staff_user_id, email, role, status, invite_token, created_at, updated_at
`

type CreateMerchantStaffParams struct {
	BusinessUserID uuid.UUID `json:"business_user_id"`
	Email          string    `json:"email"`
	Role           string    `json:"role"`
	InviteToken    *string   `json:"invite_token"`
}

// Merchant staff queries
func (q *Queries) CreateMerchantStaff(ctx context.Context, arg CreateMerchantStaffParams) (MerchantStaff, error) {
	row := q.db.QueryRow(ctx, createMerchantStaff,
		arg.BusinessUserID,
		arg.Email,
		arg.Role,
		arg.InviteToken,
	)
	var i MerchantStaff
	err := row.Scan(
		&i.ID,
		&i.BusinessUserID,
		&i.StaffUserID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBusinessDirector = `-- name: DeleteBusinessDirector :exec
DELETE FROM business_directors
WHERE id = $1 AND user_id = $2
`

type DeleteBusinessDirectorParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBusinessDirector(ctx context.Context, arg DeleteBusinessDirectorParams) error {
	_, err := q.db.Exec(ctx, deleteBusinessDirector, arg.ID, arg.UserID)
	return err
}

const deleteMerchantStaff = `-- name: DeleteMerchantStaff :exec
DELETE FROM merchant_staff WHERE id = $1 AND business_user_id = $2
`

type DeleteMerchantStaffParams struct {
	ID             uuid.UUID `json:"id"`
	BusinessUserID uuid.UUID `json:"business_user_id"`
}

func (q *Queries) DeleteMerchantStaff(ctx context.Context, arg DeleteMerchantStaffParams) error {
	_, err := q.db.Exec(ctx, deleteMerchantStaff, arg.ID, arg.BusinessUserID)
	return err
}

const getActiveMerchantStaffByUser = `-- name: GetActiveMerchantStaffByUser :many
SELECT id, business_user_id, staff_user_id, email, role, status, invite_token, created_at, updated_at FROM merchant_staff
WHERE staff_user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveMerchantStaffByUser(ctx context.Context, staffUserID *uuid.UUID) ([]MerchantStaff, error) {
	rows, err := q.db.Query(ctx, getActiveMerchantStaffByUser, staffUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantStaff{}
	for rows.Next() {
		var i MerchantStaff
		if err := rows.Scan(
			&i.ID,
			&i.BusinessUserID,
			&i.StaffUserID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.InviteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessProfileByUserID = `-- name: GetBusinessProfileByUserID :one
SELECT user_id, company_legal_name, company_registration_no, industry, country_of_incorporation, annual_revenue, business_website, directors_complete, documents_complete, created_at, updated_at FROM business_profiles WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetBusinessProfileByUserID(ctx context.Context, userID uuid.UUID) (BusinessProfile, error) {
	row := q.db.QueryRow(ctx, getBusinessProfileByUserID, userID)
	var i BusinessProfile
	err := row.Scan(
		&i.UserID,
		&i.CompanyLegalName,
		&i.CompanyRegistrationNo,
		&i.Industry,
		&i.CountryOfIncorporation,
		&i.AnnualRevenue,
		&i.BusinessWebsite,
		&i.DirectorsComplete,
		&i.DocumentsComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantStaffByEmailAndBusiness = `-- name: GetMerchantStaffByEmailAndBusiness :one
SELECT id, business_user_id, staff_user_id, email, role, status, invite_token, created_at, updated_at FROM merchant_staff WHERE email = $1 AND business_user_id = $2
`

type GetMerchantStaffByEmailAndBusinessParams struct {
	Email          string    `json:"email"`
	BusinessUserID uuid.UUID `json:"business_user_id"`
}

func (q *Queries) GetMerchantStaffByEmailAndBusiness(ctx context.Context, arg GetMerchantStaffByEmailAndBusinessParams) (MerchantStaff, error) {
	row := q.db.QueryRow(ctx, getMerchantStaffByEmailAndBusiness, arg.Email, arg.BusinessUserID)
	var i MerchantStaff
	err := row.Scan(
		&i.ID,
		&i.BusinessUserID,
		&i.StaffUserID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantStaffByID = `-- name: GetMerchantStaffByID :one
SELECT id, business_user_id, staff_user_id, email, role, status, invite_token, created_at, updated_at FROM merchant_staff WHERE id = $1
`

func (q *Queries) GetMerchantStaffByID(ctx context.Context, id uuid.UUID) (MerchantStaff, error) {
	row := q.db.QueryRow(ctx, getMerchantStaffByID, id)
	var i MerchantStaff
	err := row.Scan(
		&i.ID,
		&i.BusinessUserID,
		&i.StaffUserID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantStaffByInviteToken = `-- name: GetMerchantStaffByInviteToken :one
SELECT id, business_user_id, staff_user_id, email, role, status, invite_token, created_at, updated_at FROM merchant_staff WHERE invite_token = $1
`

func (q *Queries) GetMerchantStaffByInviteToken(ctx context.Context, inviteToken *string) (MerchantStaff, error) {
	row := q.db.QueryRow(ctx, getMerchantStaffByInviteToken, inviteToken)
	var i MerchantStaff
	err := row.Scan(
		&i.ID,
		&i.BusinessUserID,
		&i.StaffUserID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBusinessDirectors = `-- name: ListBusinessDirectors :many
SELECT id, user_id, first_name, last_name, job_title, date_of_birth, nationality, phone_number, created_at, updated_at FROM business_directors
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBusinessDirectors(ctx context.Context, userID uuid.UUID) ([]BusinessDirector, error) {
	rows, err := q.db.Query(ctx, listBusinessDirectors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessDirector{}
	for rows.Next() {
		var i BusinessDirector
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.JobTitle,
			&i.DateOfBirth,
			&i.Nationality,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantStaff = `-- name: ListMerchantStaff :many
SELECT id, business_user_id, staff_user_id, email, role, status, invite_token, created_at, updated_at FROM merchant_staff
WHERE business_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMerchantStaff(ctx context.Context, businessUserID uuid.UUID) ([]MerchantStaff, error) {
	rows, err := q.db.Query(ctx, listMerchantStaff, businessUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantStaff{}
	for rows.Next() {
		var i MerchantStaff
		if err := rows.Scan(
			&i.ID,
			&i.BusinessUserID,
			&i.StaffUserID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.InviteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDirectorsComplete = `-- name: MarkDirectorsComplete :exec
UPDATE business_profiles
SET directors_complete = true, updated_at = now()
WHERE user_id = $1
`

func (q *Queries) MarkDirectorsComplete(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDirectorsComplete, userID)
	return err
}

const markDocumentsComplete = `-- name: MarkDocumentsComplete :exec
UPDATE business_profiles
SET documents_complete = true, updated_at = now()
WHERE user_id = $1
`

func (q *Queries) MarkDocumentsComplete(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDocumentsComplete, userID)
	return err
}

const saveBusinessProfile = `-- name: SaveBusinessProfile :one
INSERT INTO business_profiles (
    user_id,
    company_legal_name,
    company_registration_no,
    industry,
    country_of_incorporation,
    annual_revenue,
    business_website
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE SET
    company_legal_name = EXCLUDED.company_legal_name,
    company_registration_no = EXCLUDED.company_registration_no,
    industry = EXCLUDED.industry,
    country_of_incorporation = EXCLUDED.country_of_incorporation,
    annual_revenue = EXCLUDED.annual_revenue,
    business_website = EXCLUDED.business_website,
    updated_at = now()
RETURNING user_id, company_legal_name, company_registration_no, industry, country_of_incorporation, annual_revenue, business_website, directors_complete, documents_complete, created_at, updated_at
`

type SaveBusinessProfileParams struct {
	UserID                 uuid.UUID `json:"user_id"`
	CompanyLegalName       string    `json:"company_legal_name"`
	CompanyRegistrationNo  string    `json:"company_registration_no"`
	Industry               string    `json:"industry"`
	CountryOfIncorporation string    `json:"country_of_incorporation"`
	AnnualRevenue          string    `json:"annual_revenue"`
	BusinessWebsite        *string   `json:"business_website"`
}

func (q *Queries) SaveBusinessProfile(ctx context.Context, arg SaveBusinessProfileParams) (BusinessProfile, error) {
	row := q.db.QueryRow(ctx, saveBusinessProfile,
		arg.UserID,
		arg.CompanyLegalName,
		arg.CompanyRegistrationNo,
		arg.Industry,
		arg.CountryOfIncorporation,
		arg.AnnualRevenue,
		arg.BusinessWebsite,
	)
	var i BusinessProfile
	err := row.Scan(
		&i.UserID,
		&i.CompanyLegalName,
		&i.CompanyRegistrationNo,
		&i.Industry,
		&i.CountryOfIncorporation,
		&i.AnnualRevenue,
		&i.BusinessWebsite,
		&i.DirectorsComplete,
		&i.DocumentsComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMerchantStaffRole = `-- name: UpdateMerchantStaffRole :exec
UPDATE merchant_staff
SET role = $1, updated_at = now()
WHERE id = $2 AND business_user_id = $3
`

type UpdateMerchantStaffRoleParams struct {
	Role           string    `json:"role"`
	ID             uuid.UUID `json:"id"`
	BusinessUserID uuid.UUID `json:"business_user_id"`
}

func (q *Queries) UpdateMerchantStaffRole(ctx context.Context, arg UpdateMerchantStaffRoleParams) error {
	_, err := q.db.Exec(ctx, updateMerchantStaffRole, arg.Role, arg.ID, arg.BusinessUserID)
	return err
}
