// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: caas.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCaasWalletFull = `-- name: CreateCaasWalletFull :one

INSERT INTO caas_wallets (user_id, caas_wallet_id, blind_index, abstraction_address)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, caas_wallet_id, abstraction_address, is_active, created_at, blind_index
`

type CreateCaasWalletFullParams struct {
	UserID             uuid.UUID `json:"user_id"`
	CaasWalletID       string    `json:"caas_wallet_id"`
	BlindIndex         *string   `json:"blind_index"`
	AbstractionAddress string    `json:"abstraction_address"`
}

// ─── CaaS wallet queries ──────────────────────────────────────────────────────
func (q *Queries) CreateCaasWalletFull(ctx context.Context, arg CreateCaasWalletFullParams) (CaasWallet, error) {
	row := q.db.QueryRow(ctx, createCaasWalletFull,
		arg.UserID,
		arg.CaasWalletID,
		arg.BlindIndex,
		arg.AbstractionAddress,
	)
	var i CaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWalletID,
		&i.AbstractionAddress,
		&i.IsActive,
		&i.CreatedAt,
		&i.BlindIndex,
	)
	return i, err
}

const createCaasWithdrawal = `-- name: CreateCaasWithdrawal :one

INSERT INTO caas_withdrawals
    (user_id, caas_withdrawal_id, phone, amount, token, payout_mobile, payout_network, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, caas_withdrawal_id, phone, amount, token, payout_mobile, payout_network, idempotency_key, status, created_at, updated_at
`

type CreateCaasWithdrawalParams struct {
	UserID           uuid.UUID `json:"user_id"`
	CaasWithdrawalID string    `json:"caas_withdrawal_id"`
	Phone            string    `json:"phone"`
	Amount           string    `json:"amount"`
	Token            string    `json:"token"`
	PayoutMobile     string    `json:"payout_mobile"`
	PayoutNetwork    string    `json:"payout_network"`
	IdempotencyKey   string    `json:"idempotency_key"`
}

// ─── CaaS withdrawal queries ──────────────────────────────────────────────────
func (q *Queries) CreateCaasWithdrawal(ctx context.Context, arg CreateCaasWithdrawalParams) (CaasWithdrawal, error) {
	row := q.db.QueryRow(ctx, createCaasWithdrawal,
		arg.UserID,
		arg.CaasWithdrawalID,
		arg.Phone,
		arg.Amount,
		arg.Token,
		arg.PayoutMobile,
		arg.PayoutNetwork,
		arg.IdempotencyKey,
	)
	var i CaasWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWithdrawalID,
		&i.Phone,
		&i.Amount,
		&i.Token,
		&i.PayoutMobile,
		&i.PayoutNetwork,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFXQuote = `-- name: CreateFXQuote :one

INSERT INTO fx_quotes (user_id, quote_id, fiat_amount, local_currency, target_token, rate, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, quote_id, fiat_amount, local_currency, target_token, rate, expires_at, used, created_at
`

type CreateFXQuoteParams struct {
	UserID        uuid.UUID      `json:"user_id"`
	QuoteID       string         `json:"quote_id"`
	FiatAmount    pgtype.Numeric `json:"fiat_amount"`
	LocalCurrency string         `json:"local_currency"`
	TargetToken   string         `json:"target_token"`
	Rate          pgtype.Numeric `json:"rate"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

// ─── FX quote queries ─────────────────────────────────────────────────────────
func (q *Queries) CreateFXQuote(ctx context.Context, arg CreateFXQuoteParams) (FxQuote, error) {
	row := q.db.QueryRow(ctx, createFXQuote,
		arg.UserID,
		arg.QuoteID,
		arg.FiatAmount,
		arg.LocalCurrency,
		arg.TargetToken,
		arg.Rate,
		arg.ExpiresAt,
	)
	var i FxQuote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuoteID,
		&i.FiatAmount,
		&i.LocalCurrency,
		&i.TargetToken,
		&i.Rate,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredFXQuotes = `-- name: DeleteExpiredFXQuotes :exec
DELETE FROM fx_quotes WHERE expires_at < NOW() AND used = false
`

func (q *Queries) DeleteExpiredFXQuotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredFXQuotes)
	return err
}

const getCaasWalletByAddress = `-- name: GetCaasWalletByAddress :one
SELECT id, user_id, caas_wallet_id, abstraction_address, is_active, created_at, blind_index FROM caas_wallets WHERE abstraction_address = $1 LIMIT 1
`

func (q *Queries) GetCaasWalletByAddress(ctx context.Context, abstractionAddress string) (CaasWallet, error) {
	row := q.db.QueryRow(ctx, getCaasWalletByAddress, abstractionAddress)
	var i CaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWalletID,
		&i.AbstractionAddress,
		&i.IsActive,
		&i.CreatedAt,
		&i.BlindIndex,
	)
	return i, err
}

const getCaasWalletByBlindIndex = `-- name: GetCaasWalletByBlindIndex :one
SELECT id, user_id, caas_wallet_id, abstraction_address, is_active, created_at, blind_index FROM caas_wallets WHERE blind_index = $1 LIMIT 1
`

func (q *Queries) GetCaasWalletByBlindIndex(ctx context.Context, blindIndex *string) (CaasWallet, error) {
	row := q.db.QueryRow(ctx, getCaasWalletByBlindIndex, blindIndex)
	var i CaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWalletID,
		&i.AbstractionAddress,
		&i.IsActive,
		&i.CreatedAt,
		&i.BlindIndex,
	)
	return i, err
}

const getCaasWalletByUserID = `-- name: GetCaasWalletByUserID :one
SELECT id, user_id, caas_wallet_id, abstraction_address, is_active, created_at, blind_index FROM caas_wallets WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetCaasWalletByUserID(ctx context.Context, userID uuid.UUID) (CaasWallet, error) {
	row := q.db.QueryRow(ctx, getCaasWalletByUserID, userID)
	var i CaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWalletID,
		&i.AbstractionAddress,
		&i.IsActive,
		&i.CreatedAt,
		&i.BlindIndex,
	)
	return i, err
}

const getCaasWithdrawalByCaasID = `-- name: GetCaasWithdrawalByCaasID :one
SELECT id, user_id, caas_withdrawal_id, phone, amount, token, payout_mobile, payout_network, idempotency_key, status, created_at, updated_at FROM caas_withdrawals WHERE caas_withdrawal_id = $1 LIMIT 1
`

func (q *Queries) GetCaasWithdrawalByCaasID(ctx context.Context, caasWithdrawalID string) (CaasWithdrawal, error) {
	row := q.db.QueryRow(ctx, getCaasWithdrawalByCaasID, caasWithdrawalID)
	var i CaasWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWithdrawalID,
		&i.Phone,
		&i.Amount,
		&i.Token,
		&i.PayoutMobile,
		&i.PayoutNetwork,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCaasWithdrawalByID = `-- name: GetCaasWithdrawalByID :one
SELECT id, user_id, caas_withdrawal_id, phone, amount, token, payout_mobile, payout_network, idempotency_key, status, created_at, updated_at FROM caas_withdrawals WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCaasWithdrawalByID(ctx context.Context, id uuid.UUID) (CaasWithdrawal, error) {
	row := q.db.QueryRow(ctx, getCaasWithdrawalByID, id)
	var i CaasWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWithdrawalID,
		&i.Phone,
		&i.Amount,
		&i.Token,
		&i.PayoutMobile,
		&i.PayoutNetwork,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCaasWithdrawalByIdempotencyKey = `-- name: GetCaasWithdrawalByIdempotencyKey :one
SELECT id, user_id, caas_withdrawal_id, phone, amount, token, payout_mobile, payout_network, idempotency_key, status, created_at, updated_at FROM caas_withdrawals WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetCaasWithdrawalByIdempotencyKey(ctx context.Context, idempotencyKey string) (CaasWithdrawal, error) {
	row := q.db.QueryRow(ctx, getCaasWithdrawalByIdempotencyKey, idempotencyKey)
	var i CaasWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWithdrawalID,
		&i.Phone,
		&i.Amount,
		&i.Token,
		&i.PayoutMobile,
		&i.PayoutNetwork,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCryptoTransactionByIdempotencyKey = `-- name: GetCryptoTransactionByIdempotencyKey :one

SELECT id, reference, sender_user_id, receiver_phone, receiver_user_id, token, amount, tx_hash, status, created_at, updated_at, quote_id, caas_transfer_id, idempotency_key, local_fiat_amount, local_currency FROM crypto_transactions WHERE idempotency_key = $1 LIMIT 1
`

// ─── crypto_transactions CaaS extras ─────────────────────────────────────────
// (CreateCryptoTransaction is defined in the existing stub; the params struct is
//
//	extended in query.sql.go to include the nullable CaaS fields below.)
func (q *Queries) GetCryptoTransactionByIdempotencyKey(ctx context.Context, idempotencyKey *string) (CryptoTransaction, error) {
	row := q.db.QueryRow(ctx, getCryptoTransactionByIdempotencyKey, idempotencyKey)
	var i CryptoTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.SenderUserID,
		&i.ReceiverPhone,
		&i.ReceiverUserID,
		&i.Token,
		&i.Amount,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuoteID,
		&i.CaasTransferID,
		&i.IdempotencyKey,
		&i.LocalFiatAmount,
		&i.LocalCurrency,
	)
	return i, err
}

const getFXQuoteByQuoteID = `-- name: GetFXQuoteByQuoteID :one
SELECT id, user_id, quote_id, fiat_amount, local_currency, target_token, rate, expires_at, used, created_at FROM fx_quotes WHERE quote_id = $1 LIMIT 1
`

func (q *Queries) GetFXQuoteByQuoteID(ctx context.Context, quoteID string) (FxQuote, error) {
	row := q.db.QueryRow(ctx, getFXQuoteByQuoteID, quoteID)
	var i FxQuote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuoteID,
		&i.FiatAmount,
		&i.LocalCurrency,
		&i.TargetToken,
		&i.Rate,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getHub2PaymentByReferenceForFunding = `-- name: GetHub2PaymentByReferenceForFunding :one
SELECT id, transaction_id, hub2_reference, payment_method, operator, phone_number, status, hub2_status, metadata, created_at, updated_at, caas_funded_at FROM hub2_payments
WHERE hub2_reference = $1 AND caas_funded_at IS NULL
LIMIT 1
`

func (q *Queries) GetHub2PaymentByReferenceForFunding(ctx context.Context, hub2Reference string) (Hub2Payment, error) {
	row := q.db.QueryRow(ctx, getHub2PaymentByReferenceForFunding, hub2Reference)
	var i Hub2Payment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Hub2Reference,
		&i.PaymentMethod,
		&i.Operator,
		&i.PhoneNumber,
		&i.Status,
		&i.Hub2Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CaasFundedAt,
	)
	return i, err
}

const listCaasWithdrawalsByUser = `-- name: ListCaasWithdrawalsByUser :many
SELECT id, user_id, caas_withdrawal_id, phone, amount, token, payout_mobile, payout_network, idempotency_key, status, created_at, updated_at FROM caas_withdrawals
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCaasWithdrawalsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListCaasWithdrawalsByUser(ctx context.Context, arg ListCaasWithdrawalsByUserParams) ([]CaasWithdrawal, error) {
	rows, err := q.db.Query(ctx, listCaasWithdrawalsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaasWithdrawal{}
	for rows.Next() {
		var i CaasWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CaasWithdrawalID,
			&i.Phone,
			&i.Amount,
			&i.Token,
			&i.PayoutMobile,
			&i.PayoutNetwork,
			&i.IdempotencyKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFXQuoteUsed = `-- name: MarkFXQuoteUsed :exec
UPDATE fx_quotes SET used = true WHERE quote_id = $1
`

func (q *Queries) MarkFXQuoteUsed(ctx context.Context, quoteID string) error {
	_, err := q.db.Exec(ctx, markFXQuoteUsed, quoteID)
	return err
}

const markHub2PaymentCaasFunded = `-- name: MarkHub2PaymentCaasFunded :exec

UPDATE hub2_payments
SET caas_funded_at = NOW()
WHERE id = $1
`

// ─── hub2_payments CaaS funding ───────────────────────────────────────────────
func (q *Queries) MarkHub2PaymentCaasFunded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markHub2PaymentCaasFunded, id)
	return err
}

const updateCaasWalletPhone = `-- name: UpdateCaasWalletPhone :exec
UPDATE caas_wallets
SET blind_index = $2
WHERE user_id = $1
`

type UpdateCaasWalletPhoneParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BlindIndex *string   `json:"blind_index"`
}

func (q *Queries) UpdateCaasWalletPhone(ctx context.Context, arg UpdateCaasWalletPhoneParams) error {
	_, err := q.db.Exec(ctx, updateCaasWalletPhone, arg.UserID, arg.BlindIndex)
	return err
}

const updateCaasWithdrawalStatus = `-- name: UpdateCaasWithdrawalStatus :one
UPDATE caas_withdrawals
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, caas_withdrawal_id, phone, amount, token, payout_mobile, payout_network, idempotency_key, status, created_at, updated_at
`

type UpdateCaasWithdrawalStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCaasWithdrawalStatus(ctx context.Context, arg UpdateCaasWithdrawalStatusParams) (CaasWithdrawal, error) {
	row := q.db.QueryRow(ctx, updateCaasWithdrawalStatus, arg.ID, arg.Status)
	var i CaasWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CaasWithdrawalID,
		&i.Phone,
		&i.Amount,
		&i.Token,
		&i.PayoutMobile,
		&i.PayoutNetwork,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCryptoTransactionCaasResult = `-- name: UpdateCryptoTransactionCaasResult :one
UPDATE crypto_transactions
SET status = $2, tx_hash = $3, caas_transfer_id = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, reference, sender_user_id, receiver_phone, receiver_user_id, token, amount, tx_hash, status, created_at, updated_at, quote_id, caas_transfer_id, idempotency_key, local_fiat_amount, local_currency
`

type UpdateCryptoTransactionCaasResultParams struct {
	ID             uuid.UUID `json:"id"`
	Status         string    `json:"status"`
	TxHash         *string   `json:"tx_hash"`
	CaasTransferID *string   `json:"caas_transfer_id"`
}

func (q *Queries) UpdateCryptoTransactionCaasResult(ctx context.Context, arg UpdateCryptoTransactionCaasResultParams) (CryptoTransaction, error) {
	row := q.db.QueryRow(ctx, updateCryptoTransactionCaasResult,
		arg.ID,
		arg.Status,
		arg.TxHash,
		arg.CaasTransferID,
	)
	var i CryptoTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.SenderUserID,
		&i.ReceiverPhone,
		&i.ReceiverUserID,
		&i.Token,
		&i.Amount,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuoteID,
		&i.CaasTransferID,
		&i.IdempotencyKey,
		&i.LocalFiatAmount,
		&i.LocalCurrency,
	)
	return i, err
}
