// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActiveVirtualCards = `-- name: CountActiveVirtualCards :one
SELECT COUNT(*) FROM virtual_cards
WHERE user_id = $1 AND status != 'closed'
`

func (q *Queries) CountActiveVirtualCards(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVirtualCards, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCardTransaction = `-- name: CreateCardTransaction :one
INSERT INTO card_transactions (
    card_id, amount, currency, merchant_name, merchant_city, merchant_country, status, provider_tx_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, card_id, amount, currency, merchant_name, merchant_city, merchant_country, status, provider_tx_id, created_at
`

type CreateCardTransactionParams struct {
	CardID          uuid.UUID `json:"card_id"`
	Amount          string    `json:"amount"`
	Currency        string    `json:"currency"`
	MerchantName    string    `json:"merchant_name"`
	MerchantCity    *string   `json:"merchant_city"`
	MerchantCountry *string   `json:"merchant_country"`
	Status          string    `json:"status"`
	ProviderTxID    *string   `json:"provider_tx_id"`
}

func (q *Queries) CreateCardTransaction(ctx context.Context, arg CreateCardTransactionParams) (CardTransaction, error) {
	row := q.db.QueryRow(ctx, createCardTransaction,
		arg.CardID,
		arg.Amount,
		arg.Currency,
		arg.MerchantName,
		arg.MerchantCity,
		arg.MerchantCountry,
		arg.Status,
		arg.ProviderTxID,
	)
	var i CardTransaction
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Amount,
		&i.Currency,
		&i.MerchantName,
		&i.MerchantCity,
		&i.MerchantCountry,
		&i.Status,
		&i.ProviderTxID,
		&i.CreatedAt,
	)
	return i, err
}

const createVirtualCard = `-- name: CreateVirtualCard :one
INSERT INTO virtual_cards (
    user_id, funding_account_id, funding_wallet_id, card_name, color_theme, card_art_id, billing_address, masked_pan, expiry, cvv_encrypted, status, provider_card_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, user_id, card_name, last_four, currency, card_network, is_active, created_at, funding_account_id, funding_wallet_id, color_theme, card_art_id, billing_address, masked_pan, expiry, cvv_encrypted, status, provider_card_id, updated_at
`

type CreateVirtualCardParams struct {
	UserID           uuid.UUID  `json:"user_id"`
	FundingAccountID *uuid.UUID `json:"funding_account_id"`
	FundingWalletID  *uuid.UUID `json:"funding_wallet_id"`
	CardName         string     `json:"card_name"`
	ColorTheme       *string    `json:"color_theme"`
	CardArtID        *string    `json:"card_art_id"`
	BillingAddress   []byte     `json:"billing_address"`
	MaskedPan        *string    `json:"masked_pan"`
	Expiry           *string    `json:"expiry"`
	CvvEncrypted     *string    `json:"cvv_encrypted"`
	Status           string     `json:"status"`
	ProviderCardID   *string    `json:"provider_card_id"`
}

func (q *Queries) CreateVirtualCard(ctx context.Context, arg CreateVirtualCardParams) (VirtualCard, error) {
	row := q.db.QueryRow(ctx, createVirtualCard,
		arg.UserID,
		arg.FundingAccountID,
		arg.FundingWalletID,
		arg.CardName,
		arg.ColorTheme,
		arg.CardArtID,
		arg.BillingAddress,
		arg.MaskedPan,
		arg.Expiry,
		arg.CvvEncrypted,
		arg.Status,
		arg.ProviderCardID,
	)
	var i VirtualCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardName,
		&i.LastFour,
		&i.Currency,
		&i.CardNetwork,
		&i.IsActive,
		&i.CreatedAt,
		&i.FundingAccountID,
		&i.FundingWalletID,
		&i.ColorTheme,
		&i.CardArtID,
		&i.BillingAddress,
		&i.MaskedPan,
		&i.Expiry,
		&i.CvvEncrypted,
		&i.Status,
		&i.ProviderCardID,
		&i.UpdatedAt,
	)
	return i, err
}

const getVirtualCardByID = `-- name: GetVirtualCardByID :one
SELECT id, user_id, card_name, last_four, currency, card_network, is_active, created_at, funding_account_id, funding_wallet_id, color_theme, card_art_id, billing_address, masked_pan, expiry, cvv_encrypted, status, provider_card_id, updated_at FROM virtual_cards
WHERE id = $1 AND user_id = $2
`

type GetVirtualCardByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetVirtualCardByID(ctx context.Context, arg GetVirtualCardByIDParams) (VirtualCard, error) {
	row := q.db.QueryRow(ctx, getVirtualCardByID, arg.ID, arg.UserID)
	var i VirtualCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardName,
		&i.LastFour,
		&i.Currency,
		&i.CardNetwork,
		&i.IsActive,
		&i.CreatedAt,
		&i.FundingAccountID,
		&i.FundingWalletID,
		&i.ColorTheme,
		&i.CardArtID,
		&i.BillingAddress,
		&i.MaskedPan,
		&i.Expiry,
		&i.CvvEncrypted,
		&i.Status,
		&i.ProviderCardID,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardTransactions = `-- name: ListCardTransactions :many
SELECT id, card_id, amount, currency, merchant_name, merchant_city, merchant_country, status, provider_tx_id, created_at FROM card_transactions
WHERE card_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListCardTransactions(ctx context.Context, cardID uuid.UUID) ([]CardTransaction, error) {
	rows, err := q.db.Query(ctx, listCardTransactions, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardTransaction{}
	for rows.Next() {
		var i CardTransaction
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Amount,
			&i.Currency,
			&i.MerchantName,
			&i.MerchantCity,
			&i.MerchantCountry,
			&i.Status,
			&i.ProviderTxID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVirtualCardsByUserID = `-- name: ListVirtualCardsByUserID :many
SELECT id, user_id, card_name, last_four, currency, card_network, is_active, created_at, funding_account_id, funding_wallet_id, color_theme, card_art_id, billing_address, masked_pan, expiry, cvv_encrypted, status, provider_card_id, updated_at FROM virtual_cards
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVirtualCardsByUserID(ctx context.Context, userID uuid.UUID) ([]VirtualCard, error) {
	rows, err := q.db.Query(ctx, listVirtualCardsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VirtualCard{}
	for rows.Next() {
		var i VirtualCard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardName,
			&i.LastFour,
			&i.Currency,
			&i.CardNetwork,
			&i.IsActive,
			&i.CreatedAt,
			&i.FundingAccountID,
			&i.FundingWalletID,
			&i.ColorTheme,
			&i.CardArtID,
			&i.BillingAddress,
			&i.MaskedPan,
			&i.Expiry,
			&i.CvvEncrypted,
			&i.Status,
			&i.ProviderCardID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVirtualCard = `-- name: UpdateVirtualCard :one
UPDATE virtual_cards
SET card_name = COALESCE($3, card_name),
    color_theme = COALESCE($4, color_theme),
    card_art_id = COALESCE($5, card_art_id),
    status = COALESCE($6, status),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, card_name, last_four, currency, card_network, is_active, created_at, funding_account_id, funding_wallet_id, color_theme, card_art_id, billing_address, masked_pan, expiry, cvv_encrypted, status, provider_card_id, updated_at
`

type UpdateVirtualCardParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	CardName   *string   `json:"card_name"`
	ColorTheme *string   `json:"color_theme"`
	CardArtID  *string   `json:"card_art_id"`
	Status     *string   `json:"status"`
}

func (q *Queries) UpdateVirtualCard(ctx context.Context, arg UpdateVirtualCardParams) (VirtualCard, error) {
	row := q.db.QueryRow(ctx, updateVirtualCard,
		arg.ID,
		arg.UserID,
		arg.CardName,
		arg.ColorTheme,
		arg.CardArtID,
		arg.Status,
	)
	var i VirtualCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardName,
		&i.LastFour,
		&i.Currency,
		&i.CardNetwork,
		&i.IsActive,
		&i.CreatedAt,
		&i.FundingAccountID,
		&i.FundingWalletID,
		&i.ColorTheme,
		&i.CardArtID,
		&i.BillingAddress,
		&i.MaskedPan,
		&i.Expiry,
		&i.CvvEncrypted,
		&i.Status,
		&i.ProviderCardID,
		&i.UpdatedAt,
	)
	return i, err
}
