// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crypto.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCryptoTransaction = `-- name: CreateCryptoTransaction :one
INSERT INTO crypto_transactions
    (reference, sender_user_id, receiver_phone, receiver_user_id, token, amount,
     tx_hash, status, quote_id, caas_transfer_id, idempotency_key, local_fiat_amount, local_currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, reference, sender_user_id, receiver_phone, receiver_user_id, token, amount, tx_hash, status, created_at, updated_at, quote_id, caas_transfer_id, idempotency_key, local_fiat_amount, local_currency
`

type CreateCryptoTransactionParams struct {
	Reference       string     `json:"reference"`
	SenderUserID    uuid.UUID  `json:"sender_user_id"`
	ReceiverPhone   string     `json:"receiver_phone"`
	ReceiverUserID  *uuid.UUID `json:"receiver_user_id"`
	Token           string     `json:"token"`
	Amount          string     `json:"amount"`
	TxHash          *string    `json:"tx_hash"`
	Status          string     `json:"status"`
	QuoteID         *string    `json:"quote_id"`
	CaasTransferID  *string    `json:"caas_transfer_id"`
	IdempotencyKey  *string    `json:"idempotency_key"`
	LocalFiatAmount *string    `json:"local_fiat_amount"`
	LocalCurrency   *string    `json:"local_currency"`
}

func (q *Queries) CreateCryptoTransaction(ctx context.Context, arg CreateCryptoTransactionParams) (CryptoTransaction, error) {
	row := q.db.QueryRow(ctx, createCryptoTransaction,
		arg.Reference,
		arg.SenderUserID,
		arg.ReceiverPhone,
		arg.ReceiverUserID,
		arg.Token,
		arg.Amount,
		arg.TxHash,
		arg.Status,
		arg.QuoteID,
		arg.CaasTransferID,
		arg.IdempotencyKey,
		arg.LocalFiatAmount,
		arg.LocalCurrency,
	)
	var i CryptoTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.SenderUserID,
		&i.ReceiverPhone,
		&i.ReceiverUserID,
		&i.Token,
		&i.Amount,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuoteID,
		&i.CaasTransferID,
		&i.IdempotencyKey,
		&i.LocalFiatAmount,
		&i.LocalCurrency,
	)
	return i, err
}

const getCryptoTransactionByID = `-- name: GetCryptoTransactionByID :one
SELECT id, reference, sender_user_id, receiver_phone, receiver_user_id, token, amount, tx_hash, status, created_at, updated_at, quote_id, caas_transfer_id, idempotency_key, local_fiat_amount, local_currency FROM crypto_transactions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCryptoTransactionByID(ctx context.Context, id uuid.UUID) (CryptoTransaction, error) {
	row := q.db.QueryRow(ctx, getCryptoTransactionByID, id)
	var i CryptoTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.SenderUserID,
		&i.ReceiverPhone,
		&i.ReceiverUserID,
		&i.Token,
		&i.Amount,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuoteID,
		&i.CaasTransferID,
		&i.IdempotencyKey,
		&i.LocalFiatAmount,
		&i.LocalCurrency,
	)
	return i, err
}

const getCryptoTransactionByReference = `-- name: GetCryptoTransactionByReference :one
SELECT id, reference, sender_user_id, receiver_phone, receiver_user_id, token, amount, tx_hash, status, created_at, updated_at, quote_id, caas_transfer_id, idempotency_key, local_fiat_amount, local_currency FROM crypto_transactions WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetCryptoTransactionByReference(ctx context.Context, reference string) (CryptoTransaction, error) {
	row := q.db.QueryRow(ctx, getCryptoTransactionByReference, reference)
	var i CryptoTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.SenderUserID,
		&i.ReceiverPhone,
		&i.ReceiverUserID,
		&i.Token,
		&i.Amount,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuoteID,
		&i.CaasTransferID,
		&i.IdempotencyKey,
		&i.LocalFiatAmount,
		&i.LocalCurrency,
	)
	return i, err
}

const listCryptoTransactionsByUser = `-- name: ListCryptoTransactionsByUser :many
SELECT id, reference, sender_user_id, receiver_phone, receiver_user_id, token, amount, tx_hash, status, created_at, updated_at, quote_id, caas_transfer_id, idempotency_key, local_fiat_amount, local_currency FROM crypto_transactions
WHERE sender_user_id = $1 OR receiver_user_id = $4
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCryptoTransactionsByUserParams struct {
	SenderUserID   uuid.UUID  `json:"sender_user_id"`
	Limit          int32      `json:"limit"`
	Offset         int32      `json:"offset"`
	ReceiverUserID *uuid.UUID `json:"receiver_user_id"`
}

func (q *Queries) ListCryptoTransactionsByUser(ctx context.Context, arg ListCryptoTransactionsByUserParams) ([]CryptoTransaction, error) {
	rows, err := q.db.Query(ctx, listCryptoTransactionsByUser,
		arg.SenderUserID,
		arg.Limit,
		arg.Offset,
		arg.ReceiverUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CryptoTransaction{}
	for rows.Next() {
		var i CryptoTransaction
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.SenderUserID,
			&i.ReceiverPhone,
			&i.ReceiverUserID,
			&i.Token,
			&i.Amount,
			&i.TxHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuoteID,
			&i.CaasTransferID,
			&i.IdempotencyKey,
			&i.LocalFiatAmount,
			&i.LocalCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCryptoTransactionStatus = `-- name: UpdateCryptoTransactionStatus :one
UPDATE crypto_transactions
SET status = $2, tx_hash = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, reference, sender_user_id, receiver_phone, receiver_user_id, token, amount, tx_hash, status, created_at, updated_at, quote_id, caas_transfer_id, idempotency_key, local_fiat_amount, local_currency
`

type UpdateCryptoTransactionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	TxHash *string   `json:"tx_hash"`
}

func (q *Queries) UpdateCryptoTransactionStatus(ctx context.Context, arg UpdateCryptoTransactionStatusParams) (CryptoTransaction, error) {
	row := q.db.QueryRow(ctx, updateCryptoTransactionStatus, arg.ID, arg.Status, arg.TxHash)
	var i CryptoTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.SenderUserID,
		&i.ReceiverPhone,
		&i.ReceiverUserID,
		&i.Token,
		&i.Amount,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuoteID,
		&i.CaasTransferID,
		&i.IdempotencyKey,
		&i.LocalFiatAmount,
		&i.LocalCurrency,
	)
	return i, err
}
