// Code generated by sqlc. DO NOT EDIT.
// Run `make sqlc` to regenerate after changing queries or schema.
package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// DBTX is the minimal interface satisfied by *pgxpool.Pool and *pgx.Conn.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

// New returns a Queries bound to the provided connection pool.
func New(pool *pgxpool.Pool) *Queries {
	return &Queries{db: pool}
}

// Queries holds the database connection used by all generated query methods.
type Queries struct {
	db DBTX
}

// WithTx returns a new Queries bound to a transaction.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
