// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStaffInDepartment = `-- name: CountStaffInDepartment :one
SELECT count(*) FROM admin_staff WHERE department_id = $1
`

func (q *Queries) CountStaffInDepartment(ctx context.Context, departmentID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStaffInDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO admin_departments (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (AdminDepartment, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Name, arg.Description)
	var i AdminDepartment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :execrows
DELETE FROM admin_departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDepartment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, name, description, created_at, updated_at FROM admin_departments WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id uuid.UUID) (AdminDepartment, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i AdminDepartment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT d.id, d.name, d.description, d.created_at, d.updated_at, (SELECT count(*) FROM admin_staff s WHERE s.department_id = d.id)::bigint AS staff_count
FROM admin_departments d
ORDER BY d.name
`

type ListDepartmentsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	StaffCount  int64     `json:"staff_count"`
}

func (q *Queries) ListDepartments(ctx context.Context) ([]ListDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepartmentsRow{}
	for rows.Next() {
		var i ListDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StaffCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE admin_departments
SET name        = coalesce($1, name),
    description = coalesce($2, description),
    updated_at  = now()
WHERE id = $3
RETURNING id, name, description, created_at, updated_at
`

type UpdateDepartmentParams struct {
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (AdminDepartment, error) {
	row := q.db.QueryRow(ctx, updateDepartment, arg.Name, arg.Description, arg.ID)
	var i AdminDepartment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
