// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_otps.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailOTP = `-- name: CreateEmailOTP :one
INSERT INTO email_otps (email, code, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, code, purpose, expires_at, used, created_at
`

type CreateEmailOTPParams struct {
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailOTP(ctx context.Context, arg CreateEmailOTPParams) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, createEmailOTP,
		arg.Email,
		arg.Code,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.Purpose,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const createMetamapVerification = `-- name: CreateMetamapVerification :one

INSERT INTO metamap_verifications
    (user_id, applicant_id, flow_id, identity_access)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, applicant_id, flow_id, identity_access, status, result_data, created_at, updated_at
`

type CreateMetamapVerificationParams struct {
	UserID         uuid.UUID `json:"user_id"`
	ApplicantID    string    `json:"applicant_id"`
	FlowID         string    `json:"flow_id"`
	IdentityAccess string    `json:"identity_access"`
}

// MetaMap verification queries
func (q *Queries) CreateMetamapVerification(ctx context.Context, arg CreateMetamapVerificationParams) (MetamapVerification, error) {
	row := q.db.QueryRow(ctx, createMetamapVerification,
		arg.UserID,
		arg.ApplicantID,
		arg.FlowID,
		arg.IdentityAccess,
	)
	var i MetamapVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantID,
		&i.FlowID,
		&i.IdentityAccess,
		&i.Status,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredEmailOTPs = `-- name: DeleteExpiredEmailOTPs :exec
DELETE FROM email_otps WHERE expires_at < NOW() OR used = true
`

func (q *Queries) DeleteExpiredEmailOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailOTPs)
	return err
}

const getMetamapVerificationByApplicantID = `-- name: GetMetamapVerificationByApplicantID :one
SELECT id, user_id, applicant_id, flow_id, identity_access, status, result_data, created_at, updated_at FROM metamap_verifications WHERE applicant_id = $1 LIMIT 1
`

func (q *Queries) GetMetamapVerificationByApplicantID(ctx context.Context, applicantID string) (MetamapVerification, error) {
	row := q.db.QueryRow(ctx, getMetamapVerificationByApplicantID, applicantID)
	var i MetamapVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantID,
		&i.FlowID,
		&i.IdentityAccess,
		&i.Status,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMetamapVerificationByUserID = `-- name: GetMetamapVerificationByUserID :one
SELECT id, user_id, applicant_id, flow_id, identity_access, status, result_data, created_at, updated_at FROM metamap_verifications WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetMetamapVerificationByUserID(ctx context.Context, userID uuid.UUID) (MetamapVerification, error) {
	row := q.db.QueryRow(ctx, getMetamapVerificationByUserID, userID)
	var i MetamapVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantID,
		&i.FlowID,
		&i.IdentityAccess,
		&i.Status,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidEmailOTP = `-- name: GetValidEmailOTP :one
SELECT id, email, code, purpose, expires_at, used, created_at FROM email_otps
WHERE email      = $1
  AND code       = $2
  AND purpose    = $3
  AND expires_at > NOW()
  AND used       = false
LIMIT 1
`

type GetValidEmailOTPParams struct {
	Email   string `json:"email"`
	Code    string `json:"code"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetValidEmailOTP(ctx context.Context, arg GetValidEmailOTPParams) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, getValidEmailOTP, arg.Email, arg.Code, arg.Purpose)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.Purpose,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailOTPUsed = `-- name: MarkEmailOTPUsed :exec
UPDATE email_otps SET used = true WHERE id = $1
`

func (q *Queries) MarkEmailOTPUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailOTPUsed, id)
	return err
}

const updateMetamapVerificationStatus = `-- name: UpdateMetamapVerificationStatus :one
UPDATE metamap_verifications
SET status = $2, result_data = $3, updated_at = NOW()
WHERE applicant_id = $1
RETURNING id, user_id, applicant_id, flow_id, identity_access, status, result_data, created_at, updated_at
`

type UpdateMetamapVerificationStatusParams struct {
	ApplicantID string `json:"applicant_id"`
	Status      string `json:"status"`
	ResultData  []byte `json:"result_data"`
}

func (q *Queries) UpdateMetamapVerificationStatus(ctx context.Context, arg UpdateMetamapVerificationStatusParams) (MetamapVerification, error) {
	row := q.db.QueryRow(ctx, updateMetamapVerificationStatus, arg.ApplicantID, arg.Status, arg.ResultData)
	var i MetamapVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantID,
		&i.FlowID,
		&i.IdentityAccess,
		&i.Status,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
