// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hub2.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createHub2Payment = `-- name: CreateHub2Payment :one
INSERT INTO hub2_payments (transaction_id, hub2_reference, payment_method, operator, phone_number, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, hub2_reference, payment_method, operator, phone_number, status, hub2_status, metadata, created_at, updated_at, caas_funded_at
`

type CreateHub2PaymentParams struct {
	TransactionID *uuid.UUID `json:"transaction_id"`
	Hub2Reference string     `json:"hub2_reference"`
	PaymentMethod string     `json:"payment_method"`
	Operator      *string    `json:"operator"`
	PhoneNumber   *string    `json:"phone_number"`
	Metadata      []byte     `json:"metadata"`
}

func (q *Queries) CreateHub2Payment(ctx context.Context, arg CreateHub2PaymentParams) (Hub2Payment, error) {
	row := q.db.QueryRow(ctx, createHub2Payment,
		arg.TransactionID,
		arg.Hub2Reference,
		arg.PaymentMethod,
		arg.Operator,
		arg.PhoneNumber,
		arg.Metadata,
	)
	var i Hub2Payment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Hub2Reference,
		&i.PaymentMethod,
		&i.Operator,
		&i.PhoneNumber,
		&i.Status,
		&i.Hub2Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CaasFundedAt,
	)
	return i, err
}

const getHub2PaymentByReference = `-- name: GetHub2PaymentByReference :one
SELECT id, transaction_id, hub2_reference, payment_method, operator, phone_number, status, hub2_status, metadata, created_at, updated_at, caas_funded_at FROM hub2_payments WHERE hub2_reference = $1 LIMIT 1
`

func (q *Queries) GetHub2PaymentByReference(ctx context.Context, hub2Reference string) (Hub2Payment, error) {
	row := q.db.QueryRow(ctx, getHub2PaymentByReference, hub2Reference)
	var i Hub2Payment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Hub2Reference,
		&i.PaymentMethod,
		&i.Operator,
		&i.PhoneNumber,
		&i.Status,
		&i.Hub2Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CaasFundedAt,
	)
	return i, err
}

const updateHub2PaymentStatus = `-- name: UpdateHub2PaymentStatus :one
UPDATE hub2_payments
SET status = $2, hub2_status = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, transaction_id, hub2_reference, payment_method, operator, phone_number, status, hub2_status, metadata, created_at, updated_at, caas_funded_at
`

type UpdateHub2PaymentStatusParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	Hub2Status *string   `json:"hub2_status"`
}

func (q *Queries) UpdateHub2PaymentStatus(ctx context.Context, arg UpdateHub2PaymentStatusParams) (Hub2Payment, error) {
	row := q.db.QueryRow(ctx, updateHub2PaymentStatus, arg.ID, arg.Status, arg.Hub2Status)
	var i Hub2Payment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Hub2Reference,
		&i.PaymentMethod,
		&i.Operator,
		&i.PhoneNumber,
		&i.Status,
		&i.Hub2Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CaasFundedAt,
	)
	return i, err
}
