// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights_extra.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getBalanceTrend = `-- name: GetBalanceTrend :many
SELECT
    date_trunc('day', transactions.created_at)::timestamptz AS date,
    sum(transactions.amount)::float8 AS fiat_usd,
    0::float8 AS crypto_usd
FROM transactions
WHERE transactions.account_id IN (SELECT id FROM accounts WHERE user_id = $1)
  AND transactions.created_at >= $2
GROUP BY 1
ORDER BY 1
`

type GetBalanceTrendParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetBalanceTrendRow struct {
	Date      time.Time `json:"date"`
	FiatUSD   float64   `json:"fiat_usd"`
	CryptoUSD float64   `json:"crypto_usd"`
}

// Daily net fiat flow per day across all the user's fiat accounts.
// The service layer accumulates these into a balance trend and fills in
// crypto from live balances.
func (q *Queries) GetBalanceTrend(ctx context.Context, arg GetBalanceTrendParams) ([]GetBalanceTrendRow, error) {
	rows, err := q.db.Query(ctx, getBalanceTrend, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBalanceTrendRow{}
	for rows.Next() {
		var i GetBalanceTrendRow
		if err := rows.Scan(&i.Date, &i.FiatUSD, &i.CryptoUSD); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyFlow = `-- name: GetMonthlyFlow :many
SELECT
    to_char(date_trunc('month', transactions.created_at), 'Mon')::text AS month,
    extract(YEAR FROM date_trunc('month', transactions.created_at))::int AS year,
    sum(CASE WHEN transactions.amount > 0 THEN transactions.amount ELSE 0 END)::float8 AS income,
    abs(sum(CASE WHEN transactions.amount < 0 THEN transactions.amount ELSE 0 END))::float8 AS spending
FROM transactions
WHERE transactions.account_id IN (SELECT id FROM accounts WHERE user_id = $1)
  AND transactions.created_at >= now() - make_interval(months => $2::int)
GROUP BY date_trunc('month', transactions.created_at)
ORDER BY date_trunc('month', transactions.created_at)
`

type GetMonthlyFlowParams struct {
	UserID uuid.UUID `json:"user_id"`
	Months int32     `json:"months"`
}

type GetMonthlyFlowRow struct {
	Month    string  `json:"month"`
	Year     int32   `json:"year"`
	Income   float64 `json:"income"`
	Spending float64 `json:"spending"`
}

func (q *Queries) GetMonthlyFlow(ctx context.Context, arg GetMonthlyFlowParams) ([]GetMonthlyFlowRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyFlow, arg.UserID, arg.Months)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyFlowRow{}
	for rows.Next() {
		var i GetMonthlyFlowRow
		if err := rows.Scan(
			&i.Month,
			&i.Year,
			&i.Income,
			&i.Spending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpendingByType = `-- name: GetSpendingByType :many
SELECT
    transactions.type::text AS tx_type,
    'fiat'::text AS source,
    abs(sum(transactions.amount))::float8 AS total
FROM transactions
WHERE transactions.account_id IN (SELECT id FROM accounts WHERE user_id = $1)
  AND transactions.amount < 0
  AND transactions.created_at >= $2
GROUP BY transactions.type
ORDER BY total DESC
`

type GetSpendingByTypeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetSpendingByTypeRow struct {
	TxType string  `json:"tx_type"`
	Source string  `json:"source"`
	Total  float64 `json:"total"`
}

func (q *Queries) GetSpendingByType(ctx context.Context, arg GetSpendingByTypeParams) ([]GetSpendingByTypeRow, error) {
	rows, err := q.db.Query(ctx, getSpendingByType, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpendingByTypeRow{}
	for rows.Next() {
		var i GetSpendingByTypeRow
		if err := rows.Scan(&i.TxType, &i.Source, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
