// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createKYCDocument = `-- name: CreateKYCDocument :one
INSERT INTO kyc_documents (user_id, doc_type, doc_url)
VALUES ($1, $2, $3)
RETURNING id, user_id, doc_type, doc_url, status, rejection_reason, created_at, updated_at
`

type CreateKYCDocumentParams struct {
	UserID  uuid.UUID `json:"user_id"`
	DocType string    `json:"doc_type"`
	DocURL  string    `json:"doc_url"`
}

func (q *Queries) CreateKYCDocument(ctx context.Context, arg CreateKYCDocumentParams) (KycDocument, error) {
	row := q.db.QueryRow(ctx, createKYCDocument, arg.UserID, arg.DocType, arg.DocURL)
	var i KycDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocType,
		&i.DocURL,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKYCDocumentsByUserID = `-- name: GetKYCDocumentsByUserID :many
SELECT id, user_id, doc_type, doc_url, status, rejection_reason, created_at, updated_at FROM kyc_documents
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetKYCDocumentsByUserID(ctx context.Context, userID uuid.UUID) ([]KycDocument, error) {
	rows, err := q.db.Query(ctx, getKYCDocumentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KycDocument{}
	for rows.Next() {
		var i KycDocument
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocType,
			&i.DocURL,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKYCDocumentStatus = `-- name: UpdateKYCDocumentStatus :one
UPDATE kyc_documents
SET status = $2, rejection_reason = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, doc_type, doc_url, status, rejection_reason, created_at, updated_at
`

type UpdateKYCDocumentStatusParams struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	RejectionReason *string   `json:"rejection_reason"`
}

func (q *Queries) UpdateKYCDocumentStatus(ctx context.Context, arg UpdateKYCDocumentStatusParams) (KycDocument, error) {
	row := q.db.QueryRow(ctx, updateKYCDocumentStatus, arg.ID, arg.Status, arg.RejectionReason)
	var i KycDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocType,
		&i.DocURL,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
