// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc_intake.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getKYCIntake = `-- name: GetKYCIntake :one
SELECT user_id, account_type, legal_first_name, legal_last_name, date_of_birth, nationality, bvn, address_line1, address_line2, city, state, postal_code, country, occupation, source_of_funds, purpose_of_account, status, submitted_at, created_at, updated_at, is_importer, counterparties, contact_email, contact_phone, saved_values FROM kyc_intake WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetKYCIntake(ctx context.Context, userID uuid.UUID) (KycIntake, error) {
	row := q.db.QueryRow(ctx, getKYCIntake, userID)
	var i KycIntake
	err := row.Scan(
		&i.UserID,
		&i.AccountType,
		&i.LegalFirstName,
		&i.LegalLastName,
		&i.DateOfBirth,
		&i.Nationality,
		&i.Bvn,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Occupation,
		&i.SourceOfFunds,
		&i.PurposeOfAccount,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsImporter,
		&i.Counterparties,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.SavedValues,
	)
	return i, err
}

const saveKYCIntakeDraft = `-- name: SaveKYCIntakeDraft :one
INSERT INTO kyc_intake (user_id, account_type, saved_values, status, updated_at)
VALUES ($1, $2, $3, 'draft', now())
ON CONFLICT (user_id) DO UPDATE SET
    account_type = EXCLUDED.account_type,
    saved_values = COALESCE(kyc_intake.saved_values, '{}'::jsonb) || EXCLUDED.saved_values,
    status       = CASE WHEN kyc_intake.status = 'submitted' THEN 'submitted' ELSE 'draft' END,
    updated_at   = now()
RETURNING user_id, account_type, legal_first_name, legal_last_name, date_of_birth, nationality, bvn, address_line1, address_line2, city, state, postal_code, country, occupation, source_of_funds, purpose_of_account, status, submitted_at, created_at, updated_at, is_importer, counterparties, contact_email, contact_phone, saved_values
`

type SaveKYCIntakeDraftParams struct {
	UserID      uuid.UUID `json:"user_id"`
	AccountType string    `json:"account_type"`
	SavedValues []byte    `json:"saved_values"`
}

// Persist partial progress (no required-field validation). Merges the supplied
// values into any existing draft (last-write-wins per key) and never downgrades
// a submitted intake back to draft.
func (q *Queries) SaveKYCIntakeDraft(ctx context.Context, arg SaveKYCIntakeDraftParams) (KycIntake, error) {
	row := q.db.QueryRow(ctx, saveKYCIntakeDraft, arg.UserID, arg.AccountType, arg.SavedValues)
	var i KycIntake
	err := row.Scan(
		&i.UserID,
		&i.AccountType,
		&i.LegalFirstName,
		&i.LegalLastName,
		&i.DateOfBirth,
		&i.Nationality,
		&i.Bvn,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Occupation,
		&i.SourceOfFunds,
		&i.PurposeOfAccount,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsImporter,
		&i.Counterparties,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.SavedValues,
	)
	return i, err
}

const upsertKYCIntake = `-- name: UpsertKYCIntake :one
INSERT INTO kyc_intake (
    user_id, account_type,
    legal_first_name, legal_last_name, date_of_birth, nationality, bvn,
    address_line1, address_line2, city, state, postal_code, country,
    occupation, source_of_funds, purpose_of_account,
    is_importer, counterparties, contact_email, contact_phone,
    saved_values, status, submitted_at, updated_at
) VALUES (
    $1, $2,
    $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19, $20,
    $21, 'submitted', now(), now()
)
ON CONFLICT (user_id) DO UPDATE SET
    account_type       = EXCLUDED.account_type,
    legal_first_name   = EXCLUDED.legal_first_name,
    legal_last_name    = EXCLUDED.legal_last_name,
    date_of_birth      = EXCLUDED.date_of_birth,
    nationality        = EXCLUDED.nationality,
    bvn                = EXCLUDED.bvn,
    address_line1      = EXCLUDED.address_line1,
    address_line2      = EXCLUDED.address_line2,
    city               = EXCLUDED.city,
    state              = EXCLUDED.state,
    postal_code        = EXCLUDED.postal_code,
    country            = EXCLUDED.country,
    occupation         = EXCLUDED.occupation,
    source_of_funds    = EXCLUDED.source_of_funds,
    purpose_of_account = EXCLUDED.purpose_of_account,
    is_importer        = EXCLUDED.is_importer,
    counterparties     = EXCLUDED.counterparties,
    contact_email      = EXCLUDED.contact_email,
    contact_phone      = EXCLUDED.contact_phone,
    saved_values       = EXCLUDED.saved_values,
    status             = 'submitted',
    submitted_at       = now(),
    updated_at         = now()
RETURNING user_id, account_type, legal_first_name, legal_last_name, date_of_birth, nationality, bvn, address_line1, address_line2, city, state, postal_code, country, occupation, source_of_funds, purpose_of_account, status, submitted_at, created_at, updated_at, is_importer, counterparties, contact_email, contact_phone, saved_values
`

type UpsertKYCIntakeParams struct {
	UserID           uuid.UUID `json:"user_id"`
	AccountType      string    `json:"account_type"`
	LegalFirstName   *string   `json:"legal_first_name"`
	LegalLastName    *string   `json:"legal_last_name"`
	DateOfBirth      *string   `json:"date_of_birth"`
	Nationality      *string   `json:"nationality"`
	Bvn              *string   `json:"bvn"`
	AddressLine1     *string   `json:"address_line1"`
	AddressLine2     *string   `json:"address_line2"`
	City             *string   `json:"city"`
	State            *string   `json:"state"`
	PostalCode       *string   `json:"postal_code"`
	Country          *string   `json:"country"`
	Occupation       *string   `json:"occupation"`
	SourceOfFunds    *string   `json:"source_of_funds"`
	PurposeOfAccount *string   `json:"purpose_of_account"`
	IsImporter       *bool     `json:"is_importer"`
	Counterparties   []byte    `json:"counterparties"`
	ContactEmail     *string   `json:"contact_email"`
	ContactPhone     *string   `json:"contact_phone"`
	SavedValues      []byte    `json:"saved_values"`
}

func (q *Queries) UpsertKYCIntake(ctx context.Context, arg UpsertKYCIntakeParams) (KycIntake, error) {
	row := q.db.QueryRow(ctx, upsertKYCIntake,
		arg.UserID,
		arg.AccountType,
		arg.LegalFirstName,
		arg.LegalLastName,
		arg.DateOfBirth,
		arg.Nationality,
		arg.Bvn,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Occupation,
		arg.SourceOfFunds,
		arg.PurposeOfAccount,
		arg.IsImporter,
		arg.Counterparties,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.SavedValues,
	)
	var i KycIntake
	err := row.Scan(
		&i.UserID,
		&i.AccountType,
		&i.LegalFirstName,
		&i.LegalLastName,
		&i.DateOfBirth,
		&i.Nationality,
		&i.Bvn,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Occupation,
		&i.SourceOfFunds,
		&i.PurposeOfAccount,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsImporter,
		&i.Counterparties,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.SavedValues,
	)
	return i, err
}
