// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc_identity.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getKYCIdentity = `-- name: GetKYCIdentity :one
SELECT user_id, status, applicant_id, review_answer, reject_labels, reject_type, moderation_comment, started_at, updated_at FROM kyc_identity WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetKYCIdentity(ctx context.Context, userID uuid.UUID) (KycIdentity, error) {
	row := q.db.QueryRow(ctx, getKYCIdentity, userID)
	var i KycIdentity
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.ApplicantID,
		&i.ReviewAnswer,
		&i.RejectLabels,
		&i.RejectType,
		&i.ModerationComment,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markKYCIdentityStarted = `-- name: MarkKYCIdentityStarted :exec
INSERT INTO kyc_identity (user_id, status, started_at, updated_at)
VALUES ($1, 'in_progress', now(), now())
ON CONFLICT (user_id) DO UPDATE SET
    status     = CASE WHEN kyc_identity.status IN ('not_started') THEN 'in_progress' ELSE kyc_identity.status END,
    started_at = COALESCE(kyc_identity.started_at, now()),
    updated_at = now()
`

// Called on POST /kyc/init. Sets in_progress the first time; never regresses a
// terminal/in-review state back to in_progress.
func (q *Queries) MarkKYCIdentityStarted(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markKYCIdentityStarted, userID)
	return err
}

const upsertKYCIdentityFromWebhook = `-- name: UpsertKYCIdentityFromWebhook :exec
INSERT INTO kyc_identity (user_id, status, applicant_id, review_answer, reject_labels, reject_type, moderation_comment, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (user_id) DO UPDATE SET
    status             = EXCLUDED.status,
    applicant_id       = COALESCE(EXCLUDED.applicant_id, kyc_identity.applicant_id),
    review_answer      = COALESCE(EXCLUDED.review_answer, kyc_identity.review_answer),
    reject_labels      = COALESCE(EXCLUDED.reject_labels, kyc_identity.reject_labels),
    reject_type        = COALESCE(EXCLUDED.reject_type, kyc_identity.reject_type),
    moderation_comment = COALESCE(EXCLUDED.moderation_comment, kyc_identity.moderation_comment),
    updated_at         = now()
`

type UpsertKYCIdentityFromWebhookParams struct {
	UserID            uuid.UUID `json:"user_id"`
	Status            string    `json:"status"`
	ApplicantID       *string   `json:"applicant_id"`
	ReviewAnswer      *string   `json:"review_answer"`
	RejectLabels      []byte    `json:"reject_labels"`
	RejectType        *string   `json:"reject_type"`
	ModerationComment *string   `json:"moderation_comment"`
}

func (q *Queries) UpsertKYCIdentityFromWebhook(ctx context.Context, arg UpsertKYCIdentityFromWebhookParams) error {
	_, err := q.db.Exec(ctx, upsertKYCIdentityFromWebhook,
		arg.UserID,
		arg.Status,
		arg.ApplicantID,
		arg.ReviewAnswer,
		arg.RejectLabels,
		arg.RejectType,
		arg.ModerationComment,
	)
	return err
}
