// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc_hybrid.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const setKycManualOverride = `-- name: SetKycManualOverride :exec
UPDATE users SET kyc_manual_override = $2, updated_at = now() WHERE id = $1
`

type SetKycManualOverrideParams struct {
	ID                uuid.UUID `json:"id"`
	KycManualOverride bool      `json:"kyc_manual_override"`
}

// Flags (or clears) admin manual control over a user's KYC decision.
func (q *Queries) SetKycManualOverride(ctx context.Context, arg SetKycManualOverrideParams) error {
	_, err := q.db.Exec(ctx, setKycManualOverride, arg.ID, arg.KycManualOverride)
	return err
}

const setKycProviderStatus = `-- name: SetKycProviderStatus :exec
UPDATE users SET kyc_provider_status = $2, updated_at = now() WHERE id = $1
`

type SetKycProviderStatusParams struct {
	ID                uuid.UUID `json:"id"`
	KycProviderStatus *string   `json:"kyc_provider_status"`
}

// Records the KYC provider's latest automated decision (does not touch the
// final kyc_status).
func (q *Queries) SetKycProviderStatus(ctx context.Context, arg SetKycProviderStatusParams) error {
	_, err := q.db.Exec(ctx, setKycProviderStatus, arg.ID, arg.KycProviderStatus)
	return err
}
