// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manual_momo.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeManualWithdrawal = `-- name: CompleteManualWithdrawal :one
UPDATE manual_withdrawals
SET status = 'completed', charge = $2, payout_amount = $3, admin_note = $4,
    reviewed_by = $5, reviewed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, account_id, provider, currency, amount, charge, payout_amount, recipient_phone, recipient_name, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at
`

type CompleteManualWithdrawalParams struct {
	ID           uuid.UUID  `json:"id"`
	Charge       *string    `json:"charge"`
	PayoutAmount *string    `json:"payout_amount"`
	AdminNote    *string    `json:"admin_note"`
	ReviewedBy   *uuid.UUID `json:"reviewed_by"`
}

func (q *Queries) CompleteManualWithdrawal(ctx context.Context, arg CompleteManualWithdrawalParams) (ManualWithdrawal, error) {
	row := q.db.QueryRow(ctx, completeManualWithdrawal,
		arg.ID,
		arg.Charge,
		arg.PayoutAmount,
		arg.AdminNote,
		arg.ReviewedBy,
	)
	var i ManualWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Provider,
		&i.Currency,
		&i.Amount,
		&i.Charge,
		&i.PayoutAmount,
		&i.RecipientPhone,
		&i.RecipientName,
		&i.Note,
		&i.Status,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmManualDeposit = `-- name: ConfirmManualDeposit :one
UPDATE manual_deposits
SET status = 'confirmed', credited_amount = $2, charge = $3, admin_note = $4,
    reviewed_by = $5, reviewed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, account_id, momo_account_id, provider, currency, claimed_amount, credited_amount, charge, sender_phone, sender_name, reference, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at
`

type ConfirmManualDepositParams struct {
	ID             uuid.UUID  `json:"id"`
	CreditedAmount *string    `json:"credited_amount"`
	Charge         *string    `json:"charge"`
	AdminNote      *string    `json:"admin_note"`
	ReviewedBy     *uuid.UUID `json:"reviewed_by"`
}

func (q *Queries) ConfirmManualDeposit(ctx context.Context, arg ConfirmManualDepositParams) (ManualDeposit, error) {
	row := q.db.QueryRow(ctx, confirmManualDeposit,
		arg.ID,
		arg.CreditedAmount,
		arg.Charge,
		arg.AdminNote,
		arg.ReviewedBy,
	)
	var i ManualDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.MomoAccountID,
		&i.Provider,
		&i.Currency,
		&i.ClaimedAmount,
		&i.CreditedAmount,
		&i.Charge,
		&i.SenderPhone,
		&i.SenderName,
		&i.Reference,
		&i.Note,
		&i.Status,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManualDeposit = `-- name: CreateManualDeposit :one

INSERT INTO manual_deposits
    (user_id, account_id, momo_account_id, provider, currency, claimed_amount,
     sender_phone, sender_name, reference, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, account_id, momo_account_id, provider, currency, claimed_amount, credited_amount, charge, sender_phone, sender_name, reference, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at
`

type CreateManualDepositParams struct {
	UserID        uuid.UUID  `json:"user_id"`
	AccountID     uuid.UUID  `json:"account_id"`
	MomoAccountID *uuid.UUID `json:"momo_account_id"`
	Provider      string     `json:"provider"`
	Currency      string     `json:"currency"`
	ClaimedAmount string     `json:"claimed_amount"`
	SenderPhone   *string    `json:"sender_phone"`
	SenderName    *string    `json:"sender_name"`
	Reference     *string    `json:"reference"`
	Note          *string    `json:"note"`
}

// ─── Manual deposits (customer top-up claims) ────────────────────────────────
func (q *Queries) CreateManualDeposit(ctx context.Context, arg CreateManualDepositParams) (ManualDeposit, error) {
	row := q.db.QueryRow(ctx, createManualDeposit,
		arg.UserID,
		arg.AccountID,
		arg.MomoAccountID,
		arg.Provider,
		arg.Currency,
		arg.ClaimedAmount,
		arg.SenderPhone,
		arg.SenderName,
		arg.Reference,
		arg.Note,
	)
	var i ManualDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.MomoAccountID,
		&i.Provider,
		&i.Currency,
		&i.ClaimedAmount,
		&i.CreditedAmount,
		&i.Charge,
		&i.SenderPhone,
		&i.SenderName,
		&i.Reference,
		&i.Note,
		&i.Status,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManualWithdrawal = `-- name: CreateManualWithdrawal :one

INSERT INTO manual_withdrawals
    (user_id, account_id, provider, currency, amount, recipient_phone, recipient_name, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, account_id, provider, currency, amount, charge, payout_amount, recipient_phone, recipient_name, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at
`

type CreateManualWithdrawalParams struct {
	UserID         uuid.UUID `json:"user_id"`
	AccountID      uuid.UUID `json:"account_id"`
	Provider       string    `json:"provider"`
	Currency       string    `json:"currency"`
	Amount         string    `json:"amount"`
	RecipientPhone string    `json:"recipient_phone"`
	RecipientName  *string   `json:"recipient_name"`
	Note           *string   `json:"note"`
}

// ─── Manual withdrawals (customer cash-out requests) ─────────────────────────
func (q *Queries) CreateManualWithdrawal(ctx context.Context, arg CreateManualWithdrawalParams) (ManualWithdrawal, error) {
	row := q.db.QueryRow(ctx, createManualWithdrawal,
		arg.UserID,
		arg.AccountID,
		arg.Provider,
		arg.Currency,
		arg.Amount,
		arg.RecipientPhone,
		arg.RecipientName,
		arg.Note,
	)
	var i ManualWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Provider,
		&i.Currency,
		&i.Amount,
		&i.Charge,
		&i.PayoutAmount,
		&i.RecipientPhone,
		&i.RecipientName,
		&i.Note,
		&i.Status,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMomoAccount = `-- name: CreateMomoAccount :one
INSERT INTO manual_momo_accounts
    (provider, display_name, phone_number, account_name, currency, country, instructions, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, provider, display_name, phone_number, account_name, currency, country, instructions, is_active, sort_order, created_at, updated_at
`

type CreateMomoAccountParams struct {
	Provider     string  `json:"provider"`
	DisplayName  string  `json:"display_name"`
	PhoneNumber  string  `json:"phone_number"`
	AccountName  *string `json:"account_name"`
	Currency     string  `json:"currency"`
	Country      string  `json:"country"`
	Instructions *string `json:"instructions"`
	IsActive     bool    `json:"is_active"`
	SortOrder    int32   `json:"sort_order"`
}

func (q *Queries) CreateMomoAccount(ctx context.Context, arg CreateMomoAccountParams) (ManualMomoAccount, error) {
	row := q.db.QueryRow(ctx, createMomoAccount,
		arg.Provider,
		arg.DisplayName,
		arg.PhoneNumber,
		arg.AccountName,
		arg.Currency,
		arg.Country,
		arg.Instructions,
		arg.IsActive,
		arg.SortOrder,
	)
	var i ManualMomoAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.DisplayName,
		&i.PhoneNumber,
		&i.AccountName,
		&i.Currency,
		&i.Country,
		&i.Instructions,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMomoAccount = `-- name: DeleteMomoAccount :exec
DELETE FROM manual_momo_accounts WHERE id = $1
`

func (q *Queries) DeleteMomoAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMomoAccount, id)
	return err
}

const getManualDeposit = `-- name: GetManualDeposit :one
SELECT id, user_id, account_id, momo_account_id, provider, currency, claimed_amount, credited_amount, charge, sender_phone, sender_name, reference, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at FROM manual_deposits WHERE id = $1
`

func (q *Queries) GetManualDeposit(ctx context.Context, id uuid.UUID) (ManualDeposit, error) {
	row := q.db.QueryRow(ctx, getManualDeposit, id)
	var i ManualDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.MomoAccountID,
		&i.Provider,
		&i.Currency,
		&i.ClaimedAmount,
		&i.CreditedAmount,
		&i.Charge,
		&i.SenderPhone,
		&i.SenderName,
		&i.Reference,
		&i.Note,
		&i.Status,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManualWithdrawal = `-- name: GetManualWithdrawal :one
SELECT id, user_id, account_id, provider, currency, amount, charge, payout_amount, recipient_phone, recipient_name, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at FROM manual_withdrawals WHERE id = $1
`

func (q *Queries) GetManualWithdrawal(ctx context.Context, id uuid.UUID) (ManualWithdrawal, error) {
	row := q.db.QueryRow(ctx, getManualWithdrawal, id)
	var i ManualWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Provider,
		&i.Currency,
		&i.Amount,
		&i.Charge,
		&i.PayoutAmount,
		&i.RecipientPhone,
		&i.RecipientName,
		&i.Note,
		&i.Status,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMomoAccount = `-- name: GetMomoAccount :one
SELECT id, provider, display_name, phone_number, account_name, currency, country, instructions, is_active, sort_order, created_at, updated_at FROM manual_momo_accounts WHERE id = $1
`

func (q *Queries) GetMomoAccount(ctx context.Context, id uuid.UUID) (ManualMomoAccount, error) {
	row := q.db.QueryRow(ctx, getMomoAccount, id)
	var i ManualMomoAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.DisplayName,
		&i.PhoneNumber,
		&i.AccountName,
		&i.Currency,
		&i.Country,
		&i.Instructions,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMomoAccounts = `-- name: ListActiveMomoAccounts :many

SELECT id, provider, display_name, phone_number, account_name, currency, country, instructions, is_active, sort_order, created_at, updated_at FROM manual_momo_accounts WHERE is_active = true ORDER BY sort_order, display_name
`

// ─── Business mobile-money collection accounts ───────────────────────────────
func (q *Queries) ListActiveMomoAccounts(ctx context.Context) ([]ManualMomoAccount, error) {
	rows, err := q.db.Query(ctx, listActiveMomoAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualMomoAccount{}
	for rows.Next() {
		var i ManualMomoAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.DisplayName,
			&i.PhoneNumber,
			&i.AccountName,
			&i.Currency,
			&i.Country,
			&i.Instructions,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMomoAccounts = `-- name: ListAllMomoAccounts :many
SELECT id, provider, display_name, phone_number, account_name, currency, country, instructions, is_active, sort_order, created_at, updated_at FROM manual_momo_accounts ORDER BY sort_order, display_name
`

func (q *Queries) ListAllMomoAccounts(ctx context.Context) ([]ManualMomoAccount, error) {
	rows, err := q.db.Query(ctx, listAllMomoAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualMomoAccount{}
	for rows.Next() {
		var i ManualMomoAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.DisplayName,
			&i.PhoneNumber,
			&i.AccountName,
			&i.Currency,
			&i.Country,
			&i.Instructions,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDepositsByStatus = `-- name: ListManualDepositsByStatus :many
SELECT id, user_id, account_id, momo_account_id, provider, currency, claimed_amount, credited_amount, charge, sender_phone, sender_name, reference, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at FROM manual_deposits
WHERE ($1::varchar = '' OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListManualDepositsByStatusParams struct {
	Status string `json:"status"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

func (q *Queries) ListManualDepositsByStatus(ctx context.Context, arg ListManualDepositsByStatusParams) ([]ManualDeposit, error) {
	rows, err := q.db.Query(ctx, listManualDepositsByStatus, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualDeposit{}
	for rows.Next() {
		var i ManualDeposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.MomoAccountID,
			&i.Provider,
			&i.Currency,
			&i.ClaimedAmount,
			&i.CreditedAmount,
			&i.Charge,
			&i.SenderPhone,
			&i.SenderName,
			&i.Reference,
			&i.Note,
			&i.Status,
			&i.AdminNote,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDepositsByUser = `-- name: ListManualDepositsByUser :many
SELECT id, user_id, account_id, momo_account_id, provider, currency, claimed_amount, credited_amount, charge, sender_phone, sender_name, reference, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at FROM manual_deposits WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListManualDepositsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListManualDepositsByUser(ctx context.Context, arg ListManualDepositsByUserParams) ([]ManualDeposit, error) {
	rows, err := q.db.Query(ctx, listManualDepositsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualDeposit{}
	for rows.Next() {
		var i ManualDeposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.MomoAccountID,
			&i.Provider,
			&i.Currency,
			&i.ClaimedAmount,
			&i.CreditedAmount,
			&i.Charge,
			&i.SenderPhone,
			&i.SenderName,
			&i.Reference,
			&i.Note,
			&i.Status,
			&i.AdminNote,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualWithdrawalsByStatus = `-- name: ListManualWithdrawalsByStatus :many
SELECT id, user_id, account_id, provider, currency, amount, charge, payout_amount, recipient_phone, recipient_name, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at FROM manual_withdrawals
WHERE ($1::varchar = '' OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListManualWithdrawalsByStatusParams struct {
	Status string `json:"status"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

func (q *Queries) ListManualWithdrawalsByStatus(ctx context.Context, arg ListManualWithdrawalsByStatusParams) ([]ManualWithdrawal, error) {
	rows, err := q.db.Query(ctx, listManualWithdrawalsByStatus, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualWithdrawal{}
	for rows.Next() {
		var i ManualWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Provider,
			&i.Currency,
			&i.Amount,
			&i.Charge,
			&i.PayoutAmount,
			&i.RecipientPhone,
			&i.RecipientName,
			&i.Note,
			&i.Status,
			&i.AdminNote,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualWithdrawalsByUser = `-- name: ListManualWithdrawalsByUser :many
SELECT id, user_id, account_id, provider, currency, amount, charge, payout_amount, recipient_phone, recipient_name, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at FROM manual_withdrawals WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListManualWithdrawalsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListManualWithdrawalsByUser(ctx context.Context, arg ListManualWithdrawalsByUserParams) ([]ManualWithdrawal, error) {
	rows, err := q.db.Query(ctx, listManualWithdrawalsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualWithdrawal{}
	for rows.Next() {
		var i ManualWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Provider,
			&i.Currency,
			&i.Amount,
			&i.Charge,
			&i.PayoutAmount,
			&i.RecipientPhone,
			&i.RecipientName,
			&i.Note,
			&i.Status,
			&i.AdminNote,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectManualDeposit = `-- name: RejectManualDeposit :one
UPDATE manual_deposits
SET status = 'rejected', admin_note = $2, reviewed_by = $3, reviewed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, account_id, momo_account_id, provider, currency, claimed_amount, credited_amount, charge, sender_phone, sender_name, reference, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at
`

type RejectManualDepositParams struct {
	ID         uuid.UUID  `json:"id"`
	AdminNote  *string    `json:"admin_note"`
	ReviewedBy *uuid.UUID `json:"reviewed_by"`
}

func (q *Queries) RejectManualDeposit(ctx context.Context, arg RejectManualDepositParams) (ManualDeposit, error) {
	row := q.db.QueryRow(ctx, rejectManualDeposit, arg.ID, arg.AdminNote, arg.ReviewedBy)
	var i ManualDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.MomoAccountID,
		&i.Provider,
		&i.Currency,
		&i.ClaimedAmount,
		&i.CreditedAmount,
		&i.Charge,
		&i.SenderPhone,
		&i.SenderName,
		&i.Reference,
		&i.Note,
		&i.Status,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectManualWithdrawal = `-- name: RejectManualWithdrawal :one
UPDATE manual_withdrawals
SET status = 'rejected', admin_note = $2, reviewed_by = $3, reviewed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, account_id, provider, currency, amount, charge, payout_amount, recipient_phone, recipient_name, note, status, admin_note, reviewed_by, reviewed_at, created_at, updated_at
`

type RejectManualWithdrawalParams struct {
	ID         uuid.UUID  `json:"id"`
	AdminNote  *string    `json:"admin_note"`
	ReviewedBy *uuid.UUID `json:"reviewed_by"`
}

func (q *Queries) RejectManualWithdrawal(ctx context.Context, arg RejectManualWithdrawalParams) (ManualWithdrawal, error) {
	row := q.db.QueryRow(ctx, rejectManualWithdrawal, arg.ID, arg.AdminNote, arg.ReviewedBy)
	var i ManualWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Provider,
		&i.Currency,
		&i.Amount,
		&i.Charge,
		&i.PayoutAmount,
		&i.RecipientPhone,
		&i.RecipientName,
		&i.Note,
		&i.Status,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMomoAccount = `-- name: UpdateMomoAccount :one
UPDATE manual_momo_accounts
SET provider = $2, display_name = $3, phone_number = $4, account_name = $5,
    currency = $6, country = $7, instructions = $8, is_active = $9, sort_order = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, provider, display_name, phone_number, account_name, currency, country, instructions, is_active, sort_order, created_at, updated_at
`

type UpdateMomoAccountParams struct {
	ID           uuid.UUID `json:"id"`
	Provider     string    `json:"provider"`
	DisplayName  string    `json:"display_name"`
	PhoneNumber  string    `json:"phone_number"`
	AccountName  *string   `json:"account_name"`
	Currency     string    `json:"currency"`
	Country      string    `json:"country"`
	Instructions *string   `json:"instructions"`
	IsActive     bool      `json:"is_active"`
	SortOrder    int32     `json:"sort_order"`
}

func (q *Queries) UpdateMomoAccount(ctx context.Context, arg UpdateMomoAccountParams) (ManualMomoAccount, error) {
	row := q.db.QueryRow(ctx, updateMomoAccount,
		arg.ID,
		arg.Provider,
		arg.DisplayName,
		arg.PhoneNumber,
		arg.AccountName,
		arg.Currency,
		arg.Country,
		arg.Instructions,
		arg.IsActive,
		arg.SortOrder,
	)
	var i ManualMomoAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.DisplayName,
		&i.PhoneNumber,
		&i.AccountName,
		&i.Currency,
		&i.Country,
		&i.Instructions,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
