// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID `json:"id"`
	PhoneNumber  string    `json:"phone_number"`
	Email        *string   `json:"email"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PinHash      *string   `json:"pin_hash"` // nullable for social-auth users
	KycStatus    string    `json:"kyc_status"`
	IsActive     bool      `json:"is_active"`
	Role         string    `json:"role"`          // "user" | "admin"
	AuthProvider string    `json:"auth_provider"` // "phone" | "google"
	GoogleSub    *string   `json:"google_sub"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Account struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	Currency         string         `json:"currency"`
	Balance          pgtype.Numeric `json:"balance"`
	AvailableBalance pgtype.Numeric `json:"available_balance"`
	AccountNumber    string         `json:"account_number"`
	Status           string         `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type Transaction struct {
	ID          uuid.UUID       `json:"id"`
	Reference   string          `json:"reference"`
	AccountID   uuid.UUID       `json:"account_id"`
	Type        string          `json:"type"`
	Amount      pgtype.Numeric  `json:"amount"`
	Currency    string          `json:"currency"`
	Fee         pgtype.Numeric  `json:"fee"`
	Description *string         `json:"description"`
	Status      string          `json:"status"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type WaasWallet struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	WaasWalletID string    `json:"waas_wallet_id"`
	Network      string    `json:"network"`
	Address      string    `json:"address"`
	IsDefault    bool      `json:"is_default"`
	CreatedAt    time.Time `json:"created_at"`
}

type CaasWallet struct {
	ID                 uuid.UUID `json:"id"`
	UserID             uuid.UUID `json:"user_id"`
	CaasWalletID       string    `json:"caas_wallet_id"`
	BlindIndex         *string   `json:"blind_index"`
	AbstractionAddress string    `json:"abstraction_address"`
	IsActive           bool      `json:"is_active"`
	CreatedAt          time.Time `json:"created_at"`
}

type CryptoTransaction struct {
	ID              uuid.UUID      `json:"id"`
	Reference       string         `json:"reference"`
	SenderUserID    uuid.UUID      `json:"sender_user_id"`
	ReceiverPhone   string         `json:"receiver_phone"`
	ReceiverUserID  *uuid.UUID     `json:"receiver_user_id"`
	Token           string         `json:"token"`
	Amount          pgtype.Numeric `json:"amount"`
	TxHash          *string        `json:"tx_hash"`
	Status          string         `json:"status"`
	QuoteID         *string        `json:"quote_id"`
	CaasTransferID  *string        `json:"caas_transfer_id"`
	IdempotencyKey  *string        `json:"idempotency_key"`
	LocalFiatAmount *string        `json:"local_fiat_amount"`
	LocalCurrency   *string        `json:"local_currency"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type KycDocument struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	DocType         string    `json:"doc_type"`
	DocURL          string    `json:"doc_url"`
	Status          string    `json:"status"`
	RejectionReason *string   `json:"rejection_reason"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Hub2Payment struct {
	ID            uuid.UUID       `json:"id"`
	TransactionID *uuid.UUID      `json:"transaction_id"`
	Hub2Reference string          `json:"hub2_reference"`
	PaymentMethod string          `json:"payment_method"`
	Operator      *string         `json:"operator"`
	PhoneNumber   *string         `json:"phone_number"`
	Status        string          `json:"status"`
	Hub2Status    *string         `json:"hub2_status"`
	Metadata      json.RawMessage `json:"metadata"`
	CaasFundedAt  *time.Time      `json:"caas_funded_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type FxQuote struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	QuoteID       string    `json:"quote_id"`
	FiatAmount    string    `json:"fiat_amount"`
	LocalCurrency string    `json:"local_currency"`
	TargetToken   string    `json:"target_token"`
	Rate          string    `json:"rate"`
	ExpiresAt     time.Time `json:"expires_at"`
	Used          bool      `json:"used"`
	CreatedAt     time.Time `json:"created_at"`
}

type CaasWithdrawal struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	CaasWithdrawalID string    `json:"caas_withdrawal_id"`
	Phone            string    `json:"phone"`
	Amount           string    `json:"amount"`
	Token            string    `json:"token"`
	PayoutMobile     string    `json:"payout_mobile"`
	PayoutNetwork    string    `json:"payout_network"`
	IdempotencyKey   string    `json:"idempotency_key"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Otp struct {
	ID          uuid.UUID `json:"id"`
	PhoneNumber string    `json:"phone_number"`
	Code        string    `json:"code"`
	ExpiresAt   time.Time `json:"expires_at"`
	Used        bool      `json:"used"`
	CreatedAt   time.Time `json:"created_at"`
}

// ─── Migration 000003 models ───────────────────────────────────────────────────

type UserSession struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	DeviceName       *string   `json:"device_name"`
	DeviceIP         *string   `json:"device_ip"`
	DeviceUA         *string   `json:"device_ua"`
	IsActive         bool      `json:"is_active"`
	LastUsedAt       time.Time `json:"last_used_at"`
	CreatedAt        time.Time `json:"created_at"`
	ExpiresAt        time.Time `json:"expires_at"`
}

type EmailOtp struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	Purpose   string    `json:"purpose"` // verify_email | pin_reset
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type MetamapVerification struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	ApplicantID    string          `json:"applicant_id"`
	FlowID         string          `json:"flow_id"`
	IdentityAccess string          `json:"identity_access"`
	Status         string          `json:"status"`
	ResultData     json.RawMessage `json:"result_data"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

// User is extended with profile fields from migration 000003.
// The base User struct above keeps the original fields for backward compat.
// Services should use UserFull when they need profile fields.
type UserFull struct {
	ID              uuid.UUID `json:"id"`
	PhoneNumber     string    `json:"phone_number"`
	Email           *string   `json:"email"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	PinHash         *string   `json:"pin_hash"` // nullable for social-auth users
	KycStatus       string    `json:"kyc_status"`
	IsActive        bool      `json:"is_active"`
	Role            string    `json:"role"`
	AuthProvider    string    `json:"auth_provider"`
	GoogleSub       *string   `json:"google_sub"`
	Bio             *string   `json:"bio"`
	AvatarURL       *string   `json:"avatar_url"`
	DateOfBirth     *string   `json:"date_of_birth"` // ISO date string YYYY-MM-DD
	Nationality     *string   `json:"nationality"`
	IsEmailVerified bool      `json:"is_email_verified"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type KycAdminAction struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	AdminID   uuid.UUID `json:"admin_id"`
	Action    string    `json:"action"` // "approved" | "rejected"
	Reason    *string   `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
}

// ─── Migration 000005 models ───────────────────────────────────────────────────

type VirtualCard struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	CardName    string    `json:"card_name"`
	LastFour    string    `json:"last_four"`
	Currency    string    `json:"currency"`
	CardNetwork string    `json:"card_network"` // "mastercard" | "visa"
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
}

type FXRate struct {
	BaseCurrency  string    `json:"base_currency"`
	QuoteCurrency string    `json:"quote_currency"`
	Rate          string    `json:"rate"` // decimal string
	Source        string    `json:"source"`
	FetchedAt     time.Time `json:"fetched_at"`
}

// AccountWithNilos extends Account with Nilos-specific fields from migration 000005.
type AccountWithNilos struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	Currency         string    `json:"currency"`
	Balance          string    `json:"balance"`           // from pgtype.Numeric as string
	AvailableBalance string    `json:"available_balance"` // from pgtype.Numeric as string
	AccountNumber    string    `json:"account_number"`
	Status           string    `json:"status"`
	NilosAccountID   *string   `json:"nilos_account_id"`
	NilosCustomerID  *string   `json:"nilos_customer_id"`
	IBAN             *string   `json:"iban"`
	BIC              *string   `json:"bic"`
	CreatedAt        time.Time `json:"created_at"`
}

// ─── Migration 000006 models ───────────────────────────────────────────────────

type Notification struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Type      string          `json:"type"`
	Title     string          `json:"title"`
	Body      string          `json:"body"`
	IsRead    bool            `json:"is_read"`
	Metadata  json.RawMessage `json:"metadata,omitempty"`
	CreatedAt time.Time       `json:"created_at"`
}
