// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	Currency         string         `json:"currency"`
	Balance          pgtype.Numeric `json:"balance"`
	AvailableBalance pgtype.Numeric `json:"available_balance"`
	AccountNumber    string         `json:"account_number"`
	Status           string         `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	NilosAccountID   *string        `json:"nilos_account_id"`
	NilosCustomerID  *string        `json:"nilos_customer_id"`
	Iban             *string        `json:"iban"`
	Bic              *string        `json:"bic"`
}

type AdminAuditLog struct {
	ID         uuid.UUID `json:"id"`
	StaffID    uuid.UUID `json:"staff_id"`
	StaffName  string    `json:"staff_name"`
	StaffEmail string    `json:"staff_email"`
	Action     string    `json:"action"`
	Resource   string    `json:"resource"`
	ResourceID *string   `json:"resource_id"`
	Details    []byte    `json:"details"`
	IPAddress  *string   `json:"ip_address"`
	CreatedAt  time.Time `json:"created_at"`
}

type AdminStaff struct {
	ID                 uuid.UUID       `json:"id"`
	UserID             *uuid.UUID      `json:"user_id"`
	Email              string          `json:"email"`
	Name               string          `json:"name"`
	Role               string          `json:"role"`
	CustomPermissions  json.RawMessage `json:"custom_permissions"`
	RevokedPermissions json.RawMessage `json:"revoked_permissions"`
	IsActive           bool            `json:"is_active"`
	InvitedBy          *uuid.UUID      `json:"invited_by"`
	InviteToken        *string         `json:"invite_token"`
	InviteAcceptedAt   *time.Time      `json:"invite_accepted_at"`
	LastLoginAt        *time.Time      `json:"last_login_at"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type Beneficiary struct {
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"user_id"`
	Label               string    `json:"label"`
	Type                string    `json:"type"`
	DestinationCurrency string    `json:"destination_currency"`
	Country             string    `json:"country"`
	PhoneNumber         *string   `json:"phone_number"`
	Operator            *string   `json:"operator"`
	BankName            *string   `json:"bank_name"`
	AccountNumber       *string   `json:"account_number"`
	Iban                *string   `json:"iban"`
	SwiftCode           *string   `json:"swift_code"`
	SortCode            *string   `json:"sort_code"`
	RoutingNumber       *string   `json:"routing_number"`
	NilosRecipientID    *string   `json:"nilos_recipient_id"`
	CreatedAt           time.Time `json:"created_at"`
}

type BusinessDirector struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	JobTitle    string    `json:"job_title"`
	DateOfBirth time.Time `json:"date_of_birth"`
	Nationality string    `json:"nationality"`
	PhoneNumber string    `json:"phone_number"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type BusinessFxRate struct {
	ID             uuid.UUID      `json:"id"`
	SourceCurrency string         `json:"source_currency"`
	TargetCurrency string         `json:"target_currency"`
	Rate           pgtype.Numeric `json:"rate"`
	FeePercent     pgtype.Numeric `json:"fee_percent"`
	FlatFee        pgtype.Numeric `json:"flat_fee"`
	IsActive       bool           `json:"is_active"`
	SetBy          *uuid.UUID     `json:"set_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type BusinessProfile struct {
	UserID                 uuid.UUID `json:"user_id"`
	CompanyLegalName       string    `json:"company_legal_name"`
	CompanyRegistrationNo  string    `json:"company_registration_no"`
	Industry               string    `json:"industry"`
	CountryOfIncorporation string    `json:"country_of_incorporation"`
	AnnualRevenue          string    `json:"annual_revenue"`
	BusinessWebsite        *string   `json:"business_website"`
	DirectorsComplete      bool      `json:"directors_complete"`
	DocumentsComplete      bool      `json:"documents_complete"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type CaasWallet struct {
	ID                 uuid.UUID `json:"id"`
	UserID             uuid.UUID `json:"user_id"`
	CaasWalletID       string    `json:"caas_wallet_id"`
	AbstractionAddress string    `json:"abstraction_address"`
	IsActive           bool      `json:"is_active"`
	CreatedAt          time.Time `json:"created_at"`
	BlindIndex         *string   `json:"blind_index"`
}

type CaasWithdrawal struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	CaasWithdrawalID string    `json:"caas_withdrawal_id"`
	Phone            string    `json:"phone"`
	Amount           string    `json:"amount"`
	Token            string    `json:"token"`
	PayoutMobile     string    `json:"payout_mobile"`
	PayoutNetwork    string    `json:"payout_network"`
	IdempotencyKey   string    `json:"idempotency_key"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type CryptoTransaction struct {
	ID              uuid.UUID  `json:"id"`
	Reference       string     `json:"reference"`
	SenderUserID    uuid.UUID  `json:"sender_user_id"`
	ReceiverPhone   string     `json:"receiver_phone"`
	ReceiverUserID  *uuid.UUID `json:"receiver_user_id"`
	Token           string     `json:"token"`
	Amount          string     `json:"amount"`
	TxHash          *string    `json:"tx_hash"`
	Status          string     `json:"status"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	QuoteID         *string    `json:"quote_id"`
	CaasTransferID  *string    `json:"caas_transfer_id"`
	IdempotencyKey  *string    `json:"idempotency_key"`
	LocalFiatAmount *string    `json:"local_fiat_amount"`
	LocalCurrency   *string    `json:"local_currency"`
}

type EmailOtp struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type Faq struct {
	ID        uuid.UUID `json:"id"`
	Question  string    `json:"question"`
	Answer    string    `json:"answer"`
	Category  string    `json:"category"`
	SortOrder int32     `json:"sort_order"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type FiatWithdrawal struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	SourceCurrency      string         `json:"source_currency"`
	SourceAmount        pgtype.Numeric `json:"source_amount"`
	Fee                 pgtype.Numeric `json:"fee"`
	FeeCurrency         string         `json:"fee_currency"`
	FxRate              pgtype.Numeric `json:"fx_rate"`
	DestinationType     string         `json:"destination_type"`
	DestinationCurrency string         `json:"destination_currency"`
	DestinationAmount   pgtype.Numeric `json:"destination_amount"`
	DestinationCountry  string         `json:"destination_country"`
	RecipientName       string         `json:"recipient_name"`
	PhoneNumber         *string        `json:"phone_number"`
	Operator            *string        `json:"operator"`
	BankName            *string        `json:"bank_name"`
	AccountNumber       *string        `json:"account_number"`
	Iban                *string        `json:"iban"`
	SwiftCode           *string        `json:"swift_code"`
	SortCode            *string        `json:"sort_code"`
	RoutingNumber       *string        `json:"routing_number"`
	Status              string         `json:"status"`
	NilosPayoutID       *string        `json:"nilos_payout_id"`
	NilosRecipientID    *string        `json:"nilos_recipient_id"`
	Hub2Reference       *string        `json:"hub2_reference"`
	FailureReason       *string        `json:"failure_reason"`
	Reference           string         `json:"reference"`
	BeneficiaryID       *uuid.UUID     `json:"beneficiary_id"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type FxQuote struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	QuoteID       string         `json:"quote_id"`
	FiatAmount    pgtype.Numeric `json:"fiat_amount"`
	LocalCurrency string         `json:"local_currency"`
	TargetToken   string         `json:"target_token"`
	Rate          pgtype.Numeric `json:"rate"`
	ExpiresAt     time.Time      `json:"expires_at"`
	Used          bool           `json:"used"`
	CreatedAt     time.Time      `json:"created_at"`
}

type FxRate struct {
	BaseCurrency  string         `json:"base_currency"`
	QuoteCurrency string         `json:"quote_currency"`
	Rate          pgtype.Numeric `json:"rate"`
	Source        *string        `json:"source"`
	FetchedAt     time.Time      `json:"fetched_at"`
}

type Hub2Payment struct {
	ID            uuid.UUID  `json:"id"`
	TransactionID *uuid.UUID `json:"transaction_id"`
	Hub2Reference string     `json:"hub2_reference"`
	PaymentMethod string     `json:"payment_method"`
	Operator      *string    `json:"operator"`
	PhoneNumber   *string    `json:"phone_number"`
	Status        string     `json:"status"`
	Hub2Status    *string    `json:"hub2_status"`
	Metadata      []byte     `json:"metadata"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	CaasFundedAt  *time.Time `json:"caas_funded_at"`
}

type KycAdminAction struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	AdminID   uuid.UUID `json:"admin_id"`
	Action    string    `json:"action"`
	Reason    *string   `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
}

type KycDocument struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	DocType         string    `json:"doc_type"`
	DocURL          string    `json:"doc_url"`
	Status          string    `json:"status"`
	RejectionReason *string   `json:"rejection_reason"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type MerchantStaff struct {
	ID             uuid.UUID  `json:"id"`
	BusinessUserID uuid.UUID  `json:"business_user_id"`
	StaffUserID    *uuid.UUID `json:"staff_user_id"`
	Email          string     `json:"email"`
	Role           string     `json:"role"`
	Status         string     `json:"status"`
	InviteToken    *string    `json:"invite_token"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type MetamapVerification struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	ApplicantID    string    `json:"applicant_id"`
	FlowID         string    `json:"flow_id"`
	IdentityAccess string    `json:"identity_access"`
	Status         string    `json:"status"`
	ResultData     []byte    `json:"result_data"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Notification struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	IsRead    bool      `json:"is_read"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

type Otp struct {
	ID          uuid.UUID `json:"id"`
	PhoneNumber string    `json:"phone_number"`
	Code        string    `json:"code"`
	ExpiresAt   time.Time `json:"expires_at"`
	Used        bool      `json:"used"`
	CreatedAt   time.Time `json:"created_at"`
}

type PlatformLimit struct {
	Tier                  string     `json:"tier"`
	DailyWithdrawalUsd    float64    `json:"daily_withdrawal_usd"`
	PerTransactionUsd     float64    `json:"per_transaction_usd"`
	MonthlyVolumeUsd      float64    `json:"monthly_volume_usd"`
	MaxHoldingBalanceUsd  float64    `json:"max_holding_balance_usd"`
	DailyTransactionCount int32      `json:"daily_transaction_count"`
	UpdatedAt             time.Time  `json:"updated_at"`
	UpdatedBy             *uuid.UUID `json:"updated_by"`
}

type PointsLedger struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Amount      int32     `json:"amount"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type SumsubVerification struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ApplicantID string    `json:"applicant_id"`
	LevelName   string    `json:"level_name"`
	AccessToken string    `json:"access_token"`
	Status      string    `json:"status"`
	ResultData  []byte    `json:"result_data"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type SupportMessage struct {
	ID         uuid.UUID  `json:"id"`
	TicketID   uuid.UUID  `json:"ticket_id"`
	SenderType string     `json:"sender_type"`
	SenderID   *uuid.UUID `json:"sender_id"`
	Body       string     `json:"body"`
	CreatedAt  time.Time  `json:"created_at"`
}

type SupportTicket struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Reference string    `json:"reference"`
	Subject   string    `json:"subject"`
	Category  string    `json:"category"`
	Status    string    `json:"status"`
	Priority  string    `json:"priority"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Transaction struct {
	ID          uuid.UUID      `json:"id"`
	Reference   string         `json:"reference"`
	AccountID   uuid.UUID      `json:"account_id"`
	Type        string         `json:"type"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    string         `json:"currency"`
	Fee         pgtype.Numeric `json:"fee"`
	Description *string        `json:"description"`
	Status      string         `json:"status"`
	Metadata    []byte         `json:"metadata"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID                uuid.UUID  `json:"id"`
	PhoneNumber       string     `json:"phone_number"`
	Email             *string    `json:"email"`
	FirstName         string     `json:"first_name"`
	LastName          string     `json:"last_name"`
	PinHash           *string    `json:"pin_hash"`
	KycStatus         string     `json:"kyc_status"`
	IsActive          bool       `json:"is_active"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Bio               *string    `json:"bio"`
	AvatarURL         *string    `json:"avatar_url"`
	DateOfBirth       *string    `json:"date_of_birth"`
	Nationality       *string    `json:"nationality"`
	IsEmailVerified   bool       `json:"is_email_verified"`
	Role              string     `json:"role"`
	AuthProvider      string     `json:"auth_provider"`
	GoogleSub         *string    `json:"google_sub"`
	TOTPSecret        *string    `json:"totp_secret"`
	TOTPEnabled       bool       `json:"totp_enabled"`
	AccountType       string     `json:"account_type"`
	Country           *string    `json:"country"`
	KycProvider       *string    `json:"kyc_provider"`
	ReferralCode      *string    `json:"referral_code"`
	ReferredBy        *uuid.UUID `json:"referred_by"`
	KycProviderStatus *string    `json:"kyc_provider_status"`
	KycManualOverride bool       `json:"kyc_manual_override"`
	Bvn               *string    `json:"bvn"`
}

type UserLimitOverride struct {
	UserID                uuid.UUID  `json:"user_id"`
	DailyWithdrawalUsd    *float64   `json:"daily_withdrawal_usd"`
	PerTransactionUsd     *float64   `json:"per_transaction_usd"`
	MonthlyVolumeUsd      *float64   `json:"monthly_volume_usd"`
	MaxHoldingBalanceUsd  *float64   `json:"max_holding_balance_usd"`
	DailyTransactionCount *int32     `json:"daily_transaction_count"`
	Note                  string     `json:"note"`
	UpdatedAt             time.Time  `json:"updated_at"`
	UpdatedBy             *uuid.UUID `json:"updated_by"`
}

type UserPreference struct {
	UserID            uuid.UUID `json:"user_id"`
	Language          string    `json:"language"`
	DarkMode          string    `json:"dark_mode"`
	BiometricsEnabled bool      `json:"biometrics_enabled"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type UserSession struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	DeviceName       *string   `json:"device_name"`
	DeviceIP         *string   `json:"device_ip"`
	DeviceUA         *string   `json:"device_ua"`
	IsActive         bool      `json:"is_active"`
	LastUsedAt       time.Time `json:"last_used_at"`
	CreatedAt        time.Time `json:"created_at"`
	ExpiresAt        time.Time `json:"expires_at"`
}

type VirtualCard struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	CardName    string    `json:"card_name"`
	LastFour    string    `json:"last_four"`
	Currency    string    `json:"currency"`
	CardNetwork string    `json:"card_network"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
}

type WaasWallet struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	WaasWalletID string    `json:"waas_wallet_id"`
	Network      string    `json:"network"`
	Address      string    `json:"address"`
	IsDefault    bool      `json:"is_default"`
	CreatedAt    time.Time `json:"created_at"`
}
