// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otps (phone_number, code, expires_at)
VALUES ($1, $2, $3)
RETURNING id, phone_number, code, expires_at, used, created_at
`

type CreateOTPParams struct {
	PhoneNumber string    `json:"phone_number"`
	Code        string    `json:"code"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error) {
	row := q.db.QueryRow(ctx, createOTP, arg.PhoneNumber, arg.Code, arg.ExpiresAt)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Code,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM otps WHERE expires_at < NOW() OR used = true
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const getValidOTP = `-- name: GetValidOTP :one
SELECT id, phone_number, code, expires_at, used, created_at FROM otps
WHERE phone_number = $1
  AND code         = $2
  AND expires_at  > NOW()
  AND used         = false
LIMIT 1
`

type GetValidOTPParams struct {
	PhoneNumber string `json:"phone_number"`
	Code        string `json:"code"`
}

func (q *Queries) GetValidOTP(ctx context.Context, arg GetValidOTPParams) (Otp, error) {
	row := q.db.QueryRow(ctx, getValidOTP, arg.PhoneNumber, arg.Code)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Code,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otps SET used = true WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}
