// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences_extra.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserPreferences = `-- name: CreateUserPreferences :exec
INSERT INTO user_preferences (user_id, language, dark_mode, biometrics_enabled)
VALUES ($1, $2, $3, $4)
`

type CreateUserPreferencesParams struct {
	UserID            uuid.UUID `json:"user_id"`
	Language          string    `json:"language"`
	DarkMode          string    `json:"dark_mode"`
	BiometricsEnabled bool      `json:"biometrics_enabled"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, createUserPreferences,
		arg.UserID,
		arg.Language,
		arg.DarkMode,
		arg.BiometricsEnabled,
	)
	return err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, language, dark_mode, biometrics_enabled, created_at, updated_at FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.DarkMode,
		&i.BiometricsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE user_preferences
SET language = $2, dark_mode = $3, biometrics_enabled = $4, updated_at = now()
WHERE user_id = $1
`

type UpdateUserPreferencesParams struct {
	UserID            uuid.UUID `json:"user_id"`
	Language          string    `json:"language"`
	DarkMode          string    `json:"dark_mode"`
	BiometricsEnabled bool      `json:"biometrics_enabled"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences,
		arg.UserID,
		arg.Language,
		arg.DarkMode,
		arg.BiometricsEnabled,
	)
	return err
}
