// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptMerchantStaffInvite(ctx context.Context, arg AcceptMerchantStaffInviteParams) error
	AcceptStaffInvite(ctx context.Context, arg AcceptStaffInviteParams) error
	CountActivity(ctx context.Context, arg CountActivityParams) (int64, error)
	CountAdminAuditLogs(ctx context.Context, arg CountAdminAuditLogsParams) (int64, error)
	CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error)
	CountStaffMembers(ctx context.Context, includeInactive bool) (int64, error)
	CountTransactionsByAccount(ctx context.Context, accountID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error)
	// Business director queries
	CreateBusinessDirector(ctx context.Context, arg CreateBusinessDirectorParams) (BusinessDirector, error)
	// Business profile queries
	CreateBusinessProfile(ctx context.Context, arg CreateBusinessProfileParams) (BusinessProfile, error)
	CreateBusinessUser(ctx context.Context, arg CreateBusinessUserParams) (User, error)
	// ─── CaaS wallet queries ──────────────────────────────────────────────────────
	CreateCaasWalletFull(ctx context.Context, arg CreateCaasWalletFullParams) (CaasWallet, error)
	// ─── CaaS withdrawal queries ──────────────────────────────────────────────────
	CreateCaasWithdrawal(ctx context.Context, arg CreateCaasWithdrawalParams) (CaasWithdrawal, error)
	CreateCryptoTransaction(ctx context.Context, arg CreateCryptoTransactionParams) (CryptoTransaction, error)
	CreateEmailOTP(ctx context.Context, arg CreateEmailOTPParams) (EmailOtp, error)
	// ─── FX quote queries ─────────────────────────────────────────────────────────
	CreateFXQuote(ctx context.Context, arg CreateFXQuoteParams) (FxQuote, error)
	CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error)
	CreateHub2Payment(ctx context.Context, arg CreateHub2PaymentParams) (Hub2Payment, error)
	CreateIndividualUser(ctx context.Context, arg CreateIndividualUserParams) (User, error)
	CreateKYCDocument(ctx context.Context, arg CreateKYCDocumentParams) (KycDocument, error)
	// Merchant staff queries
	CreateMerchantStaff(ctx context.Context, arg CreateMerchantStaffParams) (MerchantStaff, error)
	// MetaMap verification queries
	CreateMetamapVerification(ctx context.Context, arg CreateMetamapVerificationParams) (MetamapVerification, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error)
	CreatePointsRecord(ctx context.Context, arg CreatePointsRecordParams) (PointsLedger, error)
	CreateStaffMember(ctx context.Context, arg CreateStaffMemberParams) (AdminStaff, error)
	CreateSumsubVerification(ctx context.Context, arg CreateSumsubVerificationParams) (SumsubVerification, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	// ─── WaaS (Payments API custody wallets) ──────────────────────────────────
	CreateWaasWallet(ctx context.Context, arg CreateWaasWalletParams) (WaasWallet, error)
	CreditAccount(ctx context.Context, arg CreditAccountParams) (Account, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	DebitAccount(ctx context.Context, arg DebitAccountParams) (Account, error)
	DeleteBusinessDirector(ctx context.Context, arg DeleteBusinessDirectorParams) error
	DeleteExpiredEmailOTPs(ctx context.Context) error
	DeleteExpiredFXQuotes(ctx context.Context) error
	DeleteExpiredOTPs(ctx context.Context) error
	DeleteMerchantStaff(ctx context.Context, arg DeleteMerchantStaffParams) error
	DeleteUserLimitOverride(ctx context.Context, userID uuid.UUID) error
	DisableStaffMember(ctx context.Context, id uuid.UUID) error
	EnableStaffMember(ctx context.Context, id uuid.UUID) error
	FreezeAccount(ctx context.Context, id uuid.UUID) error
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByUserAndCurrency(ctx context.Context, arg GetAccountByUserAndCurrencyParams) (Account, error)
	GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountWithNilos(ctx context.Context, id uuid.UUID) (GetAccountWithNilosRow, error)
	GetAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]Account, error)
	GetActiveMerchantStaffByUser(ctx context.Context, staffUserID *uuid.UUID) ([]MerchantStaff, error)
	GetAdminDashboardStats(ctx context.Context) (GetAdminDashboardStatsRow, error)
	GetAdminUserView(ctx context.Context, id uuid.UUID) (GetAdminUserViewRow, error)
	// Daily net fiat flow per day across all the user's fiat accounts.
	// The service layer accumulates these into a balance trend and fills in
	// crypto from live balances.
	GetBalanceTrend(ctx context.Context, arg GetBalanceTrendParams) ([]GetBalanceTrendRow, error)
	GetBusinessProfileByUserID(ctx context.Context, userID uuid.UUID) (BusinessProfile, error)
	GetCaasWalletByAddress(ctx context.Context, abstractionAddress string) (CaasWallet, error)
	GetCaasWalletByBlindIndex(ctx context.Context, blindIndex *string) (CaasWallet, error)
	GetCaasWalletByUserID(ctx context.Context, userID uuid.UUID) (CaasWallet, error)
	GetCaasWithdrawalByCaasID(ctx context.Context, caasWithdrawalID string) (CaasWithdrawal, error)
	GetCaasWithdrawalByID(ctx context.Context, id uuid.UUID) (CaasWithdrawal, error)
	GetCaasWithdrawalByIdempotencyKey(ctx context.Context, idempotencyKey string) (CaasWithdrawal, error)
	GetCryptoTransactionByID(ctx context.Context, id uuid.UUID) (CryptoTransaction, error)
	// ─── crypto_transactions CaaS extras ─────────────────────────────────────────
	// (CreateCryptoTransaction is defined in the existing stub; the params struct is
	//  extended in query.sql.go to include the nullable CaaS fields below.)
	GetCryptoTransactionByIdempotencyKey(ctx context.Context, idempotencyKey *string) (CryptoTransaction, error)
	GetCryptoTransactionByReference(ctx context.Context, reference string) (CryptoTransaction, error)
	GetDefaultWaasWallet(ctx context.Context, userID uuid.UUID) (WaasWallet, error)
	GetFXQuoteByQuoteID(ctx context.Context, quoteID string) (FxQuote, error)
	GetHub2PaymentByReference(ctx context.Context, hub2Reference string) (Hub2Payment, error)
	GetHub2PaymentByReferenceForFunding(ctx context.Context, hub2Reference string) (Hub2Payment, error)
	GetKYCDocumentsByUserID(ctx context.Context, userID uuid.UUID) ([]KycDocument, error)
	GetMerchantStaffByEmailAndBusiness(ctx context.Context, arg GetMerchantStaffByEmailAndBusinessParams) (MerchantStaff, error)
	GetMerchantStaffByID(ctx context.Context, id uuid.UUID) (MerchantStaff, error)
	GetMerchantStaffByInviteToken(ctx context.Context, inviteToken *string) (MerchantStaff, error)
	GetMetamapVerificationByApplicantID(ctx context.Context, applicantID string) (MetamapVerification, error)
	GetMetamapVerificationByUserID(ctx context.Context, userID uuid.UUID) (MetamapVerification, error)
	GetMonthlyFlow(ctx context.Context, arg GetMonthlyFlowParams) ([]GetMonthlyFlowRow, error)
	GetPlatformLimit(ctx context.Context, tier string) (PlatformLimit, error)
	GetPointsBalance(ctx context.Context, userID uuid.UUID) (int64, error)
	GetPointsHistory(ctx context.Context, arg GetPointsHistoryParams) ([]PointsLedger, error)
	GetReferralsCount(ctx context.Context, referredBy *uuid.UUID) (int64, error)
	GetReferralsList(ctx context.Context, referredBy *uuid.UUID) ([]GetReferralsListRow, error)
	GetSpendingByType(ctx context.Context, arg GetSpendingByTypeParams) ([]GetSpendingByTypeRow, error)
	GetStaffMemberByEmail(ctx context.Context, email string) (AdminStaff, error)
	GetStaffMemberByID(ctx context.Context, id uuid.UUID) (AdminStaff, error)
	GetStaffMemberByInviteToken(ctx context.Context, inviteToken *string) (AdminStaff, error)
	GetStaffMemberByUserID(ctx context.Context, userID *uuid.UUID) (AdminStaff, error)
	GetSumsubVerificationByApplicantID(ctx context.Context, applicantID string) (SumsubVerification, error)
	GetSumsubVerificationByUserID(ctx context.Context, userID uuid.UUID) (SumsubVerification, error)
	GetSupportTicketWithMessages(ctx context.Context, id uuid.UUID) (GetSupportTicketWithMessagesRow, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionByReference(ctx context.Context, reference string) (Transaction, error)
	// Aggregate transaction stats across all of a user's fiat accounts since a
	// given time. Powers the business analytics dashboard (count / volume / avg /
	// largest). Volume is the sum of absolute amounts (both in- and out-flows).
	GetTransactionStatsSince(ctx context.Context, arg GetTransactionStatsSinceParams) (GetTransactionStatsSinceRow, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	GetUserByReferralCode(ctx context.Context, referralCode *string) (User, error)
	GetUserFullByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserLimitOverride(ctx context.Context, userID uuid.UUID) (UserLimitOverride, error)
	GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreference, error)
	GetUserSecurity(ctx context.Context, id uuid.UUID) (GetUserSecurityRow, error)
	GetUserSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error)
	GetUserSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error)
	GetValidEmailOTP(ctx context.Context, arg GetValidEmailOTPParams) (EmailOtp, error)
	GetValidOTP(ctx context.Context, arg GetValidOTPParams) (Otp, error)
	// Per-currency transaction count and volume since a given time. Gives business
	// accounts a currency-level breakdown of their activity.
	GetVolumeByCurrencySince(ctx context.Context, arg GetVolumeByCurrencySinceParams) ([]GetVolumeByCurrencySinceRow, error)
	GetWaasWalletByAddress(ctx context.Context, address string) (WaasWallet, error)
	GetWaasWalletByIDAndUser(ctx context.Context, arg GetWaasWalletByIDAndUserParams) (WaasWallet, error)
	GetWaasWalletByNetwork(ctx context.Context, arg GetWaasWalletByNetworkParams) (WaasWallet, error)
	GetWaasWalletsByUserID(ctx context.Context, userID uuid.UUID) ([]WaasWallet, error)
	ListActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]UserSession, error)
	ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error)
	ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]AdminAuditLog, error)
	ListBusinessDirectors(ctx context.Context, userID uuid.UUID) ([]BusinessDirector, error)
	ListCaasWithdrawalsByUser(ctx context.Context, arg ListCaasWithdrawalsByUserParams) ([]CaasWithdrawal, error)
	ListCryptoTransactionsByUser(ctx context.Context, arg ListCryptoTransactionsByUserParams) ([]CryptoTransaction, error)
	ListMerchantStaff(ctx context.Context, businessUserID uuid.UUID) ([]MerchantStaff, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPlatformLimits(ctx context.Context) ([]PlatformLimit, error)
	ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]ListRecentActivityRow, error)
	ListStaffMembers(ctx context.Context, arg ListStaffMembersParams) ([]AdminStaff, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkDirectorsComplete(ctx context.Context, userID uuid.UUID) error
	MarkDocumentsComplete(ctx context.Context, userID uuid.UUID) error
	MarkEmailOTPUsed(ctx context.Context, id uuid.UUID) error
	MarkFXQuoteUsed(ctx context.Context, quoteID string) error
	// ─── hub2_payments CaaS funding ───────────────────────────────────────────────
	MarkHub2PaymentCaasFunded(ctx context.Context, id uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	MarkOTPUsed(ctx context.Context, id uuid.UUID) error
	RevokeAllOtherSessions(ctx context.Context, arg RevokeAllOtherSessionsParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeUserSessionByID(ctx context.Context, arg RevokeUserSessionByIDParams) error
	SaveBusinessProfile(ctx context.Context, arg SaveBusinessProfileParams) (BusinessProfile, error)
	// Flags (or clears) admin manual control over a user's KYC decision.
	SetKycManualOverride(ctx context.Context, arg SetKycManualOverrideParams) error
	// Records the KYC provider's latest automated decision (does not touch the
	// final kyc_status).
	SetKycProviderStatus(ctx context.Context, arg SetKycProviderStatusParams) error
	SetReferralCode(ctx context.Context, arg SetReferralCodeParams) error
	SetUserAccountType(ctx context.Context, arg SetUserAccountTypeParams) (SetUserAccountTypeRow, error)
	SetUserBVN(ctx context.Context, arg SetUserBVNParams) (User, error)
	UpdateCaasWalletPhone(ctx context.Context, arg UpdateCaasWalletPhoneParams) error
	UpdateCaasWithdrawalStatus(ctx context.Context, arg UpdateCaasWithdrawalStatusParams) (CaasWithdrawal, error)
	UpdateCryptoTransactionCaasResult(ctx context.Context, arg UpdateCryptoTransactionCaasResultParams) (CryptoTransaction, error)
	UpdateCryptoTransactionStatus(ctx context.Context, arg UpdateCryptoTransactionStatusParams) (CryptoTransaction, error)
	UpdateHub2PaymentStatus(ctx context.Context, arg UpdateHub2PaymentStatusParams) (Hub2Payment, error)
	UpdateKYCDocumentStatus(ctx context.Context, arg UpdateKYCDocumentStatusParams) (KycDocument, error)
	UpdateMerchantStaffRole(ctx context.Context, arg UpdateMerchantStaffRoleParams) error
	UpdateMetamapVerificationStatus(ctx context.Context, arg UpdateMetamapVerificationStatusParams) (MetamapVerification, error)
	UpdateNilosAccountDetails(ctx context.Context, arg UpdateNilosAccountDetailsParams) error
	UpdateSessionLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateSessionRefreshTokenHash(ctx context.Context, arg UpdateSessionRefreshTokenHashParams) error
	UpdateStaffLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateStaffMember(ctx context.Context, arg UpdateStaffMemberParams) (AdminStaff, error)
	UpdateSumsubVerificationStatus(ctx context.Context, arg UpdateSumsubVerificationStatusParams) (SumsubVerification, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateUserEmailVerified(ctx context.Context, id uuid.UUID) error
	UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) (User, error)
	UpdateUserPinHash(ctx context.Context, arg UpdateUserPinHashParams) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertPlatformLimit(ctx context.Context, arg UpsertPlatformLimitParams) (PlatformLimit, error)
	UpsertUserLimitOverride(ctx context.Context, arg UpsertUserLimitOverrideParams) (UserLimitOverride, error)
}

var _ Querier = (*Queries)(nil)
