// Code generated by sqlc. DO NOT EDIT.
// Run `make sqlc` to regenerate after changing queries or schema.
package db

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
)

var errNotImplemented = errors.New("sqlc: not generated — run make sqlc")

// ── Param structs ─────────────────────────────────────────────────────────────

type CreateOTPParams struct {
	PhoneNumber string
	Code        string
	ExpiresAt   time.Time
}

type GetValidOTPParams struct {
	PhoneNumber string
	Code        string
}

type CreateUserParams struct {
	PhoneNumber  string
	Email        *string
	FirstName    string
	LastName     string
	PinHash      *string // nil for social-auth users
	Role         string  // default "user"
	AuthProvider string  // "phone" | "google"
	GoogleSub    *string
}

type CreateGoogleUserParams struct {
	Email        string
	FirstName    string
	LastName     string
	GoogleSub    string
	Role         string
	AuthProvider string
}

type UpdateUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

type RecordKycAdminActionParams struct {
	UserID  uuid.UUID
	AdminID uuid.UUID
	Action  string
	Reason  *string
}

type UpdateUserKYCStatusParams struct {
	ID        uuid.UUID
	KycStatus string
}

type CreateAccountParams struct {
	UserID        uuid.UUID
	Currency      string
	AccountNumber string
}

type GetAccountByUserAndCurrencyParams struct {
	UserID   uuid.UUID
	Currency string
}

type ListTransactionsByAccountParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

type CreateWaasWalletParams struct {
	UserID       uuid.UUID
	WaasWalletID string
	Network      string
	Address      string
	IsDefault    bool
}

type GetWaasWalletByNetworkParams struct {
	UserID  uuid.UUID
	Network string
}

type CreateCaasWalletParams struct {
	UserID             uuid.UUID
	CaasWalletID       string
	AbstractionAddress string
}

// Note: Amount is string here to match service code; real sqlc generates pgtype.Numeric.
// Fix crypto_service.go to use pgtype.Numeric after running make sqlc.
type CreateCryptoTransactionParams struct {
	Reference       string
	SenderUserID    uuid.UUID
	ReceiverPhone   string
	ReceiverUserID  *uuid.UUID
	Token           string
	Amount          string
	TxHash          *string
	Status          string
	QuoteID         *string
	CaasTransferID  *string
	IdempotencyKey  *string
	LocalFiatAmount *string
	LocalCurrency   *string
}

type ListCryptoTransactionsByUserParams struct {
	SenderUserID   uuid.UUID
	ReceiverUserID *uuid.UUID
	Limit          int32
	Offset         int32
}

type UpdateCryptoTransactionStatusParams struct {
	ID     uuid.UUID
	Status string
	TxHash *string
}

type CreateHub2PaymentParams struct {
	Hub2Reference string
	PaymentMethod string
	Operator      *string
	PhoneNumber   *string
}

type UpdateHub2PaymentStatusParams struct {
	ID         uuid.UUID
	Status     string
	Hub2Status *string
}

// ── CaaS new types ────────────────────────────────────────────────────────────

type CreateCaasWalletFullParams struct {
	UserID             uuid.UUID
	CaasWalletID       string
	BlindIndex         *string
	AbstractionAddress string
}

type UpdateCaasWalletPhoneParams struct {
	UserID     uuid.UUID
	BlindIndex *string
}

type CreateFXQuoteParams struct {
	UserID        uuid.UUID
	QuoteID       string
	FiatAmount    string
	LocalCurrency string
	TargetToken   string
	Rate          string
	ExpiresAt     time.Time
}

type CreateCaasWithdrawalParams struct {
	UserID           uuid.UUID
	CaasWithdrawalID string
	Phone            string
	Amount           string
	Token            string
	PayoutMobile     string
	PayoutNetwork    string
	IdempotencyKey   string
}

type UpdateCaasWithdrawalStatusParams struct {
	ID     uuid.UUID
	Status string
}

type ListCaasWithdrawalsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type UpdateCryptoTransactionCaasResultParams struct {
	ID             uuid.UUID
	Status         string
	TxHash         *string
	CaasTransferID *string
}

type CreateKYCDocumentParams struct {
	UserID  uuid.UUID
	DocType string
	DocURL  string
}

// ── OTP ───────────────────────────────────────────────────────────────────────

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error) {
	return Otp{}, errNotImplemented
}

func (q *Queries) GetValidOTP(ctx context.Context, arg GetValidOTPParams) (Otp, error) {
	return Otp{}, errNotImplemented
}

func (q *Queries) MarkOTPUsed(ctx context.Context, id uuid.UUID) error {
	return errNotImplemented
}

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	return errNotImplemented
}

// ── Users ─────────────────────────────────────────────────────────────────────

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	return User{}, errNotImplemented
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	return User{}, errNotImplemented
}

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	return User{}, errNotImplemented
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	return User{}, errNotImplemented
}

func (q *Queries) UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) (User, error) {
	return User{}, errNotImplemented
}

func (q *Queries) UpdateUserPinHash(ctx context.Context, id uuid.UUID, pinHash string) error {
	return errNotImplemented
}

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	return errNotImplemented
}

// ── Accounts ──────────────────────────────────────────────────────────────────

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	return Account{}, errNotImplemented
}

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	return Account{}, errNotImplemented
}

func (q *Queries) GetAccountByUserAndCurrency(ctx context.Context, arg GetAccountByUserAndCurrencyParams) (Account, error) {
	return Account{}, errNotImplemented
}

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	return nil, errNotImplemented
}

func (q *Queries) GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error) {
	return Account{}, errNotImplemented
}

func (q *Queries) CreditAccount(ctx context.Context, id uuid.UUID, amount string) (Account, error) {
	return Account{}, errNotImplemented
}

func (q *Queries) DebitAccount(ctx context.Context, id uuid.UUID, amount string) (Account, error) {
	return Account{}, errNotImplemented
}

func (q *Queries) FreezeAccount(ctx context.Context, id uuid.UUID) error {
	return errNotImplemented
}

// ── Transactions ──────────────────────────────────────────────────────────────

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	return Transaction{}, errNotImplemented
}

func (q *Queries) GetTransactionByReference(ctx context.Context, ref string) (Transaction, error) {
	return Transaction{}, errNotImplemented
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	return nil, errNotImplemented
}

func (q *Queries) CountTransactionsByAccount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	return 0, errNotImplemented
}

// ── WaaS Wallets ──────────────────────────────────────────────────────────────

func (q *Queries) CreateWaasWallet(ctx context.Context, arg CreateWaasWalletParams) (WaasWallet, error) {
	return WaasWallet{}, errNotImplemented
}

func (q *Queries) GetWaasWalletsByUserID(ctx context.Context, userID uuid.UUID) ([]WaasWallet, error) {
	return nil, errNotImplemented
}

func (q *Queries) GetWaasWalletByNetwork(ctx context.Context, arg GetWaasWalletByNetworkParams) (WaasWallet, error) {
	return WaasWallet{}, errNotImplemented
}

func (q *Queries) GetDefaultWaasWallet(ctx context.Context, userID uuid.UUID) (WaasWallet, error) {
	return WaasWallet{}, errNotImplemented
}

// ── CaaS Wallets ──────────────────────────────────────────────────────────────

func (q *Queries) CreateCaasWallet(ctx context.Context, arg CreateCaasWalletParams) (CaasWallet, error) {
	return CaasWallet{}, errNotImplemented
}

func (q *Queries) GetCaasWalletByUserID(ctx context.Context, userID uuid.UUID) (CaasWallet, error) {
	return CaasWallet{}, errNotImplemented
}

func (q *Queries) GetCaasWalletByAddress(ctx context.Context, address string) (CaasWallet, error) {
	return CaasWallet{}, errNotImplemented
}

// ── Crypto Transactions ───────────────────────────────────────────────────────

func (q *Queries) CreateCryptoTransaction(ctx context.Context, arg CreateCryptoTransactionParams) (CryptoTransaction, error) {
	return CryptoTransaction{}, errNotImplemented
}

func (q *Queries) GetCryptoTransactionByID(ctx context.Context, id uuid.UUID) (CryptoTransaction, error) {
	return CryptoTransaction{}, errNotImplemented
}

func (q *Queries) GetCryptoTransactionByReference(ctx context.Context, ref string) (CryptoTransaction, error) {
	return CryptoTransaction{}, errNotImplemented
}

func (q *Queries) ListCryptoTransactionsByUser(ctx context.Context, arg ListCryptoTransactionsByUserParams) ([]CryptoTransaction, error) {
	return nil, errNotImplemented
}

func (q *Queries) UpdateCryptoTransactionStatus(ctx context.Context, arg UpdateCryptoTransactionStatusParams) (CryptoTransaction, error) {
	return CryptoTransaction{}, errNotImplemented
}

// ── Hub2 Payments ─────────────────────────────────────────────────────────────

func (q *Queries) CreateHub2Payment(ctx context.Context, arg CreateHub2PaymentParams) (Hub2Payment, error) {
	return Hub2Payment{}, errNotImplemented
}

func (q *Queries) GetHub2PaymentByReference(ctx context.Context, ref string) (Hub2Payment, error) {
	return Hub2Payment{}, errNotImplemented
}

func (q *Queries) UpdateHub2PaymentStatus(ctx context.Context, arg UpdateHub2PaymentStatusParams) (Hub2Payment, error) {
	return Hub2Payment{}, errNotImplemented
}

// ── KYC Documents ─────────────────────────────────────────────────────────────

func (q *Queries) CreateKYCDocument(ctx context.Context, arg CreateKYCDocumentParams) (KycDocument, error) {
	return KycDocument{}, errNotImplemented
}

func (q *Queries) GetKYCDocumentsByUserID(ctx context.Context, userID uuid.UUID) ([]KycDocument, error) {
	return nil, errNotImplemented
}

func (q *Queries) UpdateKYCDocumentStatus(ctx context.Context, id uuid.UUID, status, rejectionReason string) (KycDocument, error) {
	return KycDocument{}, errNotImplemented
}

// ── CaaS Wallets (extended) ───────────────────────────────────────────────────

func (q *Queries) CreateCaasWalletFull(ctx context.Context, arg CreateCaasWalletFullParams) (CaasWallet, error) {
	return CaasWallet{}, errNotImplemented
}

func (q *Queries) GetCaasWalletByBlindIndex(ctx context.Context, blindIndex string) (CaasWallet, error) {
	return CaasWallet{}, errNotImplemented
}

func (q *Queries) UpdateCaasWalletPhone(ctx context.Context, arg UpdateCaasWalletPhoneParams) error {
	return errNotImplemented
}

// ── FX Quotes ─────────────────────────────────────────────────────────────────

func (q *Queries) CreateFXQuote(ctx context.Context, arg CreateFXQuoteParams) (FxQuote, error) {
	return FxQuote{}, errNotImplemented
}

func (q *Queries) GetFXQuoteByQuoteID(ctx context.Context, quoteID string) (FxQuote, error) {
	return FxQuote{}, errNotImplemented
}

func (q *Queries) MarkFXQuoteUsed(ctx context.Context, quoteID string) error {
	return errNotImplemented
}

func (q *Queries) DeleteExpiredFXQuotes(ctx context.Context) error {
	return errNotImplemented
}

// ── CaaS Withdrawals ──────────────────────────────────────────────────────────

func (q *Queries) CreateCaasWithdrawal(ctx context.Context, arg CreateCaasWithdrawalParams) (CaasWithdrawal, error) {
	return CaasWithdrawal{}, errNotImplemented
}

func (q *Queries) GetCaasWithdrawalByID(ctx context.Context, id uuid.UUID) (CaasWithdrawal, error) {
	return CaasWithdrawal{}, errNotImplemented
}

func (q *Queries) GetCaasWithdrawalByIdempotencyKey(ctx context.Context, key string) (CaasWithdrawal, error) {
	return CaasWithdrawal{}, errNotImplemented
}

func (q *Queries) GetCaasWithdrawalByCaasID(ctx context.Context, caasID string) (CaasWithdrawal, error) {
	return CaasWithdrawal{}, errNotImplemented
}

func (q *Queries) UpdateCaasWithdrawalStatus(ctx context.Context, arg UpdateCaasWithdrawalStatusParams) (CaasWithdrawal, error) {
	return CaasWithdrawal{}, errNotImplemented
}

func (q *Queries) ListCaasWithdrawalsByUser(ctx context.Context, arg ListCaasWithdrawalsByUserParams) ([]CaasWithdrawal, error) {
	return nil, errNotImplemented
}

// ── Crypto Transaction CaaS extras ────────────────────────────────────────────

func (q *Queries) GetCryptoTransactionByIdempotencyKey(ctx context.Context, key *string) (CryptoTransaction, error) {
	return CryptoTransaction{}, errNotImplemented
}

func (q *Queries) UpdateCryptoTransactionCaasResult(ctx context.Context, arg UpdateCryptoTransactionCaasResultParams) (CryptoTransaction, error) {
	return CryptoTransaction{}, errNotImplemented
}

// ── Hub2 CaaS funding ─────────────────────────────────────────────────────────

func (q *Queries) MarkHub2PaymentCaasFunded(ctx context.Context, id uuid.UUID) error {
	return errNotImplemented
}

func (q *Queries) GetHub2PaymentByReferenceForFunding(ctx context.Context, ref string) (Hub2Payment, error) {
	return Hub2Payment{}, errNotImplemented
}

// ── Sessions ──────────────────────────────────────────────────────────────────

type CreateUserSessionParams struct {
	UserID           uuid.UUID
	RefreshTokenHash string
	DeviceName       *string
	DeviceIP         *string
	DeviceUA         *string
	ExpiresAt        time.Time
}

type RevokeAllOtherSessionsParams struct {
	UserID    uuid.UUID
	ExcludeID uuid.UUID
}

type UpdateSessionRefreshTokenHashParams struct {
	ID               uuid.UUID
	RefreshTokenHash string
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	return UserSession{}, errNotImplemented
}

func (q *Queries) GetUserSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error) {
	return UserSession{}, errNotImplemented
}

func (q *Queries) GetUserSessionByRefreshTokenHash(ctx context.Context, hash string) (UserSession, error) {
	return UserSession{}, errNotImplemented
}

func (q *Queries) ListActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]UserSession, error) {
	return nil, errNotImplemented
}

func (q *Queries) RevokeUserSessionByID(ctx context.Context, id, userID uuid.UUID) error {
	return errNotImplemented
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	return errNotImplemented
}

func (q *Queries) RevokeAllOtherSessions(ctx context.Context, arg RevokeAllOtherSessionsParams) error {
	return errNotImplemented
}

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, id uuid.UUID) error {
	return errNotImplemented
}

func (q *Queries) UpdateSessionRefreshTokenHash(ctx context.Context, arg UpdateSessionRefreshTokenHashParams) error {
	return errNotImplemented
}

// ── Email OTPs ────────────────────────────────────────────────────────────────

type CreateEmailOTPParams struct {
	Email     string
	Code      string
	Purpose   string
	ExpiresAt time.Time
}

type GetValidEmailOTPParams struct {
	Email   string
	Code    string
	Purpose string
}

func (q *Queries) CreateEmailOTP(ctx context.Context, arg CreateEmailOTPParams) (EmailOtp, error) {
	return EmailOtp{}, errNotImplemented
}

func (q *Queries) GetValidEmailOTP(ctx context.Context, arg GetValidEmailOTPParams) (EmailOtp, error) {
	return EmailOtp{}, errNotImplemented
}

func (q *Queries) MarkEmailOTPUsed(ctx context.Context, id uuid.UUID) error {
	return errNotImplemented
}

func (q *Queries) DeleteExpiredEmailOTPs(ctx context.Context) error {
	return errNotImplemented
}

// ── MetaMap ───────────────────────────────────────────────────────────────────

type CreateMetamapVerificationParams struct {
	UserID         uuid.UUID
	ApplicantID    string
	FlowID         string
	IdentityAccess string
}

type UpdateMetamapVerificationStatusParams struct {
	ApplicantID string
	Status      string
	ResultData  []byte
}

func (q *Queries) CreateMetamapVerification(ctx context.Context, arg CreateMetamapVerificationParams) (MetamapVerification, error) {
	return MetamapVerification{}, errNotImplemented
}

func (q *Queries) GetMetamapVerificationByUserID(ctx context.Context, userID uuid.UUID) (MetamapVerification, error) {
	return MetamapVerification{}, errNotImplemented
}

func (q *Queries) GetMetamapVerificationByApplicantID(ctx context.Context, applicantID string) (MetamapVerification, error) {
	return MetamapVerification{}, errNotImplemented
}

func (q *Queries) UpdateMetamapVerificationStatus(ctx context.Context, arg UpdateMetamapVerificationStatusParams) (MetamapVerification, error) {
	return MetamapVerification{}, errNotImplemented
}

// ── User profile ──────────────────────────────────────────────────────────────

type UpdateUserProfileParams struct {
	ID          uuid.UUID
	FirstName   string
	LastName    string
	Bio         *string
	AvatarURL   *string
	DateOfBirth *string
	Nationality *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	return User{}, errNotImplemented
}

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	return errNotImplemented
}

func (q *Queries) GetUserFullByID(ctx context.Context, id uuid.UUID) (UserFull, error) {
	return UserFull{}, errNotImplemented
}

// ── Social Auth ───────────────────────────────────────────────────────────────

func (q *Queries) GetUserByGoogleSub(ctx context.Context, sub string) (User, error) {
	return User{}, errNotImplemented
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	return User{}, errNotImplemented
}

// ── Admin / KYC management ────────────────────────────────────────────────────

func (q *Queries) ListUsersAwaitingKYCReview(ctx context.Context) ([]UserFull, error) {
	return nil, errNotImplemented
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	return User{}, errNotImplemented
}

func (q *Queries) RecordKycAdminAction(ctx context.Context, arg RecordKycAdminActionParams) (KycAdminAction, error) {
	return KycAdminAction{}, errNotImplemented
}

// ── Nilos / Card (migration 000005) ───────────────────────────────────────────

type UpdateAccountNilosParams struct {
	ID              uuid.UUID
	NilosAccountID  string
	NilosCustomerID string
	IBAN            *string
	BIC             *string
}

type CreateVirtualCardParams struct {
	UserID      uuid.UUID
	CardName    string
	LastFour    string
	Currency    string
	CardNetwork string
}

type GetFXRateParams struct {
	BaseCurrency  string
	QuoteCurrency string
}

type UpsertFXRateParams struct {
	BaseCurrency  string
	QuoteCurrency string
	Rate          string
	Source        string
}

func (q *Queries) UpdateAccountNilos(ctx context.Context, arg UpdateAccountNilosParams) error {
	return errNotImplemented
}

func (q *Queries) GetAccountWithNilos(ctx context.Context, id uuid.UUID) (AccountWithNilos, error) {
	return AccountWithNilos{}, errNotImplemented
}

func (q *Queries) GetAccountsByUserIDWithNilos(ctx context.Context, userID uuid.UUID) ([]AccountWithNilos, error) {
	return nil, errNotImplemented
}

func (q *Queries) CreateVirtualCard(ctx context.Context, arg CreateVirtualCardParams) (VirtualCard, error) {
	return VirtualCard{}, errNotImplemented
}

func (q *Queries) GetActiveVirtualCard(ctx context.Context, userID uuid.UUID) (VirtualCard, error) {
	return VirtualCard{}, errNotImplemented
}

func (q *Queries) GetFXRate(ctx context.Context, arg GetFXRateParams) (FXRate, error) {
	return FXRate{}, errNotImplemented
}

func (q *Queries) GetAllFXRates(ctx context.Context) ([]FXRate, error) {
	return nil, errNotImplemented
}

func (q *Queries) UpsertFXRate(ctx context.Context, arg UpsertFXRateParams) error {
	return errNotImplemented
}

// ── Dashboard helpers ──────────────────────────────────────────────────────────

type MonthlyTransactionSummary struct {
	IncomeUSD   float64 `json:"income_usd"`
	SpendingUSD float64 `json:"spending_usd"`
	TxCount     int64   `json:"tx_count"`
}

type RecentContact struct {
	Name          string `json:"name"`
	PhoneNumber   string `json:"phone_number"`
	LastContactAt time.Time `json:"last_contact_at"`
}

func (q *Queries) GetMonthlyTransactionSummary(ctx context.Context, userID uuid.UUID) (MonthlyTransactionSummary, error) {
	return MonthlyTransactionSummary{}, errNotImplemented
}

func (q *Queries) GetRecentContacts(ctx context.Context, userID uuid.UUID, limit int) ([]RecentContact, error) {
	return nil, errNotImplemented
}

// ListRecentActivityParams for unified activity feed
type ListRecentActivityParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type ActivityItem struct {
	ID          string    `json:"id"`
	Source      string    `json:"source"`      // "fiat" | "crypto" | "caas"
	Type        string    `json:"type"`        // "credit" | "debit" | "exchange"
	Description string    `json:"description"` // "Received BTC", "Sent USD", etc.
	Asset       string    `json:"asset"`       // "BTC", "USD", "USDC", "ETH"
	Amount      string    `json:"amount"`      // absolute decimal string
	AmountSign  string    `json:"amount_sign"` // "+" | "-"
	Status      string    `json:"status"`      // "completed" | "pending" | "failed"
	CounterName string    `json:"counter_name,omitempty"`
	DaysAgo     int       `json:"days_ago"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]ActivityItem, error) {
	return nil, errNotImplemented
}

// ─── Notification queries ──────────────────────────────────────────────────────

type CreateNotificationParams struct {
	UserID   uuid.UUID       `json:"user_id"`
	Type     string          `json:"type"`
	Title    string          `json:"title"`
	Body     string          `json:"body"`
	Metadata json.RawMessage `json:"metadata"`
}

type ListNotificationsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	UnreadOnly bool      `json:"unread_only"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	return Notification{}, errNotImplemented
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	return nil, errNotImplemented
}

func (q *Queries) CountNotifications(ctx context.Context, userID uuid.UUID, unreadOnly bool) (int64, error) {
	return 0, errNotImplemented
}

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	return 0, errNotImplemented
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	return Notification{}, errNotImplemented
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	return errNotImplemented
}

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	return Notification{}, errNotImplemented
}

// ─── Migration 000007: account balance management ─────────────────────────────

type DeductAvailableBalanceParams struct {
	ID     uuid.UUID
	Amount string // decimal string e.g. "100.00"
}

type RestoreAvailableBalanceParams struct {
	ID     uuid.UUID
	Amount string
}

type DeductBalanceParams struct {
	ID     uuid.UUID
	Amount string
}

// DeductAvailableBalance holds funds for a pending withdrawal (reduces available, not settled).
func (q *Queries) DeductAvailableBalance(ctx context.Context, arg DeductAvailableBalanceParams) error {
	return errNotImplemented
}

// RestoreAvailableBalance releases funds held for a failed or cancelled withdrawal.
func (q *Queries) RestoreAvailableBalance(ctx context.Context, arg RestoreAvailableBalanceParams) error {
	return errNotImplemented
}

// DeductBalance settles a completed withdrawal (reduces both available and settled balance).
func (q *Queries) DeductBalance(ctx context.Context, arg DeductBalanceParams) error {
	return errNotImplemented
}

// GetAccountWithNilosByUserAndCurrency returns the full account row including Nilos fields.
func (q *Queries) GetAccountWithNilosByUserAndCurrency(ctx context.Context, userID uuid.UUID, currency string) (AccountWithNilos, error) {
	return AccountWithNilos{}, errNotImplemented
}

// ─── Migration 000007: business FX rates ─────────────────────────────────────

type UpsertBusinessFxRateParams struct {
	SourceCurrency string
	TargetCurrency string
	Rate           string // decimal e.g. "595.00"
	FeePercent     string // decimal e.g. "0.0100"
	FlatFee        string // decimal e.g. "0.00"
	SetBy          *uuid.UUID
}

type GetBusinessFxRateParams struct {
	SourceCurrency string
	TargetCurrency string
}

// UpsertBusinessFxRate creates or updates the conversion rate for a currency pair.
func (q *Queries) UpsertBusinessFxRate(ctx context.Context, arg UpsertBusinessFxRateParams) (BusinessFxRate, error) {
	return BusinessFxRate{}, errNotImplemented
}

// GetBusinessFxRate returns the active rate for a currency pair, or an error if not found.
func (q *Queries) GetBusinessFxRate(ctx context.Context, arg GetBusinessFxRateParams) (BusinessFxRate, error) {
	return BusinessFxRate{}, errNotImplemented
}

// ListBusinessFxRates returns all configured rates.
func (q *Queries) ListBusinessFxRates(ctx context.Context) ([]BusinessFxRate, error) {
	return nil, errNotImplemented
}

// ─── Migration 000007: beneficiaries ─────────────────────────────────────────

type CreateBeneficiaryParams struct {
	UserID              uuid.UUID
	Label               string
	Type                string // "mobile_money" | "bank"
	DestinationCurrency string
	Country             string
	PhoneNumber         *string
	Operator            *string
	BankName            *string
	AccountNumber       *string
	IBAN                *string
	SwiftCode           *string
	SortCode            *string
	RoutingNumber       *string
}

type GetBeneficiaryByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CreateBeneficiary(ctx context.Context, arg CreateBeneficiaryParams) (Beneficiary, error) {
	return Beneficiary{}, errNotImplemented
}

func (q *Queries) ListBeneficiaries(ctx context.Context, userID uuid.UUID) ([]Beneficiary, error) {
	return nil, errNotImplemented
}

func (q *Queries) GetBeneficiaryByID(ctx context.Context, arg GetBeneficiaryByIDParams) (Beneficiary, error) {
	return Beneficiary{}, errNotImplemented
}

func (q *Queries) UpdateBeneficiaryNilosRecipient(ctx context.Context, id uuid.UUID, nilosRecipientID string) error {
	return errNotImplemented
}

func (q *Queries) DeleteBeneficiary(ctx context.Context, id, userID uuid.UUID) error {
	return errNotImplemented
}

// ─── Migration 000007: fiat withdrawals ──────────────────────────────────────

type CreateFiatWithdrawalParams struct {
	UserID              uuid.UUID
	SourceCurrency      string
	SourceAmount        string
	Fee                 string
	FeeCurrency         string
	FxRate              *string    // nil if same currency
	DestinationType     string
	DestinationCurrency string
	DestinationAmount   string
	DestinationCountry  string
	RecipientName       string
	PhoneNumber         *string
	Operator            *string
	BankName            *string
	AccountNumber       *string
	IBAN                *string
	SwiftCode           *string
	SortCode            *string
	RoutingNumber       *string
	Reference           string
	BeneficiaryID       *uuid.UUID
}

type GetFiatWithdrawalByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type ListFiatWithdrawalsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type UpdateFiatWithdrawalStatusParams struct {
	ID            uuid.UUID
	Status        string
	FailureReason *string
}

type UpdateFiatWithdrawalHub2RefParams struct {
	ID            uuid.UUID
	Hub2Reference string
	Status        string
}

type UpdateFiatWithdrawalNilosRefParams struct {
	ID               uuid.UUID
	NilosPayoutID    string
	NilosRecipientID string
	Status           string
}

func (q *Queries) CreateFiatWithdrawal(ctx context.Context, arg CreateFiatWithdrawalParams) (FiatWithdrawal, error) {
	return FiatWithdrawal{}, errNotImplemented
}

func (q *Queries) GetFiatWithdrawalByID(ctx context.Context, arg GetFiatWithdrawalByIDParams) (FiatWithdrawal, error) {
	return FiatWithdrawal{}, errNotImplemented
}

func (q *Queries) GetFiatWithdrawalByHub2Ref(ctx context.Context, hub2Ref string) (FiatWithdrawal, error) {
	return FiatWithdrawal{}, errNotImplemented
}

func (q *Queries) ListFiatWithdrawals(ctx context.Context, arg ListFiatWithdrawalsParams) ([]FiatWithdrawal, error) {
	return nil, errNotImplemented
}

func (q *Queries) CountFiatWithdrawals(ctx context.Context, userID uuid.UUID) (int64, error) {
	return 0, errNotImplemented
}

func (q *Queries) UpdateFiatWithdrawalStatus(ctx context.Context, arg UpdateFiatWithdrawalStatusParams) (FiatWithdrawal, error) {
	return FiatWithdrawal{}, errNotImplemented
}

func (q *Queries) UpdateFiatWithdrawalHub2Ref(ctx context.Context, arg UpdateFiatWithdrawalHub2RefParams) (FiatWithdrawal, error) {
	return FiatWithdrawal{}, errNotImplemented
}

func (q *Queries) UpdateFiatWithdrawalNilosRef(ctx context.Context, arg UpdateFiatWithdrawalNilosRefParams) (FiatWithdrawal, error) {
	return FiatWithdrawal{}, errNotImplemented
}

// ─── Migration 000008: security (2FA + PIN + biometrics) ─────────────────────

type SetTOTPSecretParams struct {
	ID         uuid.UUID
	TOTPSecret *string // nil to clear
}

type SetTOTPEnabledParams struct {
	ID          uuid.UUID
	TOTPEnabled bool
	TOTPSecret  *string // set when enabling, nil to clear when disabling
}

// GetUserSecurityByID returns the totp_secret + totp_enabled fields for a user.
func (q *Queries) GetUserSecurity(ctx context.Context, id uuid.UUID) (struct {
	TOTPSecret  *string
	TOTPEnabled bool
}, error) {
	return struct {
		TOTPSecret  *string
		TOTPEnabled bool
	}{}, errNotImplemented
}

func (q *Queries) SetTOTPEnabled(ctx context.Context, arg SetTOTPEnabledParams) error {
	return errNotImplemented
}

func (q *Queries) SetBiometricsEnabled(ctx context.Context, userID uuid.UUID, enabled bool) error {
	return errNotImplemented
}

// ChangePIN updates the stored PIN hash for a user (requires old hash to have been
// verified by the caller before invoking this).
func (q *Queries) ChangePIN(ctx context.Context, id uuid.UUID, newPinHash string) error {
	return errNotImplemented
}

// ─── Migration 000008: user preferences ──────────────────────────────────────

type UpsertUserPreferencesParams struct {
	UserID            uuid.UUID
	Language          string
	DarkMode          string
	BiometricsEnabled bool
}

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreferences, error) {
	return UserPreferences{}, errNotImplemented
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreferences, error) {
	return UserPreferences{}, errNotImplemented
}

// ─── Migration 000008: support tickets ───────────────────────────────────────

type CreateSupportTicketParams struct {
	UserID    uuid.UUID
	Reference string
	Subject   string
	Category  string
}

type CreateSupportMessageParams struct {
	TicketID   uuid.UUID
	SenderType string
	SenderID   *uuid.UUID
	Body       string
}

type ListSupportTicketsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetSupportTicketParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CreateSupportTicket(ctx context.Context, arg CreateSupportTicketParams) (SupportTicket, error) {
	return SupportTicket{}, errNotImplemented
}

func (q *Queries) GetSupportTicket(ctx context.Context, arg GetSupportTicketParams) (SupportTicket, error) {
	return SupportTicket{}, errNotImplemented
}

func (q *Queries) ListSupportTickets(ctx context.Context, arg ListSupportTicketsParams) ([]SupportTicket, error) {
	return nil, errNotImplemented
}

func (q *Queries) CountSupportTickets(ctx context.Context, userID uuid.UUID) (int64, error) {
	return 0, errNotImplemented
}

func (q *Queries) CreateSupportMessage(ctx context.Context, arg CreateSupportMessageParams) (SupportMessage, error) {
	return SupportMessage{}, errNotImplemented
}

func (q *Queries) ListSupportMessages(ctx context.Context, ticketID uuid.UUID) ([]SupportMessage, error) {
	return nil, errNotImplemented
}

func (q *Queries) UpdateSupportTicketStatus(ctx context.Context, id uuid.UUID, status string) (SupportTicket, error) {
	return SupportTicket{}, errNotImplemented
}

// ─── Migration 000008: FAQs ───────────────────────────────────────────────────

func (q *Queries) ListFAQs(ctx context.Context, category string) ([]FAQ, error) {
	return nil, errNotImplemented
}

func (q *Queries) GetFAQ(ctx context.Context, id uuid.UUID) (FAQ, error) {
	return FAQ{}, errNotImplemented
}

// Admin FAQ management
type UpsertFAQParams struct {
	ID        *uuid.UUID
	Question  string
	Answer    string
	Category  string
	SortOrder int
}

func (q *Queries) UpsertFAQ(ctx context.Context, arg UpsertFAQParams) (FAQ, error) {
	return FAQ{}, errNotImplemented
}

func (q *Queries) DeleteFAQ(ctx context.Context, id uuid.UUID) error {
	return errNotImplemented
}
