// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referrals.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPointsRecord = `-- name: CreatePointsRecord :one
INSERT INTO points_ledger (user_id, amount, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, amount, description, created_at
`

type CreatePointsRecordParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Amount      int32     `json:"amount"`
	Description string    `json:"description"`
}

func (q *Queries) CreatePointsRecord(ctx context.Context, arg CreatePointsRecordParams) (PointsLedger, error) {
	row := q.db.QueryRow(ctx, createPointsRecord, arg.UserID, arg.Amount, arg.Description)
	var i PointsLedger
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getPointsBalance = `-- name: GetPointsBalance :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM points_ledger WHERE user_id = $1
`

func (q *Queries) GetPointsBalance(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPointsBalance, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPointsHistory = `-- name: GetPointsHistory :many
SELECT id, user_id, amount, description, created_at FROM points_ledger
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetPointsHistoryParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetPointsHistory(ctx context.Context, arg GetPointsHistoryParams) ([]PointsLedger, error) {
	rows, err := q.db.Query(ctx, getPointsHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointsLedger{}
	for rows.Next() {
		var i PointsLedger
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferralsCount = `-- name: GetReferralsCount :one
SELECT COUNT(*)::bigint FROM users WHERE referred_by = $1
`

func (q *Queries) GetReferralsCount(ctx context.Context, referredBy *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getReferralsCount, referredBy)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getReferralsList = `-- name: GetReferralsList :many
SELECT id, phone_number, email, first_name, last_name, created_at FROM users
WHERE referred_by = $1
ORDER BY created_at DESC
`

type GetReferralsListRow struct {
	ID          uuid.UUID `json:"id"`
	PhoneNumber string    `json:"phone_number"`
	Email       *string   `json:"email"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetReferralsList(ctx context.Context, referredBy *uuid.UUID) ([]GetReferralsListRow, error) {
	rows, err := q.db.Query(ctx, getReferralsList, referredBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReferralsListRow{}
	for rows.Next() {
		var i GetReferralsListRow
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByReferralCode = `-- name: GetUserByReferralCode :one
SELECT id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by FROM users WHERE referral_code = $1 LIMIT 1
`

func (q *Queries) GetUserByReferralCode(ctx context.Context, referralCode *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByReferralCode, referralCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
	)
	return i, err
}

const setReferralCode = `-- name: SetReferralCode :exec
UPDATE users SET referral_code = $2, referred_by = COALESCE($3, referred_by)
WHERE id = $1
`

type SetReferralCodeParams struct {
	ID           uuid.UUID  `json:"id"`
	ReferralCode *string    `json:"referral_code"`
	ReferredBy   *uuid.UUID `json:"referred_by"`
}

func (q *Queries) SetReferralCode(ctx context.Context, arg SetReferralCodeParams) error {
	_, err := q.db.Exec(ctx, setReferralCode, arg.ID, arg.ReferralCode, arg.ReferredBy)
	return err
}
