// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions
    (user_id, refresh_token_hash, device_name, device_ip, device_ua, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, refresh_token_hash, device_name, device_ip, device_ua, is_active, last_used_at, created_at, expires_at
`

type CreateUserSessionParams struct {
	UserID           uuid.UUID `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	DeviceName       *string   `json:"device_name"`
	DeviceIP         *string   `json:"device_ip"`
	DeviceUA         *string   `json:"device_ua"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceName,
		arg.DeviceIP,
		arg.DeviceUA,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.DeviceIP,
		&i.DeviceUA,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserSessionByID = `-- name: GetUserSessionByID :one
SELECT id, user_id, refresh_token_hash, device_name, device_ip, device_ua, is_active, last_used_at, created_at, expires_at FROM user_sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.DeviceIP,
		&i.DeviceUA,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserSessionByRefreshTokenHash = `-- name: GetUserSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, device_name, device_ip, device_ua, is_active, last_used_at, created_at, expires_at FROM user_sessions
WHERE refresh_token_hash = $1 AND is_active = true AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetUserSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByRefreshTokenHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.DeviceIP,
		&i.DeviceUA,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveSessionsByUserID = `-- name: ListActiveSessionsByUserID :many
SELECT id, user_id, refresh_token_hash, device_name, device_ip, device_ua, is_active, last_used_at, created_at, expires_at FROM user_sessions
WHERE user_id = $1 AND is_active = true AND expires_at > NOW()
ORDER BY last_used_at DESC
`

func (q *Queries) ListActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.DeviceName,
			&i.DeviceIP,
			&i.DeviceUA,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllOtherSessions = `-- name: RevokeAllOtherSessions :exec
UPDATE user_sessions SET is_active = false WHERE user_id = $1 AND id != $2
`

type RevokeAllOtherSessionsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ExcludeID uuid.UUID `json:"exclude_id"`
}

func (q *Queries) RevokeAllOtherSessions(ctx context.Context, arg RevokeAllOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllOtherSessions, arg.UserID, arg.ExcludeID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions SET is_active = false WHERE user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeUserSessionByID = `-- name: RevokeUserSessionByID :exec
UPDATE user_sessions SET is_active = false WHERE id = $1 AND user_id = $2
`

type RevokeUserSessionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeUserSessionByID(ctx context.Context, arg RevokeUserSessionByIDParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessionByID, arg.ID, arg.UserID)
	return err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE user_sessions SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, id)
	return err
}

const updateSessionRefreshTokenHash = `-- name: UpdateSessionRefreshTokenHash :exec
UPDATE user_sessions
SET refresh_token_hash = $2, last_used_at = NOW()
WHERE id = $1
`

type UpdateSessionRefreshTokenHashParams struct {
	ID               uuid.UUID `json:"id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
}

func (q *Queries) UpdateSessionRefreshTokenHash(ctx context.Context, arg UpdateSessionRefreshTokenHashParams) error {
	_, err := q.db.Exec(ctx, updateSessionRefreshTokenHash, arg.ID, arg.RefreshTokenHash)
	return err
}
