// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sumsub.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSumsubVerification = `-- name: CreateSumsubVerification :one
INSERT INTO sumsub_verifications (
    user_id,
    applicant_id,
    level_name,
    access_token
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, applicant_id, level_name, access_token, status, result_data, created_at, updated_at
`

type CreateSumsubVerificationParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ApplicantID string    `json:"applicant_id"`
	LevelName   string    `json:"level_name"`
	AccessToken string    `json:"access_token"`
}

func (q *Queries) CreateSumsubVerification(ctx context.Context, arg CreateSumsubVerificationParams) (SumsubVerification, error) {
	row := q.db.QueryRow(ctx, createSumsubVerification,
		arg.UserID,
		arg.ApplicantID,
		arg.LevelName,
		arg.AccessToken,
	)
	var i SumsubVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantID,
		&i.LevelName,
		&i.AccessToken,
		&i.Status,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSumsubVerificationByApplicantID = `-- name: GetSumsubVerificationByApplicantID :one
SELECT id, user_id, applicant_id, level_name, access_token, status, result_data, created_at, updated_at FROM sumsub_verifications
WHERE applicant_id = $1 LIMIT 1
`

func (q *Queries) GetSumsubVerificationByApplicantID(ctx context.Context, applicantID string) (SumsubVerification, error) {
	row := q.db.QueryRow(ctx, getSumsubVerificationByApplicantID, applicantID)
	var i SumsubVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantID,
		&i.LevelName,
		&i.AccessToken,
		&i.Status,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSumsubVerificationByUserID = `-- name: GetSumsubVerificationByUserID :one
SELECT id, user_id, applicant_id, level_name, access_token, status, result_data, created_at, updated_at FROM sumsub_verifications
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSumsubVerificationByUserID(ctx context.Context, userID uuid.UUID) (SumsubVerification, error) {
	row := q.db.QueryRow(ctx, getSumsubVerificationByUserID, userID)
	var i SumsubVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantID,
		&i.LevelName,
		&i.AccessToken,
		&i.Status,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSumsubVerificationStatus = `-- name: UpdateSumsubVerificationStatus :one
UPDATE sumsub_verifications
SET status = $2,
    result_data = $3,
    updated_at = now()
WHERE applicant_id = $1
RETURNING id, user_id, applicant_id, level_name, access_token, status, result_data, created_at, updated_at
`

type UpdateSumsubVerificationStatusParams struct {
	ApplicantID string `json:"applicant_id"`
	Status      string `json:"status"`
	ResultData  []byte `json:"result_data"`
}

func (q *Queries) UpdateSumsubVerificationStatus(ctx context.Context, arg UpdateSumsubVerificationStatusParams) (SumsubVerification, error) {
	row := q.db.QueryRow(ctx, updateSumsubVerificationStatus, arg.ApplicantID, arg.Status, arg.ResultData)
	var i SumsubVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantID,
		&i.LevelName,
		&i.AccessToken,
		&i.Status,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
