// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support_extra.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getSupportTicketWithMessages = `-- name: GetSupportTicketWithMessages :one
SELECT
    t.id, t.user_id, t.subject, t.status, t.created_at,
    COALESCE(json_agg(m.*), '[]')::jsonb as messages
FROM support_tickets t
LEFT JOIN support_messages m ON m.ticket_id = t.id
WHERE t.id = $1
GROUP BY t.id
`

type GetSupportTicketWithMessagesRow struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Subject   string          `json:"subject"`
	Status    string          `json:"status"`
	CreatedAt time.Time       `json:"created_at"`
	Messages  json.RawMessage `json:"messages"`
}

func (q *Queries) GetSupportTicketWithMessages(ctx context.Context, id uuid.UUID) (GetSupportTicketWithMessagesRow, error) {
	row := q.db.QueryRow(ctx, getSupportTicketWithMessages, id)
	var i GetSupportTicketWithMessagesRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.CreatedAt,
		&i.Messages,
	)
	return i, err
}
