// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions_extra.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActivity = `-- name: CountActivity :one
SELECT count(*)
FROM transactions
WHERE account_id IN (SELECT id FROM accounts WHERE user_id = $1)
  AND ($2::text = '' OR type = $2)
  AND ($3::text = '' OR description ILIKE '%' || $3 || '%')
`

type CountActivityParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TypeFilter string    `json:"type_filter"`
	Search     string    `json:"search"`
}

func (q *Queries) CountActivity(ctx context.Context, arg CountActivityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivity, arg.UserID, arg.TypeFilter, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActivity = `-- name: ListActivity :many
SELECT
    ('tx-' || id::text)::text as id,
    type as type,
    COALESCE(description, '')::text as title,
    amount::float8 as amount,
    currency as currency,
    status as status,
    ''::text as source,
    ''::text as asset,
    ''::text as amount_sign,
    COALESCE(description, '')::text as description,
    ''::text as counter_name,
    created_at as created_at
FROM transactions
WHERE account_id IN (SELECT id FROM accounts WHERE user_id = $1)
  AND ($4::text = '' OR type = $4)
  AND ($5::text = '' OR description ILIKE '%' || $5 || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListActivityParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Offset     int32     `json:"offset"`
	Limit      int32     `json:"limit"`
	TypeFilter string    `json:"type_filter"`
	Search     string    `json:"search"`
}

type ListActivityRow struct {
	ID          string    `json:"id"`
	Type        string    `json:"type"`
	Title       string    `json:"title"`
	Amount      float64   `json:"amount"`
	Currency    string    `json:"currency"`
	Status      string    `json:"status"`
	Source      string    `json:"source"`
	Asset       string    `json:"asset"`
	AmountSign  string    `json:"amount_sign"`
	Description string    `json:"description"`
	CounterName string    `json:"counter_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity,
		arg.UserID,
		arg.Offset,
		arg.Limit,
		arg.TypeFilter,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRow{}
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Source,
			&i.Asset,
			&i.AmountSign,
			&i.Description,
			&i.CounterName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT
    ('tx-' || id::text)::text as id,
    type as type,
    COALESCE(description, '')::text as title,
    amount::float8 as amount,
    currency as currency,
    status as status,
    ''::text as source,
    ''::text as asset,
    ''::text as amount_sign,
    COALESCE(description, '')::text as description,
    ''::text as counter_name,
    created_at as created_at
FROM transactions
WHERE account_id IN (SELECT id FROM accounts WHERE user_id = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRecentActivityParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListRecentActivityRow struct {
	ID          string    `json:"id"`
	Type        string    `json:"type"`
	Title       string    `json:"title"`
	Amount      float64   `json:"amount"`
	Currency    string    `json:"currency"`
	Status      string    `json:"status"`
	Source      string    `json:"source"`
	Asset       string    `json:"asset"`
	AmountSign  string    `json:"amount_sign"`
	Description string    `json:"description"`
	CounterName string    `json:"counter_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]ListRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, listRecentActivity, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentActivityRow{}
	for rows.Next() {
		var i ListRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Source,
			&i.Asset,
			&i.AmountSign,
			&i.Description,
			&i.CounterName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
