// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByAccount = `-- name: CountTransactionsByAccount :one
SELECT COUNT(*) FROM transactions WHERE account_id = $1
`

func (q *Queries) CountTransactionsByAccount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (reference, account_id, type, amount, currency, fee, description, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, reference, account_id, type, amount, currency, fee, description, status, metadata, created_at, updated_at
`

type CreateTransactionParams struct {
	Reference   string         `json:"reference"`
	AccountID   uuid.UUID      `json:"account_id"`
	Type        string         `json:"type"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    string         `json:"currency"`
	Fee         pgtype.Numeric `json:"fee"`
	Description *string        `json:"description"`
	Status      string         `json:"status"`
	Metadata    []byte         `json:"metadata"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Reference,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.Fee,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Fee,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, reference, account_id, type, amount, currency, fee, description, status, metadata, created_at, updated_at FROM transactions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Fee,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByReference = `-- name: GetTransactionByReference :one
SELECT id, reference, account_id, type, amount, currency, fee, description, status, metadata, created_at, updated_at FROM transactions WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetTransactionByReference(ctx context.Context, reference string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByReference, reference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Fee,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, reference, account_id, type, amount, currency, fee, description, status, metadata, created_at, updated_at FROM transactions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Fee,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, reference, account_id, type, amount, currency, fee, description, status, metadata, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.ID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Fee,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
