// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone_number, email, first_name, last_name, pin_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn
`

type CreateUserParams struct {
	PhoneNumber string  `json:"phone_number"`
	Email       *string `json:"email"`
	FirstName   string  `json:"first_name"`
	LastName    string  `json:"last_name"`
	PinHash     *string `json:"pin_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PhoneNumber,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PinHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn FROM users WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const updateUserKYCStatus = `-- name: UpdateUserKYCStatus :one
UPDATE users
SET kyc_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn
`

type UpdateUserKYCStatusParams struct {
	ID        uuid.UUID `json:"id"`
	KycStatus string    `json:"kyc_status"`
}

func (q *Queries) UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserKYCStatus, arg.ID, arg.KycStatus)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const updateUserPinHash = `-- name: UpdateUserPinHash :exec
UPDATE users
SET pin_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPinHashParams struct {
	ID      uuid.UUID `json:"id"`
	PinHash *string   `json:"pin_hash"`
}

func (q *Queries) UpdateUserPinHash(ctx context.Context, arg UpdateUserPinHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPinHash, arg.ID, arg.PinHash)
	return err
}
