// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_extra.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBusinessUser = `-- name: CreateBusinessUser :one
INSERT INTO users (
    phone_number, email, first_name, last_name, pin_hash, country, role, auth_provider, account_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'business'
) RETURNING id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn
`

type CreateBusinessUserParams struct {
	PhoneNumber  string  `json:"phone_number"`
	Email        *string `json:"email"`
	FirstName    string  `json:"first_name"`
	LastName     string  `json:"last_name"`
	PinHash      *string `json:"pin_hash"`
	Country      *string `json:"country"`
	Role         string  `json:"role"`
	AuthProvider string  `json:"auth_provider"`
}

func (q *Queries) CreateBusinessUser(ctx context.Context, arg CreateBusinessUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createBusinessUser,
		arg.PhoneNumber,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PinHash,
		arg.Country,
		arg.Role,
		arg.AuthProvider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (
    email, first_name, last_name, google_sub, role, auth_provider
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn
`

type CreateGoogleUserParams struct {
	Email        *string `json:"email"`
	FirstName    string  `json:"first_name"`
	LastName     string  `json:"last_name"`
	GoogleSub    *string `json:"google_sub"`
	Role         string  `json:"role"`
	AuthProvider string  `json:"auth_provider"`
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.GoogleSub,
		arg.Role,
		arg.AuthProvider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const createIndividualUser = `-- name: CreateIndividualUser :one
INSERT INTO users (
    phone_number, email, first_name, last_name, pin_hash, country, role, auth_provider, account_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'individual'
) RETURNING id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn
`

type CreateIndividualUserParams struct {
	PhoneNumber  string  `json:"phone_number"`
	Email        *string `json:"email"`
	FirstName    string  `json:"first_name"`
	LastName     string  `json:"last_name"`
	PinHash      *string `json:"pin_hash"`
	Country      *string `json:"country"`
	Role         string  `json:"role"`
	AuthProvider string  `json:"auth_provider"`
}

func (q *Queries) CreateIndividualUser(ctx context.Context, arg CreateIndividualUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createIndividualUser,
		arg.PhoneNumber,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PinHash,
		arg.Country,
		arg.Role,
		arg.AuthProvider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn FROM users WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const getUserFullByID = `-- name: GetUserFullByID :one
SELECT id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn FROM users WHERE id = $1
`

func (q *Queries) GetUserFullByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserFullByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const getUserSecurity = `-- name: GetUserSecurity :one
SELECT id, totp_enabled, totp_secret, pin_hash FROM users WHERE id = $1
`

type GetUserSecurityRow struct {
	ID          uuid.UUID `json:"id"`
	TOTPEnabled bool      `json:"totp_enabled"`
	TOTPSecret  *string   `json:"totp_secret"`
	PinHash     *string   `json:"pin_hash"`
}

func (q *Queries) GetUserSecurity(ctx context.Context, id uuid.UUID) (GetUserSecurityRow, error) {
	row := q.db.QueryRow(ctx, getUserSecurity, id)
	var i GetUserSecurityRow
	err := row.Scan(
		&i.ID,
		&i.TOTPEnabled,
		&i.TOTPSecret,
		&i.PinHash,
	)
	return i, err
}

const promoteUserToOwnerByPhone = `-- name: PromoteUserToOwnerByPhone :one
UPDATE users SET role = 'owner', updated_at = now() WHERE phone_number = $1
RETURNING id, phone_number, email, role
`

type PromoteUserToOwnerByPhoneRow struct {
	ID          uuid.UUID `json:"id"`
	PhoneNumber string    `json:"phone_number"`
	Email       *string   `json:"email"`
	Role        string    `json:"role"`
}

func (q *Queries) PromoteUserToOwnerByPhone(ctx context.Context, phoneNumber string) (PromoteUserToOwnerByPhoneRow, error) {
	row := q.db.QueryRow(ctx, promoteUserToOwnerByPhone, phoneNumber)
	var i PromoteUserToOwnerByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const setUserBVN = `-- name: SetUserBVN :one
UPDATE users SET bvn = $2, updated_at = now() WHERE id = $1 RETURNING id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn
`

type SetUserBVNParams struct {
	ID  uuid.UUID `json:"id"`
	Bvn *string   `json:"bvn"`
}

func (q *Queries) SetUserBVN(ctx context.Context, arg SetUserBVNParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserBVN, arg.ID, arg.Bvn)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users SET is_email_verified = true, updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    bio = COALESCE($4, bio),
    avatar_url = COALESCE($5, avatar_url),
    date_of_birth = COALESCE($6, date_of_birth),
    nationality = COALESCE($7, nationality),
    bvn = COALESCE($8, bvn),
    updated_at = now()
WHERE id = $1
RETURNING id, phone_number, email, first_name, last_name, pin_hash, kyc_status, is_active, created_at, updated_at, bio, avatar_url, date_of_birth, nationality, is_email_verified, role, auth_provider, google_sub, totp_secret, totp_enabled, account_type, country, kyc_provider, referral_code, referred_by, kyc_provider_status, kyc_manual_override, bvn
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID `json:"id"`
	FirstName   *string   `json:"first_name"`
	LastName    *string   `json:"last_name"`
	Bio         *string   `json:"bio"`
	AvatarURL   *string   `json:"avatar_url"`
	DateOfBirth *string   `json:"date_of_birth"`
	Nationality *string   `json:"nationality"`
	Bvn         *string   `json:"bvn"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Bio,
		arg.AvatarURL,
		arg.DateOfBirth,
		arg.Nationality,
		arg.Bvn,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PinHash,
		&i.KycStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarURL,
		&i.DateOfBirth,
		&i.Nationality,
		&i.IsEmailVerified,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleSub,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.AccountType,
		&i.Country,
		&i.KycProvider,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.KycProviderStatus,
		&i.KycManualOverride,
		&i.Bvn,
	)
	return i, err
}
