// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vtu.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVTUTransaction = `-- name: CreateVTUTransaction :one
INSERT INTO vtu_transactions (
    user_id, account_id, amount, currency, service_type, provider, target_phone, target_account, reference, provider_ref, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, user_id, account_id, amount, currency, service_type, provider, target_phone, target_account, reference, provider_ref, status, created_at, updated_at
`

type CreateVTUTransactionParams struct {
	UserID        uuid.UUID `json:"user_id"`
	AccountID     uuid.UUID `json:"account_id"`
	Amount        string    `json:"amount"`
	Currency      string    `json:"currency"`
	ServiceType   string    `json:"service_type"`
	Provider      string    `json:"provider"`
	TargetPhone   *string   `json:"target_phone"`
	TargetAccount *string   `json:"target_account"`
	Reference     *string   `json:"reference"`
	ProviderRef   *string   `json:"provider_ref"`
	Status        string    `json:"status"`
}

func (q *Queries) CreateVTUTransaction(ctx context.Context, arg CreateVTUTransactionParams) (VtuTransaction, error) {
	row := q.db.QueryRow(ctx, createVTUTransaction,
		arg.UserID,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.ServiceType,
		arg.Provider,
		arg.TargetPhone,
		arg.TargetAccount,
		arg.Reference,
		arg.ProviderRef,
		arg.Status,
	)
	var i VtuTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.ServiceType,
		&i.Provider,
		&i.TargetPhone,
		&i.TargetAccount,
		&i.Reference,
		&i.ProviderRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVTUTransactionByReference = `-- name: GetVTUTransactionByReference :one
SELECT id, user_id, account_id, amount, currency, service_type, provider, target_phone, target_account, reference, provider_ref, status, created_at, updated_at FROM vtu_transactions
WHERE reference = $1
`

func (q *Queries) GetVTUTransactionByReference(ctx context.Context, reference *string) (VtuTransaction, error) {
	row := q.db.QueryRow(ctx, getVTUTransactionByReference, reference)
	var i VtuTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.ServiceType,
		&i.Provider,
		&i.TargetPhone,
		&i.TargetAccount,
		&i.Reference,
		&i.ProviderRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVTUTransactionsByUserID = `-- name: ListVTUTransactionsByUserID :many
SELECT id, user_id, account_id, amount, currency, service_type, provider, target_phone, target_account, reference, provider_ref, status, created_at, updated_at FROM vtu_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListVTUTransactionsByUserID(ctx context.Context, userID uuid.UUID) ([]VtuTransaction, error) {
	rows, err := q.db.Query(ctx, listVTUTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VtuTransaction{}
	for rows.Next() {
		var i VtuTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.ServiceType,
			&i.Provider,
			&i.TargetPhone,
			&i.TargetAccount,
			&i.Reference,
			&i.ProviderRef,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVTUTransactionStatus = `-- name: UpdateVTUTransactionStatus :one
UPDATE vtu_transactions
SET status = $2,
    provider_ref = COALESCE($3, provider_ref),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, account_id, amount, currency, service_type, provider, target_phone, target_account, reference, provider_ref, status, created_at, updated_at
`

type UpdateVTUTransactionStatusParams struct {
	ID          uuid.UUID `json:"id"`
	Status      string    `json:"status"`
	ProviderRef *string   `json:"provider_ref"`
}

func (q *Queries) UpdateVTUTransactionStatus(ctx context.Context, arg UpdateVTUTransactionStatusParams) (VtuTransaction, error) {
	row := q.db.QueryRow(ctx, updateVTUTransactionStatus, arg.ID, arg.Status, arg.ProviderRef)
	var i VtuTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.ServiceType,
		&i.Provider,
		&i.TargetPhone,
		&i.TargetAccount,
		&i.Reference,
		&i.ProviderRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
