// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWaasWallet = `-- name: CreateWaasWallet :one

INSERT INTO waas_wallets (user_id, waas_wallet_id, network, address, is_default)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, waas_wallet_id, network, address, is_default, created_at
`

type CreateWaasWalletParams struct {
	UserID       uuid.UUID `json:"user_id"`
	WaasWalletID string    `json:"waas_wallet_id"`
	Network      string    `json:"network"`
	Address      string    `json:"address"`
	IsDefault    bool      `json:"is_default"`
}

// ─── WaaS (Payments API custody wallets) ──────────────────────────────────
func (q *Queries) CreateWaasWallet(ctx context.Context, arg CreateWaasWalletParams) (WaasWallet, error) {
	row := q.db.QueryRow(ctx, createWaasWallet,
		arg.UserID,
		arg.WaasWalletID,
		arg.Network,
		arg.Address,
		arg.IsDefault,
	)
	var i WaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WaasWalletID,
		&i.Network,
		&i.Address,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultWaasWallet = `-- name: GetDefaultWaasWallet :one
SELECT id, user_id, waas_wallet_id, network, address, is_default, created_at FROM waas_wallets
WHERE user_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultWaasWallet(ctx context.Context, userID uuid.UUID) (WaasWallet, error) {
	row := q.db.QueryRow(ctx, getDefaultWaasWallet, userID)
	var i WaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WaasWalletID,
		&i.Network,
		&i.Address,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getWaasWalletByAddress = `-- name: GetWaasWalletByAddress :one
SELECT id, user_id, waas_wallet_id, network, address, is_default, created_at FROM waas_wallets WHERE address = $1 LIMIT 1
`

func (q *Queries) GetWaasWalletByAddress(ctx context.Context, address string) (WaasWallet, error) {
	row := q.db.QueryRow(ctx, getWaasWalletByAddress, address)
	var i WaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WaasWalletID,
		&i.Network,
		&i.Address,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getWaasWalletByIDAndUser = `-- name: GetWaasWalletByIDAndUser :one
SELECT id, user_id, waas_wallet_id, network, address, is_default, created_at FROM waas_wallets WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetWaasWalletByIDAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWaasWalletByIDAndUser(ctx context.Context, arg GetWaasWalletByIDAndUserParams) (WaasWallet, error) {
	row := q.db.QueryRow(ctx, getWaasWalletByIDAndUser, arg.ID, arg.UserID)
	var i WaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WaasWalletID,
		&i.Network,
		&i.Address,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getWaasWalletByNetwork = `-- name: GetWaasWalletByNetwork :one
SELECT id, user_id, waas_wallet_id, network, address, is_default, created_at FROM waas_wallets
WHERE user_id = $1 AND network = $2
LIMIT 1
`

type GetWaasWalletByNetworkParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Network string    `json:"network"`
}

func (q *Queries) GetWaasWalletByNetwork(ctx context.Context, arg GetWaasWalletByNetworkParams) (WaasWallet, error) {
	row := q.db.QueryRow(ctx, getWaasWalletByNetwork, arg.UserID, arg.Network)
	var i WaasWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WaasWalletID,
		&i.Network,
		&i.Address,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getWaasWalletsByUserID = `-- name: GetWaasWalletsByUserID :many
SELECT id, user_id, waas_wallet_id, network, address, is_default, created_at FROM waas_wallets WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetWaasWalletsByUserID(ctx context.Context, userID uuid.UUID) ([]WaasWallet, error) {
	rows, err := q.db.Query(ctx, getWaasWalletsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaasWallet{}
	for rows.Next() {
		var i WaasWallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WaasWalletID,
			&i.Network,
			&i.Address,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
