// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Rach Finance Engineering",
            "email": "engineering@rach.finance"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all fiat accounts (XAF, XOF, USD, GBP, EUR) for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "List accounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.AccountListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{currency}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single fiat account for the given currency code.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get account by currency",
                "parameters": [
                    {
                        "enum": [
                            "XAF",
                            "XOF",
                            "USD",
                            "GBP",
                            "EUR"
                        ],
                        "type": "string",
                        "description": "Currency code",
                        "name": "currency",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.AccountResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{currency}/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of transactions for the given currency account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "List transactions for an account",
                "parameters": [
                    {
                        "enum": [
                            "XAF",
                            "XOF",
                            "USD",
                            "GBP",
                            "EUR"
                        ],
                        "type": "string",
                        "description": "Currency code",
                        "name": "currency",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page, max 100 (default 20)",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.TransactionListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{currency}/transactions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a specific transaction by its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get a single transaction",
                "parameters": [
                    {
                        "enum": [
                            "XAF",
                            "XOF",
                            "USD",
                            "GBP",
                            "EUR"
                        ],
                        "type": "string",
                        "description": "Currency code",
                        "name": "currency",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transaction UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticates a user with phone + PIN and returns a JWT token pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.TokenPairResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Account inactive",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/otp/send": {
            "post": {
                "description": "Sends a 6-digit OTP to the provided phone number. Must be called before register or login.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Send OTP",
                "parameters": [
                    {
                        "description": "Phone number in E.164 format",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.SendOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/otp/verify": {
            "post": {
                "description": "Confirms that the OTP sent to the phone is correct. Call before register for new users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify OTP",
                "parameters": [
                    {
                        "description": "Phone + OTP code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user account and returns a JWT token pair. OTP must have been verified first.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "New user details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.TokenPairResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Phone number already registered",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/token/refresh": {
            "post": {
                "description": "Issues a new access + refresh token pair using a valid refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.TokenPairResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired refresh token",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/crypto/balances": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the USDC balance of the caller's ERC-4337 Smart Contract Wallet from the CaaS service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "Get stablecoin balances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CryptoBalanceResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/crypto/fund": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Step 4–5 of the Instant USD Account flow. Initiates a HUB2 Mobile Money collection: the customer receives a push-to-pay prompt on their phone. After they approve, HUB2 fires a webhook which triggers DigitalFX to instruct Rach CaaS to convert the XOF/XAF to USDC/USDT and credit the customer's ERC-4337 Smart Contract Wallet. The customer sees their updated balance via GET /crypto/balances once Rach CaaS confirms the fiat and completes the OTC conversion.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "Fund Instant USD Account via Mobile Money",
                "parameters": [
                    {
                        "description": "Funding request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.FundAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "HUB2 collection reference — poll status or wait for balance update",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.Hub2RefResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/crypto/send": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transfers stablecoins (USDT or USDC) from the caller to another DigitalFX user identified by phone number. An FX quote is obtained first, then the CaaS P2P transfer is executed. Amount is in USD-equivalent decimal (e.g. \"50.00\").",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "Send USDT or USDC to another user",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.SendCryptoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CryptoTxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/crypto/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of crypto (USDT/USDC) transactions for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "List crypto transactions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page, max 100 (default 20)",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CryptoTxListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/crypto/transactions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single crypto transaction by its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "Get a crypto transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CryptoTxResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/crypto/wallet": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the caller's ERC-4337 Smart Contract Wallet (SCW), provisioning it on the CaaS service if this is the first call. The wallet is identified by the user's phone number.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "Get or create ERC-4337 abstraction wallet",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CaasWalletResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/kyc/documents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all identity documents submitted by the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "List KYC documents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.KYCDocumentListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Records a KYC document for manual review. The doc_url should be a GCS signed URL or object path obtained from the client-side upload flow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Submit a KYC document",
                "parameters": [
                    {
                        "description": "Document metadata",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.KYCDocumentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.KYCDocumentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/kyc/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the current KYC verification status for the authenticated user. Possible values: pending, approved, rejected.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Get KYC status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.KYCStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transfers/exchange": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Converts between supported fiat currencies at the current FX rate. Rate provider integration is pending.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Exchange currency",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.MessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transfers/hub2": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Initiates either a collection (deposit) or disbursement (withdrawal) via the HUB2 Mobile Money gateway for XAF/XOF operators (MTN, Orange).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Mobile Money payment via HUB2",
                "parameters": [
                    {
                        "description": "Payment details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.Hub2PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.Hub2RefResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transfers/internal": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transfers fiat funds between two DigitalFX users using their phone numbers. Both sender and receiver must have an account in the requested currency.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Internal fiat transfer",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.InternalTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wallets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all on-chain HD wallets (BIP-44) provisioned for the authenticated user via the Rach WaaS service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "List HD wallets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.WalletListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Provisions an HD wallet seed (if not already created) and derives a deposit address for the given blockchain network. Idempotent — safe to call again for the same network.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Create HD wallet for a network",
                "parameters": [
                    {
                        "description": "Network selection",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CreateWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.WalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wallets/deposit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Initiates a Mobile Money collection (deposit) via HUB2, crediting the user's fiat account when confirmed. Returns the HUB2 reference for webhook correlation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Initiate Mobile Money deposit",
                "parameters": [
                    {
                        "description": "Deposit details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.DepositRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.Hub2RefResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wallets/withdraw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Initiates a Mobile Money disbursement (withdrawal) via HUB2, debiting the user's fiat account. Returns the HUB2 reference for tracking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Initiate Mobile Money withdrawal",
                "parameters": [
                    {
                        "description": "Withdrawal details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.WithdrawalRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.Hub2RefResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{walletId}/address": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the deposit address for the specified wallet ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Get deposit address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet UUID",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.WalletResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/webhooks/hub2": {
            "post": {
                "description": "Receives Mobile Money payment status updates from HUB2. On a COLLECTION SUCCESSFUL event, DigitalFX automatically credits the user's CaaS USDC wallet. The request must carry a valid HMAC-SHA256 signature in the X-Hub2-Signature header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "HUB2 payment webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 signature: sha256=\u003chex\u003e",
                        "name": "X-Hub2-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "HUB2 webhook payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.HUB2WebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Invalid signature",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api_handlers.AccountData": {
            "type": "object",
            "properties": {
                "account_number": {
                    "type": "string",
                    "example": "DFX0000001"
                },
                "available_balance": {
                    "type": "string",
                    "example": "5000.000000"
                },
                "balance": {
                    "type": "string",
                    "example": "5000.000000"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string",
                    "example": "XAF"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                }
            }
        },
        "internal_api_handlers.AccountListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_handlers.AccountData"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.AccountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.AccountData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.BalanceData": {
            "type": "object",
            "properties": {
                "balance_usdc": {
                    "type": "string",
                    "example": "100.000000"
                },
                "wallet_address": {
                    "type": "string",
                    "example": "0xSCW123..."
                }
            }
        },
        "internal_api_handlers.CaasWalletData": {
            "type": "object",
            "properties": {
                "abstraction_address": {
                    "type": "string",
                    "example": "0xSCW123..."
                },
                "caas_wallet_id": {
                    "type": "string",
                    "example": "0xblindindex..."
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.CaasWalletResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.CaasWalletData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.CreateWalletRequest": {
            "type": "object",
            "properties": {
                "network": {
                    "description": "Network is the blockchain network. Supported: BTC BCH LTC BSC ETH POL TRX SOL XRP",
                    "type": "string",
                    "enum": [
                        "BTC",
                        "BCH",
                        "LTC",
                        "BSC",
                        "ETH",
                        "POL",
                        "TRX",
                        "SOL",
                        "XRP"
                    ],
                    "example": "ETH"
                }
            }
        },
        "internal_api_handlers.CryptoBalanceResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.BalanceData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.CryptoTxData": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "50.00"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "receiver_phone": {
                    "type": "string",
                    "example": "+237698765432"
                },
                "reference": {
                    "type": "string",
                    "example": "CRYPTO-REF-001"
                },
                "sender_user_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "token": {
                    "type": "string",
                    "example": "USDC"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.CryptoTxListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_handlers.CryptoTxData"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.CryptoTxResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.CryptoTxData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.DepositRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 5000
                },
                "currency": {
                    "type": "string",
                    "example": "XAF"
                },
                "operator": {
                    "type": "string",
                    "example": "MTN"
                },
                "phone": {
                    "type": "string",
                    "example": "+237612345678"
                }
            }
        },
        "internal_api_handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "VALIDATION_ERROR"
                        },
                        "message": {
                            "type": "string",
                            "example": "phone is required"
                        }
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_api_handlers.FundAccountRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Amount in local fiat (minimum 100)",
                    "type": "number",
                    "minimum": 100,
                    "example": 20000
                },
                "currency": {
                    "description": "Currency of the Mobile Money deposit: XOF or XAF",
                    "type": "string",
                    "enum": [
                        "XOF",
                        "XAF"
                    ],
                    "example": "XOF"
                },
                "operator": {
                    "description": "Operator is the Mobile Money provider",
                    "type": "string",
                    "enum": [
                        "Orange",
                        "MTN",
                        "Wave",
                        "Moov",
                        "Airtel"
                    ],
                    "example": "MTN"
                },
                "phone": {
                    "description": "Phone is the Mobile Money number to pull from (E.164)",
                    "type": "string",
                    "example": "+22507000000"
                },
                "token": {
                    "description": "Token is the target stablecoin — defaults to USDC",
                    "type": "string",
                    "enum": [
                        "USDC",
                        "USDT"
                    ],
                    "example": "USDC"
                }
            }
        },
        "internal_api_handlers.HUB2WebhookRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 20000
                },
                "currency": {
                    "type": "string",
                    "example": "XOF"
                },
                "phone": {
                    "type": "string",
                    "example": "+22507000000"
                },
                "reference": {
                    "type": "string",
                    "example": "HUB2-REF-001"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "SUCCESSFUL",
                        "FAILED",
                        "CANCELLED",
                        "PENDING"
                    ],
                    "example": "SUCCESSFUL"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "COLLECTION",
                        "DISBURSEMENT"
                    ],
                    "example": "COLLECTION"
                }
            }
        },
        "internal_api_handlers.Hub2PaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 5000
                },
                "currency": {
                    "type": "string",
                    "example": "XAF"
                },
                "direction": {
                    "description": "Direction: collection (deposit) or disbursement (withdrawal)",
                    "type": "string",
                    "enum": [
                        "collection",
                        "disbursement"
                    ],
                    "example": "collection"
                },
                "operator": {
                    "type": "string",
                    "example": "MTN"
                },
                "payment_method": {
                    "description": "PaymentMethod e.g. mobile_money",
                    "type": "string",
                    "example": "mobile_money"
                },
                "phone": {
                    "type": "string",
                    "example": "+237612345678"
                }
            }
        },
        "internal_api_handlers.Hub2RefData": {
            "type": "object",
            "properties": {
                "hub2_reference": {
                    "type": "string",
                    "example": "HUB2-REF-001"
                }
            }
        },
        "internal_api_handlers.Hub2RefResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.Hub2RefData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.InternalTransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 5000
                },
                "currency": {
                    "type": "string",
                    "example": "XAF"
                },
                "description": {
                    "type": "string",
                    "example": "Monthly payment"
                },
                "receiver_phone": {
                    "type": "string",
                    "example": "+237698765432"
                }
            }
        },
        "internal_api_handlers.KYCDocumentData": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "doc_type": {
                    "type": "string",
                    "example": "national_id"
                },
                "doc_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "rejection_reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.KYCDocumentListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_handlers.KYCDocumentData"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.KYCDocumentRequest": {
            "type": "object",
            "properties": {
                "doc_type": {
                    "description": "DocType one of: national_id | passport | selfie | proof_of_address",
                    "type": "string",
                    "enum": [
                        "national_id",
                        "passport",
                        "selfie",
                        "proof_of_address"
                    ],
                    "example": "national_id"
                },
                "doc_url": {
                    "description": "DocURL is the GCS object path or signed URL returned by the upload endpoint",
                    "type": "string",
                    "example": "https://storage.googleapis.com/digitalfx-kyc-dev/doc.jpg"
                }
            }
        },
        "internal_api_handlers.KYCDocumentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.KYCDocumentData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.KYCStatusData": {
            "type": "object",
            "properties": {
                "kyc_status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "approved",
                        "rejected"
                    ],
                    "example": "pending"
                }
            }
        },
        "internal_api_handlers.KYCStatusResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.KYCStatusData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.LoginRequest": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string",
                    "example": "+237612345678"
                },
                "pin": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "internal_api_handlers.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "OTP sent"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.PaginationMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "per_page": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "internal_api_handlers.RefreshTokenRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGci..."
                }
            }
        },
        "internal_api_handlers.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Alice"
                },
                "last_name": {
                    "type": "string",
                    "example": "Dupont"
                },
                "phone": {
                    "type": "string",
                    "example": "+237612345678"
                },
                "pin": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "internal_api_handlers.SendCryptoRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "50.00"
                },
                "receiver_phone": {
                    "type": "string",
                    "example": "+237698765432"
                },
                "token": {
                    "description": "Token must be USDT or USDC",
                    "type": "string",
                    "enum": [
                        "USDT",
                        "USDC"
                    ],
                    "example": "USDC"
                }
            }
        },
        "internal_api_handlers.SendOTPRequest": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string",
                    "example": "+237612345678"
                }
            }
        },
        "internal_api_handlers.TokenPairData": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGci..."
                },
                "expires_in": {
                    "type": "integer",
                    "example": 1800
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGci..."
                }
            }
        },
        "internal_api_handlers.TokenPairResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.TokenPairData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.TransactionData": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "amount": {
                    "type": "string",
                    "example": "5000.000000"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string",
                    "example": "XAF"
                },
                "description": {
                    "type": "string",
                    "example": "Deposit via MTN Mobile Money"
                },
                "fee": {
                    "type": "string",
                    "example": "0.000000"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "reference": {
                    "type": "string",
                    "example": "TXN-20240101-001"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "type": {
                    "type": "string",
                    "example": "credit"
                }
            }
        },
        "internal_api_handlers.TransactionListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_handlers.TransactionData"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/internal_api_handlers.PaginationMeta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.TransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.TransactionData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.VerifyOTPRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "+237612345678"
                }
            }
        },
        "internal_api_handlers.WalletData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xabc123..."
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "network": {
                    "type": "string",
                    "example": "ETH"
                },
                "user_id": {
                    "type": "string"
                },
                "waas_wallet_id": {
                    "type": "string",
                    "example": "cust_abc123"
                }
            }
        },
        "internal_api_handlers.WalletListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_handlers.WalletData"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.WalletResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_api_handlers.WalletData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_handlers.WithdrawalRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 5000
                },
                "currency": {
                    "type": "string",
                    "example": "XAF"
                },
                "operator": {
                    "type": "string",
                    "example": "ORANGE"
                },
                "phone": {
                    "type": "string",
                    "example": "+237612345678"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT access token — prefix with \"Bearer \": Bearer eyJhbGci...",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DigitalFX API",
	Description:      "DigitalFX is a multi-currency fintech platform for Central/West Africa.\nIt combines fiat accounts (XAF, XOF, USD, GBP, EUR), HD crypto wallets (BIP-44 via Rach WaaS),\nand stablecoin P2P transfers (USDC/USDT via Rach CaaS ERC-4337 SCWs).\nMobile Money deposits and withdrawals are handled via HUB2 (MTN, Orange).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
